### ISSUE TITLE
BCC-Maps Tab goes to Adressumschreibung

### ISSUE THREAD

**Issue by C78dev** [mailcow/mailcow-dockerized#1108]
Hello,

after clean install on an new Server the configuration -> mailboxes section over mailcow UI was changed.

"new" Server
![new](https://user-images.githubusercontent.com/36932852/36810729-df27e942-1ccb-11e8-92a5-5cbeb8c42026.png)

"Old" Server (installed two days ago)
![old](https://user-images.githubusercontent.com/36932852/36810748-f0198ca6-1ccb-11e8-9fe4-6c8c75e6d362.png)

I think there is either another tab or a dropdown missing.

Thanks :)

**Comment by mkuron** [comment]
No, that is all correct. If you log in with server admin (and not just domain admin) privileges, the address rewriting tab will also let you configure recipient maps. Domain admins can only configure Bcc maps as the recipient maps apply to all domains. Both Bcc maps and recipient maps are essentially address rewriting, which is why they are available on the same tab.
