### ISSUE TITLE
any way to disable grelist ?

### ISSUE THREAD

**Issue by changchichung** [mailcow/mailcow-dockerized#1134]
many emails come from our suppliers  always soft reject by greylist
is there anyway to disabled to greylisting ?

**Comment by mkuron** [comment]
The greylisting happens if the messages are just below the spam threshold (5 by default). You can check the rspamd web interface to see why it thinks that the messages from your suppliers are spam.

Simply disabling greylisting most likely won‘t help as some messages might be above the threshold to get tagged as spam. So what you probably want to do is to add your suppliers‘ domains to the whitelist. This can either be done per-user or per-domain in the mailcow web interface.

**Comment by mkuron** [comment]
If you actually want to disable greylisting altogether (and not do what I wrote yesterday), this is a duplicate of #413.

**Comment by changchichung** [comment]
did you mean 
```
You can just disable the MX check module:

cd /somewhere/mailcow-dockerized
echo "enabled = false;" > data/conf/rspamd/local.d/mx_check.conf
docker-compose restart rspamd-mailcow
```

yup , I already tried that , but greylist is still working ..

**Comment by mkuron** [comment]
Mx_check is not related to greylisting, so don’t change that setting.

You cannot currently easily disable greylisting. But you most likely don’t want to do that anyway: your problem is not that these messages are greylisted, your problem is that they are false-positively recognized as spam. That should be fixed by whitelisting the sender in the web UI.

**Comment by wuast94** [comment]
I want to disable it too..well a greylistet email is bad becouse I don't know that there is a mail. I must look into logs to see it and I don't want to do that. I look in my spam folder and can mark it as no spam. But Mails that I don't receive are very bad in my opinion.

**Comment by andryyy** [comment]
A greylisted mail is not a reject. It is not bad, greylisting is good.

Greylisting is "try again later".

**Comment by wuast94** [comment]
Yes but I became a steam Message today with my two factor code..and this mail greylistet is not so good becouse I need it :D

**Comment by andryyy** [comment]
Can you post the symbols of the greylisted message?

**Comment by wuast94** [comment]
![25910790-c953-46b4-89ff-582511d6659d](https://user-images.githubusercontent.com/16965460/51518499-65f64000-1e1e-11e9-8519-3621ab9c16b7.jpeg)

The first mail was greylistet..then I forced steam to send the mail again..that's the second email
