### ISSUE TITLE
Watchdog: dovecot-mailcow service hit the error rate limit

### ISSUE THREAD

**Issue by m0lmk** [mailcow/mailcow-dockerized#1138]
I've had Mailcow installed for about a week and it's working great. Catching far more spam then my old mail server.

I have the watchdog enabled and I've been getting this error for the past few days

    Watchdog: dovecot-mailcow service hit the error rate limit

I have an account that is shared between 5 users who are all checking in on multiple devices. Could this be causing the issue?

**Comment by andryyy** [comment]
Is this still an open issue?

**Comment by m0lmk** [comment]
Yes, I get the notification twice a day.

**Comment by m0lmk** [comment]
Has anyone else experienced this? I am still getting this message at least twice per day and have no idea why.

**Comment by andryyy** [comment]
Many users?

You should check the Dovecot logs for the time it happens... "tail" can be omited, but expect a flood of logs.

```
docker-compose logs --tail=2000 dovecot-mailcow
```

**Comment by m0lmk** [comment]
Thanks @andryyy. There are only around 10 users on this box but there are several users who all access the same mailbox from the same office so could they be hitting a rate limit somewhere based on connecting IP?

Where do I need to run that command? I have tried from the mailcow folder and it returned this error:

    :~/mailcow-dockerized$ docker-compose logs --tail=2000 dovecot-mailcow
    ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

    If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by andryyy** [comment]
Yes, that's actually possible, I think.

But we need the logs first. You should kill and delete all containers (all, not just mailcow) by running `docker rm -f $(docker ps -a -q)`. After that run `systemctl restart docker` and `docker-compose up -d`. 

It is possible you run a Dockerd update and mailcow was running.

**Comment by patsch** [comment]
I have the same issue, i.e. I am getting

> Watchdog: postfix-mailcow service hit the error rate limit

 It's also odd that this error keeps cropping up, i.e. after installation mailcow dockerized ran fine for weeks before this first happened, then it got quiet again after a restart, but then it pops up again and now it won't go away.

Here is the log I get with

`docker-compose logs postfix-mailcow`

It seems to die because it is sent a SIGTERM ?

Any help would be greatly appreciated.

> postfix-mailcow_1    | 2018-09-02 22:41:04,023 CRIT Set uid to user 0
postfix-mailcow_1    | 2018-09-02 22:41:04,026 INFO supervisord started with pid 1
postfix-mailcow_1    | 2018-09-02 22:41:05,029 INFO spawned: 'postfix' with pid 9
postfix-mailcow_1    | 2018-09-02 22:41:05,032 INFO spawned: 'syslog-ng' with pid 10
postfix-mailcow_1    | Sep  2 22:41:05 mx syslog-ng[10]: syslog-ng starting up; version='3.8.1'
postfix-mailcow_1    | Sep  2 22:41:05 mx postfix[240]: Postfix is running with backwards-compatible default settings
postfix-mailcow_1    | Sep  2 22:41:05 mx postfix[240]: See http://www.postfix.org/COMPATIBILITY_README.html for details
postfix-mailcow_1    | Sep  2 22:41:05 mx postfix[240]: To disable backwards compatibility use "postconf compatibility_level=2" and "postfix reload"
postfix-mailcow_1    | Sep  2 22:41:05 mx postfix/postfix-script[326]: starting the Postfix mail system
postfix-mailcow_1    | Sep  2 22:41:05 mx postfix/master[328]: daemon started -- version 3.1.6, configuration /opt/postfix/conf
postfix-mailcow_1    | 2018-09-02 22:41:06,648 INFO success: postfix entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | 2018-09-02 22:41:06,648 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix-mailcow_1    | Sep  2 22:41:45 mx postfix/postscreen[342]: CONNECT from [172.22.1.1]:51436 to [172.22.1.6]:25
postfix-mailcow_1    | Sep  2 22:41:45 mx postfix/postscreen[342]: WHITELISTED [172.22.1.1]:51436
postfix-mailcow_1    | Sep  2 22:41:45 mx postfix/smtpd[344]: connect from unknown[172.22.1.1]
postfix-mailcow_1    | Sep  2 22:41:45 mx postfix/smtp[341]: warning: host mx.mojomail.services[43.239.97.134]:25 greeted me with my own hostname mx.mojomail.services
postfix-mailcow_1    | Sep  2 22:41:45 mx postfix/smtp[341]: warning: host mx.mojomail.services[43.239.97.134]:25 replied to HELO/EHLO with my own hostname mx.mojomail.services
postfix-mailcow_1    | Sep  2 22:41:45 mx postfix/smtp[341]: 7C9F280154: to=<postmaster@mx.mojomail.services>, orig_to=<postmaster>, relay=mx.mojomail.services[43.239.97.134]:25, delay=0.08, delays=0.02/0.03/0.03/0, dsn=5.4.6, status=bounced (mail for mx.mojomail.services loops back to myself)
postfix-mailcow_1    | Sep  2 22:41:45 mx postfix/smtpd[344]: disconnect from unknown[172.22.1.1] ehlo=1 quit=1 commands=2
postfix-mailcow_1    | Sep  2 22:41:45 mx postfix/bounce[345]: warning: 7C9F280154: undeliverable postmaster notification discarded
postfix-mailcow_1    | Sep  2 22:42:25 mx postfix/postscreen[342]: CONNECT from [172.22.1.1]:51698 to [172.22.1.6]:25
postfix-mailcow_1    | Sep  2 22:42:25 mx postfix/postscreen[342]: WHITELISTED [172.22.1.1]:51698
postfix-mailcow_1    | Sep  2 22:42:25 mx postfix/smtpd[344]: connect from unknown[172.22.1.1]
postfix-mailcow_1    | Sep  2 22:42:25 mx postfix/smtp[341]: warning: host mx.mojomail.services[43.239.97.134]:25 greeted me with my own hostname mx.mojomail.services
postfix-mailcow_1    | Sep  2 22:42:25 mx postfix/smtp[341]: warning: host mx.mojomail.services[43.239.97.134]:25 replied to HELO/EHLO with my own hostname mx.mojomail.services
postfix-mailcow_1    | Sep  2 22:42:25 mx postfix/smtp[341]: 906B880154: to=<postmaster@mx.mojomail.services>, orig_to=<postmaster>, relay=mx.mojomail.services[43.239.97.134]:25, delay=0.02, delays=0.01/0/0/0, dsn=5.4.6, status=bounced (mail for mx.mojomail.services loops back to myself)
postfix-mailcow_1    | Sep  2 22:42:25 mx postfix/smtpd[344]: disconnect from unknown[172.22.1.1] ehlo=1 quit=1 commands=2
postfix-mailcow_1    | Sep  2 22:42:25 mx postfix/bounce[345]: warning: 906B880154: undeliverable postmaster notification discarded
postfix-mailcow_1    | Sep  2 22:42:57 mx postfix/postscreen[342]: CONNECT from [172.22.1.1]:51944 to [172.22.1.6]:25
postfix-mailcow_1    | Sep  2 22:42:57 mx postfix/postscreen[342]: WHITELISTED [172.22.1.1]:51944
postfix-mailcow_1    | Sep  2 22:42:57 mx postfix/smtpd[344]: connect from unknown[172.22.1.1]
postfix-mailcow_1    | Sep  2 22:42:57 mx postfix/smtp[341]: warning: host mx.mojomail.services[43.239.97.134]:25 greeted me with my own hostname mx.mojomail.services
postfix-mailcow_1    | Sep  2 22:42:57 mx postfix/smtp[341]: warning: host mx.mojomail.services[43.239.97.134]:25 replied to HELO/EHLO with my own hostname mx.mojomail.services
postfix-mailcow_1    | Sep  2 22:42:57 mx postfix/smtp[341]: AF63780154: to=<postmaster@mx.mojomail.services>, orig_to=<postmaster>, relay=mx.mojomail.services[43.239.97.134]:25, delay=0.01, delays=0.01/0/0/0, dsn=5.4.6, status=bounced (mail for mx.mojomail.services loops back to myself)
postfix-mailcow_1    | Sep  2 22:42:57 mx postfix/bounce[345]: warning: AF63780154: undeliverable postmaster notification discarded
postfix-mailcow_1    | Sep  2 22:42:57 mx postfix/smtpd[344]: disconnect from unknown[172.22.1.1] ehlo=1 quit=1 commands=2
postfix-mailcow_1    | Sep  2 22:43:28 mx postfix/postscreen[342]: CONNECT from [172.22.1.1]:52208 to [172.22.1.6]:25
postfix-mailcow_1    | Sep  2 22:43:28 mx postfix/postscreen[342]: WHITELISTED [172.22.1.1]:52208
postfix-mailcow_1    | Sep  2 22:43:28 mx postfix/smtpd[344]: connect from unknown[172.22.1.1]
postfix-mailcow_1    | Sep  2 22:43:28 mx postfix/smtp[341]: warning: host mx.mojomail.services[43.239.97.134]:25 greeted me with my own hostname mx.mojomail.services
postfix-mailcow_1    | Sep  2 22:43:28 mx postfix/smtp[341]: warning: host mx.mojomail.services[43.239.97.134]:25 replied to HELO/EHLO with my own hostname mx.mojomail.services
postfix-mailcow_1    | Sep  2 22:43:28 mx postfix/smtp[341]: CC98880154: to=<postmaster@mx.mojomail.services>, orig_to=<postmaster>, relay=mx.mojomail.services[43.239.97.134]:25, delay=0.02, delays=0.01/0/0.01/0, dsn=5.4.6, status=bounced (mail for mx.mojomail.services loops back to myself)
postfix-mailcow_1    | Sep  2 22:43:28 mx postfix/smtpd[344]: disconnect from unknown[172.22.1.1] ehlo=1 quit=1 commands=2
postfix-mailcow_1    | Sep  2 22:43:28 mx postfix/bounce[345]: warning: CC98880154: undeliverable postmaster notification discarded
postfix-mailcow_1    | Sep  2 22:44:01 mx postfix/postscreen[342]: CONNECT from [172.22.1.1]:52422 to [172.22.1.6]:25
postfix-mailcow_1    | Sep  2 22:44:01 mx postfix/postscreen[342]: WHITELISTED [172.22.1.1]:52422
postfix-mailcow_1    | Sep  2 22:44:01 mx postfix/smtpd[344]: connect from unknown[172.22.1.1]
postfix-mailcow_1    | Sep  2 22:44:01 mx postfix/smtp[341]: warning: host mx.mojomail.services[43.239.97.134]:25 greeted me with my own hostname mx.mojomail.services
postfix-mailcow_1    | Sep  2 22:44:01 mx postfix/smtp[341]: warning: host mx.mojomail.services[43.239.97.134]:25 replied to HELO/EHLO with my own hostname mx.mojomail.services
postfix-mailcow_1    | Sep  2 22:44:01 mx postfix/smtp[341]: EAFDA80154: to=<postmaster@mx.mojomail.services>, orig_to=<postmaster>, relay=mx.mojomail.services[43.239.97.134]:25, delay=0.03, delays=0.02/0/0.01/0, dsn=5.4.6, status=bounced (mail for mx.mojomail.services loops back to myself)
postfix-mailcow_1    | Sep  2 22:44:01 mx postfix/bounce[345]: warning: EAFDA80154: undeliverable postmaster notification discarded
postfix-mailcow_1    | Sep  2 22:44:01 mx postfix/smtpd[344]: disconnect from unknown[172.22.1.1] ehlo=1 quit=1 commands=2
postfix-mailcow_1    | Sep  2 22:44:40 mx postfix/postscreen[342]: CONNECT from [172.22.1.1]:52762 to [172.22.1.6]:25
postfix-mailcow_1    | Sep  2 22:44:40 mx postfix/postscreen[342]: WHITELISTED [172.22.1.1]:52762
postfix-mailcow_1    | Sep  2 22:44:40 mx postfix/smtpd[344]: connect from unknown[172.22.1.1]
postfix-mailcow_1    | Sep  2 22:44:40 mx postfix/smtp[341]: warning: host mx.mojomail.services[43.239.97.134]:25 greeted me with my own hostname mx.mojomail.services
postfix-mailcow_1    | Sep  2 22:44:40 mx postfix/smtp[341]: warning: host mx.mojomail.services[43.239.97.134]:25 replied to HELO/EHLO with my own hostname mx.mojomail.services
postfix-mailcow_1    | Sep  2 22:44:40 mx postfix/smtp[341]: 16E8880154: to=<postmaster@mx.mojomail.services>, orig_to=<postmaster>, relay=mx.mojomail.services[43.239.97.134]:25, delay=0.01, delays=0.01/0/0/0, dsn=5.4.6, status=bounced (mail for mx.mojomail.services loops back to myself)
postfix-mailcow_1    | Sep  2 22:44:40 mx postfix/smtpd[344]: disconnect from unknown[172.22.1.1] ehlo=1 quit=1 commands=2
postfix-mailcow_1    | Sep  2 22:44:40 mx postfix/bounce[345]: warning: 16E8880154: undeliverable postmaster notification discarded
postfix-mailcow_1    | Sep  2 22:45:30 mx postfix/postscreen[342]: CONNECT from [172.22.1.1]:53074 to [172.22.1.6]:25
postfix-mailcow_1    | Sep  2 22:45:30 mx postfix/postscreen[342]: WHITELISTED [172.22.1.1]:53074
postfix-mailcow_1    | Sep  2 22:45:30 mx postfix/smtpd[344]: connect from unknown[172.22.1.1]
postfix-mailcow_1    | Sep  2 22:45:30 mx postfix/smtp[341]: warning: host mx.mojomail.services[43.239.97.134]:25 greeted me with my own hostname mx.mojomail.services
postfix-mailcow_1    | Sep  2 22:45:30 mx postfix/smtp[341]: warning: host mx.mojomail.services[43.239.97.134]:25 replied to HELO/EHLO with my own hostname mx.mojomail.services
postfix-mailcow_1    | Sep  2 22:45:30 mx postfix/smtp[341]: 359CD80154: to=<postmaster@mx.mojomail.services>, orig_to=<postmaster>, relay=mx.mojomail.services[43.239.97.134]:25, delay=0.01, delays=0.01/0/0/0, dsn=5.4.6, status=bounced (mail for mx.mojomail.services loops back to myself)
postfix-mailcow_1    | Sep  2 22:45:30 mx postfix/smtpd[344]: disconnect from unknown[172.22.1.1] ehlo=1 quit=1 commands=2
postfix-mailcow_1    | Sep  2 22:45:30 mx postfix/bounce[345]: warning: 359CD80154: undeliverable postmaster notification discarded
postfix-mailcow_1    | Sep  2 22:46:08 mx postfix/postscreen[342]: CONNECT from [172.22.1.1]:53364 to [172.22.1.6]:25
postfix-mailcow_1    | Sep  2 22:46:08 mx postfix/postscreen[342]: WHITELISTED [172.22.1.1]:53364
postfix-mailcow_1    | Sep  2 22:46:08 mx postfix/smtpd[344]: connect from unknown[172.22.1.1]
postfix-mailcow_1    | Sep  2 22:46:08 mx postfix/smtp[341]: warning: host mx.mojomail.services[43.239.97.134]:25 greeted me with my own hostname mx.mojomail.services
postfix-mailcow_1    | Sep  2 22:46:08 mx postfix/smtp[341]: warning: host mx.mojomail.services[43.239.97.134]:25 replied to HELO/EHLO with my own hostname mx.mojomail.services
postfix-mailcow_1    | Sep  2 22:46:08 mx postfix/smtp[341]: 556EB80154: to=<postmaster@mx.mojomail.services>, orig_to=<postmaster>, relay=mx.mojomail.services[43.239.97.134]:25, delay=0.01, delays=0.01/0/0.01/0, dsn=5.4.6, status=bounced (mail for mx.mojomail.services loops back to myself)
postfix-mailcow_1    | Sep  2 22:46:08 mx postfix/smtpd[344]: disconnect from unknown[172.22.1.1] ehlo=1 quit=1 commands=2
postfix-mailcow_1    | Sep  2 22:46:08 mx postfix/bounce[345]: warning: 556EB80154: undeliverable postmaster notification discarded
postfix-mailcow_1    | 2018-09-02 22:46:29,146 WARN received SIGTERM indicating exit request
postfix-mailcow_1    | 2018-09-02 22:46:29,146 INFO waiting for postfix, syslog-ng to die
postfix-mailcow_1    | Sep  2 22:46:29 mx syslog-ng[10]: syslog-ng shutting down; version='3.8.1'
postfix-mailcow_1    | 2018-09-02 22:46:29,250 INFO stopped: syslog-ng (exit status 0)
postfix-mailcow_1    | 2018-09-02 22:46:29,294 INFO reaped unknown pid 328
postfix-mailcow_1    | 2018-09-02 22:46:29,295 INFO reaped unknown pid 329
postfix-mailcow_1    | 2018-09-02 22:46:29,295 INFO reaped unknown pid 330
postfix-mailcow_1    | 2018-09-02 22:46:29,295 INFO reaped unknown pid 331
postfix-mailcow_1    | 2018-09-02 22:46:29,295 INFO reaped unknown pid 333
postfix-mailcow_1    | 2018-09-02 22:46:29,295 INFO reaped unknown pid 334
postfix-mailcow_1    | 2018-09-02 22:46:29,295 INFO reaped unknown pid 335
postfix-mailcow_1    | 2018-09-02 22:46:29,295 INFO reaped unknown pid 337
postfix-mailcow_1    | 2018-09-02 22:46:29,295 INFO reaped unknown pid 338
postfix-mailcow_1    | 2018-09-02 22:46:29,296 INFO reaped unknown pid 339
postfix-mailcow_1    | 2018-09-02 22:46:29,296 INFO reaped unknown pid 340
postfix-mailcow_1    | 2018-09-02 22:46:29,296 INFO reaped unknown pid 341
postfix-mailcow_1    | 2018-09-02 22:46:29,296 INFO reaped unknown pid 342
postfix-mailcow_1    | 2018-09-02 22:46:29,296 INFO reaped unknown pid 344
postfix-mailcow_1    | 2018-09-02 22:46:29,296 INFO reaped unknown pid 345
postfix-mailcow_1    | 2018-09-02 22:46:29,296 INFO reaped unknown pid 374
postfix-mailcow_1    | 2018-09-02 22:46:29,300 INFO stopped: postfix (terminated by SIGTERM)

**Comment by patsch** [comment]
And it seems that the suggested sequence fixed it for me, thanks!

`docker rm -f $(docker ps -a -q)`

`systemctl restart docker`

`docker-compose up -d`

**Comment by m0lmk** [comment]
Seems to have fixed it for me too.

Thanks.
