### ISSUE TITLE
Feature-Request: Make recipient_delimiter configurable

### ISSUE THREAD

**Issue by dragonchaser** [mailcow/mailcow-dockerized#1146]
Postfix and dovecot use the '+' char as default recipient delimiter (for subadressing), since most websites rely on faulty regular expressions to validate the email input they do not allow this character to be used as delimiter. 

It would be a great feature to be able to customise that in the config (per domain if possible).

**Comment by mkuron** [comment]
What would you want to use instead of a plus? Dots, underscores and dashes are too common in email addresses to be usable for subaddressing and most other characters can‘t/shouldn’t be used in email addresses.

**Comment by dragonchaser** [comment]
Indeed dots and dashes were my plan. And being common is the point to "outsmart" those websites. 

My use-cases are mailservers which do not relay mail and have a limited number of users where those characters are not used or needed to divide first- and last-names.

**Comment by mkuron** [comment]
`recipient_delimiter` in the Postfix and Dovecot config would need to be changed, the rspamd settings.php would need to insert the character instead of `[+]` and the `TAG_MOO` rspamd symbol would need to be rewritten to not use the `TAGGED_RCPT` symbol (which only works with `+`) but extract the alias directly. The latter two could easily be made to pull the delimiter setting from the database, but the Postfix and Dovecot config cannot do that (and definitely not per-domain). So this isn‘t going to get fixed in Mailcow, but you can easily make the necessary changes in your local configuration.
