### ISSUE TITLE
Moving volume vmail to another partition

### ISSUE THREAD

**Issue by razvan-horobeanu** [mailcow/mailcow-dockerized#1152]
Hello,

I installed the docker file on the root partition / and I would like to move it a storage partition /home. Is it an easy way to do this? or I should perform a reinstall, but I am not aware of any configuration change to reach this state (volume vmail to sit on /home partition).

Thank you,
Razvan

**Comment by MAGICCC** [comment]
You can edit the `/etc/docker/daemon.json` and add a parameter named `graph`.
```
"graph": "/data/docker",
```

Also be sure to backup everything before starting on such things and stop the docker service/containers and copy the actual /var/lib/docker to the new location before starting docker again.

If everything is fine you should get following output of `docker info | grep 'Docker Root Dir'`:
```
#docker info | grep 'Docker Root Dir'
Docker Root Dir: /data/docker
```

**Comment by razvan-horobeanu** [comment]
I don't have such a file daemon.json in the indicated folder, only key.json. I am using Ubuntu 17.10.
I tried to create such a file with the one line mentioned above and "docker-compose up -d" is not starting again.

Any other suggestion is highly appreciated.

**Comment by andryyy** [comment]
You should at least read the Docker docs. :-)

Add...
```
{
    "graph": "/data/docker"
}
```
...to the newly created file daemon.json (in /etc/docker). "docker-compose" does not read these settings. You need to restart the Docker daemon.

You should also run `docker-compose down -v` before applying the changes. **This will delete your data**, create a copy of /var/lib/docker before going ahead.

**Comment by razvan-horobeanu** [comment]
It worked perfectly based on your additional details. I only have to stop the docker daemon before deleting data.
Thank you for your support.

**Comment by JohnGalt1717** [comment]
The problem with this solution is that it moves ALL docker volumes instead of just the mailcow ones. This needs to be setup so that you can specify where the volumes are located instead of it always just dumping them in the docker defaults which basically is never the right spot in any complex setup with large amounts of data. (and defeats the entire purpose of using docker for your configuration because it assumes that mailcow is the only thing running on docker.)

This needs to be configuration options for pathing for all of these.

**Comment by andryyy** [comment]
Read the docs.

**Comment by JohnGalt1717** [comment]
I did. And searched here extensively, and searched google on how to force it using docker compose.

Still don't have a viable solution. So if there's docs that actually address how to put these in a viable spot without changing all of docker, please link to it and show me because google agrees that it doesn't exist "mailcow change volume locations" comes up with nothing useful.
