### ISSUE TITLE
Related domains and manual certificates

### ISSUE THREAD

**Issue by razvan-horobeanu** [mailcow/mailcow-dockerized#1154]
Hello,
I tested the domain configuration with mxtoolbox.com and it reports an error regarding https - the Certificate has a name mismatch. I created the letsencrypt keys manually and copy over the existing ones, they are referring to domain.com, www.domain.com and mail.domanin.com. Only the last one is used by mailcow and it is the only one working / certifying browser.
Shall I use the others as domain aliases to obtain secured connections?
An alternative could be to try to use the embedded approach acme. Do it solve this issue?
Thank you,

**Comment by MAGICCC** [comment]
>An alternative could be to try to use the embedded approach acme. Do it solve this issue?

Depends what you actually want. Using one cert for everything - web, mail, cloud, other things. Or one for mail only (some do that because it's more 'secure' regarding finding out their mail instance...)

Anyway:
I assume you disabled the LE container using `SKIP_LETS_ENCRYPT=y` in mailcow.conf? If yes, do you copy/link the fullchain.pem as cert.pem and the privkey.pem as key.pem in /data/assets/ssl?
Does the certificate include mail.domain.com as SAN? - check it e.g. with a browser.

**Comment by razvan-horobeanu** [comment]
What I want to achieve is to access mailcow UI using https by accessing domain.com and www.domain.com and the certificates I have. It is only working using mail.domain.com that was used during mailcow install. I followed all the steps you mentioned. 
Please note that the certificates I have are referring to all three addresses. 
acme log is reporting:

  | Found  orphaned SAN horobeanu.ro www.horobeanu.ro in certificate, moving old  files to /var/lib/acme/acme/private/2018-03-10 10 34 49.bak/, keeping  key file...

**Comment by MAGICCC** [comment]
So you don't disabled acme? Please state how you want to get your certificates. At the moment you use the acme container, so you can add your other SANs in the mailcow.conf

**Comment by razvan-horobeanu** [comment]
Everything is working fine. I added the two additional SANs in the conf file separated by a comma. 
Thank you.
