### ISSUE TITLE
Problem with install !

### ISSUE THREAD

**Issue by jimmyr57000** [mailcow/mailcow-dockerized#1192]
Hello,

I have a problem with install mailcow!

after run docker-compose up -d 

http://prntscr.com/iuey8j

Tested Debian 8 and 9

Thanks you!

**Comment by MAGICCC** [comment]
After a quick research it seems that docker doesn't like LXC once again: https://github.com/moby/moby/issues/36016

**Comment by Braintelligence** [comment]
@MAGICCC Is this a temporary fix then: https://github.com/moby/moby/issues/36016#issuecomment-375160291 ?

**Comment by MAGICCC** [comment]
I don't use LXC, but he may try it

**Comment by twixi** [comment]
i have this error too:
`user@mail:/opt/mailcow-dockerized$ sudo docker-compose up -d
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
Creating network "mailcowdockerized_mailcow-network" with driver "bridge"
Creating volume "mailcowdockerized_vmail-vol-1" with default driver
Creating volume "mailcowdockerized_mysql-vol-1" with default driver
Creating volume "mailcowdockerized_redis-vol-1" with default driver
Creating volume "mailcowdockerized_rspamd-vol-1" with default driver
Creating volume "mailcowdockerized_postfix-vol-1" with default driver
Creating volume "mailcowdockerized_crypt-vol-1" with default driver
Creating volume "mailcowdockerized_rspamd-sock" with default driver
Creating mailcowdockerized_redis-mailcow_1     ... done
Creating mailcowdockerized_watchdog-mailcow_1  ... done
Creating mailcowdockerized_dovecot-mailcow_1   ... done
Creating mailcowdockerized_sogo-mailcow_1      ... done
Creating mailcowdockerized_ipv6nat_1           ... done
Creating mailcowdockerized_mysql-mailcow_1     ... done
Creating mailcowdockerized_memcached-mailcow_1 ... done
Creating mailcowdockerized_unbound-mailcow_1   ... done
Creating mailcowdockerized_clamd-mailcow_1     ... done
Creating mailcowdockerized_postfix-mailcow_1   ... done
Creating mailcowdockerized_dockerapi-mailcow_1 ... done
Creating mailcowdockerized_php-fpm-mailcow_1   ... done
Creating mailcowdockerized_nginx-mailcow_1     ... done
Creating mailcowdockerized_netfilter-mailcow_1 ... done
Creating mailcowdockerized_rspamd-mailcow_1    ...
Creating mailcowdockerized_acme-mailcow_1      ...

ERROR: for mailcowdockerized_acme-mailcow_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for mailcowdockerized_rspamd-mailcow_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for acme-mailcow  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for rspamd-mailcow  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).`

**Comment by MAGICCC** [comment]
@twixi No you don't have the same issue! And hijacking other peoples issues isn't a good idea anyway!

Well ok. You could setting `COMPOSE_HTTP_TIMEOUT` to a higher value as the errormessage states or you could tell us how much RAM/ what cpu you have. I had this issue with some low end virtual servers when I tried to 'debug it'
For now you could use `COMPOSE_HTTP_TIMEOUT=200 docker-compose up -d`  as temp solution

**Comment by twixi** [comment]
(1 core, 1GB ram, ubuntu 16.04) i have next error:
`WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
`

my instruction on blank os^
`sudo curl -sSL https://get.docker.com/ | CHANNEL=stable sh
sudo systemctl enable docker.service
sudo systemctl start docker.service

sudo curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

umask 022

cd /opt
sudo git clone https://github.com/mailcow/mailcow-dockerized
cd mailcow-dockerized
sudo ./generate_config.sh
mail.server.com
sudo nano mailcow.conf

sudo docker-compose pull
sudo docker-compose up -d`

**Comment by MAGICCC** [comment]
You may disable clamd in your mailcow.conf since you only have 1GB of RAM and clamav would take atleast 1,5GB
