### ISSUE TITLE
use without docker

### ISSUE THREAD

**Issue by jonasled2** [mailcow/mailcow-dockerized#1194]
is it possible to use mailcow without docker, I cant install it.

**Comment by Braintelligence** [comment]
Please provide full system specs and the steps you tried to install mailcow-dockerized.
Did you read the mailcow-dockerized documentation?

**Comment by stevesbrain** [comment]
@Schildkroete1 You'll probably have more success with us helping you get docker running, than to try and get it going without docker :)

**Comment by Braintelligence** [comment]
Agreed.

**Comment by jonasled2** [comment]
My problem is, that my server is running with openvz and an older kernel, so there is no Docker running. At the moment I use the old version without docker. My OS is ubuntu 16.04

**Comment by stevesbrain** [comment]
Ubuntu 16.04 supports it no worries, but openvz is a problem. Any reason that'd prevent you from moving to a xen or kvm host?

**Comment by mkuron** [comment]
Duplicate of #670. We require Docker because that makes it a lot easier to handle updates and make the installations much more reproducible. Since Docker is the de-factor standard nowadays, we see no reason to change it. Maintaining both a dockerized and a plain Mailcow would be quite a lot of work.

**Comment by jonasled2** [comment]
Yes, I have this Server until feb 2019.
  

  
  

  
  
  
  
  
>

**Comment by alexanderrieder** [comment]
@Schildkroete1 I can offer you a server for one year. What kind of Server specs do you need? You can contact me via email: info@re-host.eu

**Comment by jonasled2** [comment]
no, i dont want a new server, so i will use the old version.

**Comment by stevesbrain** [comment]
@alexanderrieder I think @Schildkroete1 also means "Thanks for the very kind offer though!", but forgot to write it ;)

**Comment by jonasled2** [comment]
yes

**Comment by andryyy** [comment]
Nice offer @alexanderrieder  👍  :-)

**Comment by snoopy72** [comment]
i am a bit confused:

We also offer service to our customers and when there are several (multiple) requests towards us for alternatives, we begin to think about it. after all, we change our "usual ways" towards the requirements of our customers (because they are our goal, not our own way).

here are several requests for using mailcow without docker - into which request queue i would like to add ourselfs.

as we have several thousands installations running on small (sometimes private) customers, there is no way to think about installing docker everywhere. so, due to your decision, we currently can and will not select mailcow for introduction to our customers as additional alternative. is this really the (or one) goal of your project ?

**Comment by mkuron** [comment]
I understand not everyone likes Docker, @snoopy72. However, it makes a complex stack like Mailcow easier to maintain because it separates services more cleanly. Maintaining a Docker and a non-Docker version side-by-side would constitute a major effort, so don't hold your breath that it will happen one day. We're quite happy with Mailcow inside Docker.

**Comment by andryyy** [comment]
Yes, it works great, is easy to maintain and is supported by the best community on this planet. Thank you guys, who support us!

**Comment by snoopy72** [comment]
> 
> 
> I understand not everyone likes Docker, @snoopy72. However, it makes a complex stack like Mailcow easier to maintain because it separates services more cleanly. Maintaining a Docker and a non-Docker version side-by-side would constitute a major effort, so don't hold your breath that it will happen one day. We're quite happy with Mailcow inside Docker.

I understand and acceppt that decision - but (and that must be allowed) i am wondering about it.

It's as a big car producer would say "we only produce left handed cars from now on - it's easier and cheaper". They would be right, no doubt. BUT: they loose the part of the useres in right handed countries. of course, they COULD drive those cars, but in real nobody would. As i said: It's your decision and that is (of course) ok.

**Comment by mkuron** [comment]
I like the left-handed car analogy. Mailcow is a small car manufacturer that doesn't have the resources to also build a right-handed car without compromising on the left-handed model.

Mailcow is a one-size-fits-all solution, but everyone knows that one size never fits everybody's expectation. So there will always be people whom we can't satisfy. However, judging by the number of our users, most people either had their expectations satisfied or adapted their expectations to be able to use Mailcow -- really, it's worth it. And Docker isn't exactly exotic anymore either -- it's become quite a standard way to distribute complex software stacks with mutual dependencies which you wouldn't want to set up on your own.
