### ISSUE TITLE
backup all for new serever

### ISSUE THREAD

**Issue by twixi** [mailcow/mailcow-dockerized#1201]
how to quick backup mailcow and transfer to new server? where run only 2 commands: `sudo curl -sSL https://get.docker.com/ | CHANNEL=stable sh
sudo systemctl enable docker.service
sudo systemctl start docker.service

sudo curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
`

**Comment by MAGICCC** [comment]
You could create a backup with [this](https://mailcow.github.io/mailcow-dockerized-docs/b_n_r_backup/), move it to the new server with e.g. rsync and [restore](https://mailcow.github.io/mailcow-dockerized-docs/b_n_r_restore/) it
Or directly move the whole volumes/data to the new server

**Comment by xetorixik** [comment]
In addition to the above reply.
Check your old servers SQL password.

Restoring Mailcow SQL on a new server results in SQL connection failed.
As [generate_config.sh generates](https://github.com/mailcow/mailcow-dockerized/blob/master/generate_config.sh#L60) a new random SQL password for mailcow.conf.
Which conflicts with the backup.

**Comment by xetorixik** [comment]
P.s.
Pay attention when restoring data from Rspam from the old to the new server.
I systematic got 502 errors by Nginx, when trying to visit the Rspam GUI after recovery.

I did not investigate further because skipping the data solves the problem.
Its maybe because I stopped using ClamAV. I don't know.

Rspam is working great out of the box so not having Rspam's learning curve is no problem for me.

**Comment by PhoenixPeca** [comment]
I believe this issue was solved already. I'm closing this now.
