### ISSUE TITLE
SOGo saving same draft indefinitely until the container is stopped

### ISSUE THREAD

**Issue by divadsn** [mailcow/mailcow-dockerized#1203]
Since yesterday my server is having constant 90-100% CPU usage with netdata spamming my Slack with critical notifications about the usage. Checking with `htop` I noticed the following:
![grafik](https://user-images.githubusercontent.com/28547847/37890389-c0eeaa60-30d0-11e8-87ba-de4b3e268fff.png)

`imap` and `sogod` are constantly demanding high CPU usage. While `sogod` is behind a NGINX proxy which should filter out bad connections, `imap` spams the following error "cannot allocate memory" into the log of dovecot-mailcow:
![grafik](https://user-images.githubusercontent.com/28547847/37890368-b05c2f56-30d0-11e8-973f-65f21f6994aa.png)

My server has 4 GB out of 8 GB free available and more than 50% disk space, so what is going on?
Or could be a full swap space be the issue?

**Comment by andryyy** [comment]
That's strange. Do you have many IMAP connections?

**Comment by divadsn** [comment]
@andryyy no, only 2 devices use a mail client as far as I can remember, the others use SOGo and Roundcube for Webmail.

**Comment by divadsn** [comment]
Oh, somehow I have over 30.000 drafts unread, strange.
SOGo crashes and Roundcube isn't able to show them.

**Comment by divadsn** [comment]
![grafik](https://user-images.githubusercontent.com/28547847/38022934-326fee90-3281-11e8-8d2a-17bc29f4de4f.png)
Looks like SOGo has derped something and was saving a new draft until I killed off the container, well...

Update: after restart the drafts continue to spam, what the hell

**Comment by divadsn** [comment]
Running update.sh again and recreating the containers solved the issue somehow, hope it won't repeat ^^

**Comment by bitmario** [comment]
@divadsn I'm facing the same issue since a few days ago, drafts keep being created which overloads my server (which used to sit almost idle). I tried the update but it didn't fix it. Could you please describe the steps you took in more detail?

**Comment by BjarneRest** [comment]
My installation does it too! Please reopen issue.

I had to delete the whole mailbox (including the vmail folder) to fix the problem. One update later, the Draft folder was filled up again...

I am using the Android Gmail client via Exchange on two devices and the Sogo webmailer

**Comment by andryyy** [comment]
Sounds interesting. You won't need to delete the whole vmail folder anyway.
I will try to reproduce it and open an issue @ SOGo. I would really appreciate any help collecting information.

**Comment by bitmario** [comment]
@andryyy I'm happy to help collecting info, please let me know what you need. I'll provide some basic stuff below.

Just like divadsn, high CPU usage is caused by sogod and imap. I also used to have memory errors, but ever since I increased the VM's memory they went away (it was 1.5GB). High CPU usage still occurs even after running the update script, but it is intermittent and apparently random. None of this happened until early April.
I also get random copies of drafts, which may or may not be related to this. Right now I have 152562 copies of (part of) an e-mail I sent on Monday in my account's drafts folder...

The only obvious issues in the logs available in the mailcow panel are a few messages like this:
`[3218]: \|SOGo\| terminating app, vMem size limit (384 MB) has been reached (currently 1260 MB)`
and 
`4/11/2018, 12:05:10 AM	notice	[9]: [WARN] <0x0x559a0df905b0[WOWatchDogChild]> pid 3107 has been hanging in the same request for 2 minutes`

[More of this log](https://gist.github.com/bitmario/5523ba51486a264c61be2fae3330f6cd)

My environment:
- Server: 1 core, 2.75GB RAM, 1 GB swap, Ubuntu 16.04
- 3 Android clients using Gmail to connect to about 4 accounts each over ActiveSync/IMAP
- 3 desktops using Outlook 2016 with 2-5 accounts over ActiveSync 
- Sporadic use of the SoGo webmail (probably never more than one person at a time, however some have other accounts configured via SoGo IMAP)

**Comment by divadsn** [comment]
@bitmario in my case I found the issue, it was my phone which was saving drafts indefinitely in the Gmail app, I think it seems like something is either wrong with the Google Exchange plugin in Gmail or with the SOGo implementation.

After switching to Outlook for Android every draft seems to save fine, no issues now.

**Comment by divadsn** [comment]
Maybe I could come up with a workaround for now which would not show up the Exchange setup on Gmail app and use IMAP instead.

**Comment by bitmario** [comment]
@divadsn Thanks for the feedback. My testing confirms that the issue is indeed caused by creating a draft in the Gmail app. Creating a draft from the SOGo web interface does not cause this.

I got rid of all the drafts by deleting them in `/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/domain.com/account/.Drafts/cur` (I had to use `find cur/ -name '*' | xargs rm` because there were so many files). I then had to delete some accounts on a couple of phones because they still kept trying to create more copies of the same drafts. Did a final cleanup and problem solved! Back to ~5% CPU.

I alerted the users to avoid using Gmail and will be trying other email apps to see if that fixes it for good.

@andryyy To reproduce this issue, just create a draft using the latest Gmail android app and check that user's drafts folders after a couple of minutes... You'll see copies of your message popping up.
Not sure if this is a SOGo issue or Gmail issue, but this doesn't seem to happen when using Gmail with a real Exchange server.

**Comment by bitmario** [comment]
I tested the Outlook app and it does not have this issue, but the drafts are not saved on the server so it's not surprising. Seems like it is a reasonable alternative, the only drawback is we lose the integration with the Google calendar.

**Comment by divadsn** [comment]
@bitmario you can still get the integration by allowing Outlook to view your calendar.

**Comment by BjarneRest** [comment]
@bitmario @divadsn I need the contacts and calendar integration. The calendar view in Outlook is okay so far, but I'm not happy with the contacts on mobile outlook.
Maybe I can get the CardDav and CalDav URSs from SOGo and sync them via OpenSync (Free App in PlaySore, worked with my Nextcloud so far)

**Comment by mritzmann** [comment]
I had the same problem today.

Client: Mozilla Thunderbird / IMAP

**Comment by andryyy** [comment]
Seems like it doesn't care about the default vszlimit at all. I set explicit limits for these services.

**Comment by axd** [comment]
My workaround was to delete all the draft emails, delete my account from android's accounts and add it again, this solves the problem, just keep in mind not save draft in Gmail app until a solution is released.

**Comment by andryyy** [comment]
It should be fixed, I hope. If not, it is SOGo to spam the drafts folder. I doubt it, as @mritzmann run into this with Thunderbird.

**Comment by evilstiefel** [comment]
Must be a Sogo problem, hit this the past week. Only noticed because I had very high load in my dovecot container with the imap process. Turned out one draft message had been copied a good 400000 times. ActiveSync added ~1-3 copies per second. I didn't debug it properly with the extended debugging messages for AS, so I can't really say what circumstances with the particular draft led to the issue (only that I, too, initially created it with Thunderbird).

"Fixed" it by clearing the drafts folder of all messages.

**Comment by rafix1989** [comment]
Hi evilstiefel

Unfortunately i have the same issue, my draft folder has over 600000 messages. 
What command did you use to clear draft folder ??
 
> "Fixed" it by clearing the drafts folder of all messages.

**Comment by andryyy** [comment]
Gmail app is causing this. Delete from the volume by hand. :) In /var/lib/docker/volumes/mailcowbla_vmail-vol-1bla
