### ISSUE TITLE
	connect to ******:25: Connection timed out

### ISSUE THREAD

**Issue by element465** [mailcow/mailcow-dockerized#1214]
Incoming email is fine, but outgoing seems to be blocking outgoing email. I am using Vultr (with port 25 unblocked) and the Docker install using Debian 9.

My port 25 is open according to telnet: http://prntscr.com/iybq7v

But when I send, I get this error.

> 3/30/2018, 2:14:17 PM | info | connect to alt2.gmail-smtp-in.l.google.com[209.85.147.27]:25: Connection timed out
-- | -- | --
3/30/2018, 2:13:47 PM | info | connect to alt1.gmail-smtp-in.l.google.com[2607:f8b0:4003:c09::1b]:25: Connection timed out
3/30/2018, 2:13:17 PM | info | connect to alt1.gmail-smtp-in.l.google.com[64.233.179.26]:25: Connection timed out
3/30/2018, 2:12:38 PM | info | connect to gmail-smtp-in.l.google.com[2404:6800:4008:c00::1a]:25: Connection timed out
3/30/2018, 2:12:03 PM | info | connect to gmail-smtp-in.l.google.com[108.177.97.26]:25: Connection timed out
3/30/2018, 2:11:32 PM | info | 571471F9EB: to=<luke@********>, relay=dovecot[fd4d:6169:6c63:6f77::f]:24, delay=0.71, delays=0.53/0.04/0.06/0.08, dsn=2.0.0, status=sent (250 2.0.0 <luke@********> qOz1OOOqvVo5AAAAf5rrBg Saved)
3/30/2018, 2:11:31 PM | info | 571471F9EB: from=<luke@********>, size=1093, nrcpt=2 (queue active)
3/30/2018, 2:11:31 PM | info | disconnect from mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248] ehlo=1 auth=1 mail=1 rcpt=2 data=1 quit=1 commands=7
3/30/2018, 2:11:31 PM | info | 571471F9EB: message-id=<29-5abdab00-1-7d7b1100@5741232>
3/30/2018, 2:11:31 PM | info | 571471F9EB: client=mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248], sasl_method=PLAIN, sasl_username=luke@********
3/30/2018, 2:11:31 PM | info | connect from mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248]

Any idea on whether my outbound firewalls are blocking? I've been here for hours and stumped! And how would I check this? Could Docker be getting in the way?

**Comment by mkuron** [comment]
Most likely your hosting company has a firewall that blocks port 25 and you need to ask them to unblock it. Your telnet check does not mean anything because it only tested whether your server can connect to itself. You need to check whether it can connect to the outside world, e.g. like this: `telnet gmail-smtp-in.l.google.com 25`.

**Comment by xetorixik** [comment]
@element465 As you are using Vultr.
Vultr's  > outbound traffic to the SMTP port [may be blocked for new accounts](https://www.vultr.com/faq/).

> If you encounter this restriction, [contact our support team from the customer portal](https://www.vultr.com/docs/what-ports-are-blocked).

You should send them a support ticket.

Secondly. 
Register your domain with [Google Postmaster Tools](https://gmail.com/postmaster/).
Mail is all about IP and domain reputation. 

When something happens within the ASN network. (If another user starts to f**** in the network.) 
You can also be blocked.

Thirdly. I almost forget about it. Hence this edit.

>  I've been here for hours and stumped! 

In order to prevent your useless, hours searching for an unknown problem.
What I always do in the case of a similar problem. 
Is starting another VPS (other provider, maybe test domain) and simulate the problem.

Many providers support pay per hour. So that's easy.
This prevents annoyance. And quickly provides a solution.

For example. 
You often see that you have the IP address on a blockade list.
Whether reputation has suffered damage because someone is rummaging from the same network.
