### ISSUE TITLE
Please use OSCP Stapling for the acme Client

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1218]
Hey, I noticed that the build-in certbot function works just great!
But could you please add OSCP Stapling, so I dont have to use my own certificates? It just be pretty easy, because it exists an option (--must-staple).

**Comment by andryyy** [comment]
I don’t really want to enable it. You can change acme-mailcow and other configuration files for your setup. 

I think at least Postfix still has some problems handling it properly. 

I also don’t like the idea to enable fancy options because they exist. :-) We should always make sure what problems may occur and wether or not it actually improves the setup.

**Comment by ghost** [comment]
Okay, thank you for the quick reply. :)
Keep up the good work, mailcow is really, really nice

**Comment by mkuron** [comment]
Dovecot said they might implement it in the future: https://www.dovecot.org/list/dovecot/2016-March/103403.html . Postfix said that they will never implement it: https://marc.info/?l=postfix-users&m=151119229905817 . So Mailcow will never be able to implement OCSP stapling.

As Let's Encrypt only issues 90-day certificates (and renews after 60), the need for stapling is not that big. In essence, stapling reduces the validity period of a compromised certificate to a few days. On average, a Let's Encrypt certificate will have 60 days of validity left at the time it is compromised, so you only shorten the validity of the compromised certificate by a factor of 20 through stapling. Compare that to long-lived certificates (2 years), where stapling gives you a factor of 250.
