### ISSUE TITLE
iptables and docker

### ISSUE THREAD

**Issue by jm3west** [mailcow/mailcow-dockerized#122]
Hi everybody,

across mailcow-dockerized is it the first contact with docker.

I use an iptables for my vServer
I do open the ports for apache-proxy and mailcow.
But when I activate the iptables then is the communication under port 8080, 8443 and 4190 disturbed

regards
jm3west

**Comment by skupfer** [comment]
Is it still reachable or is a container down maybe? What does the nginx logs says?

Had a similar problem after adding new iptables rules (flushing etc pp). Try restarting the docker service/daemon after playing with iptables rules.

EDIT:

Due to the docker restart it will recreate the missing iptables rules on the host itself. Unfortunately this is the only way to fix this from what I have found googling for a solution.
I guess you could write a script to automatically re-start the docker daemon after an iptables-restore or so...

**Comment by tehXor** [comment]
docker itself makes heavy use of iptables on the docker host to enable its container communication. So I'm guessing your rules interfere with the docker rules. Therefore you will need to understand what docker does and how you can write your rules more specific so that they don't interfere with the docker rules. Some starting point could be https://docs.docker.com/engine/userguide/networking/default_network/container-communication/ or simply googleing a bit about iptables and docker.

You could also post your exact rules which currently don't work. Maybe people can help you then.

**Comment by broedli** [comment]
@jm3west is your problem resolved?

**Comment by lenovouser** [comment]
@jm3west this has been a known issue for a long time, sadly docker hasn't fixed it yet 😞 

https://github.com/moby/moby/issues/29312
