### ISSUE TITLE
Sieve filter with bcc as forwarding criteria

### ISSUE THREAD

**Issue by imp1sh** [mailcow/mailcow-dockerized#1244]
Hi,

I'm on commit bc3daa836ffa4bb848a34aacc486a7bb3cd1fbf4 on a CentOS 7.4 system.
A customer has a sieve rule that looks like this:

if allof (address :is ["to", "cc"] "desination@domain.com") {
    redirect "redirect@domain.com";
}

He would want it to be like this:

if allof (address :is ["to", "cc", "bcc"] "desination@domain.com") {
    redirect "redirect@domain.com";
}

Is this something than can be done via the user interface or maybe manually with a workaround? In the past I tried to create sieve rules manually by creating the folders / files but that didn't work.

Thank you.

**Comment by mkuron** [comment]
Received messages never contain a Bcc header, otherwise you could see all other recipients, which would defeat the point of Bcc.

I assume mailto:desination@domain.com is one of your customer's own email addresses and domain.com is hosted on your Mailcow server? If (and only if) that is the case, you can filter based on the envelope recipient.

**Comment by imp1sh** [comment]
Thank you.
