### ISSUE TITLE
How to change /SOGo url to other name?

### ISSUE THREAD

**Issue by twixi** [mailcow/mailcow-dockerized#1252]
I want to change mail.site.com/**SOGo** path to example mail.site.com/**OtherName**
How to do it?

**Comment by mkuron** [comment]
You would need to replace several occurences of `SOGo` in https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/nginx/site.conf . You can also do this on a reverse proxy, which is preferable because it doesn‘t require modifying Mailcow and thus prevents conflicts during upgrades.

Related to #393, which contains more possible solutions.
