### ISSUE TITLE
Generated cert contains all domains (info leak) (related #1308)

### ISSUE THREAD

**Issue by alexandernst** [mailcow/mailcow-dockerized#1309]
The certificate chain of trusted domains contains all the domains, which is pretty bad as it's an information leak that shouldn't happen.

To reproduce the bug just go to https://www.checktls.com/TestReceiver and type any domain hosted by mailcow. You'll see, in the result, a list of all domains that are hosted by that mailcow server.

**Comment by andryyy** [comment]
Not related to the previous issue. 

You’ll need to handle autodiscover and autoconfig with an external reverse proxy. Create those names there and have an acme client create a certificate for each name.

If you are doing hosting services, this should not be a problem at all - you probably already use reverse proxies for a bunch of services. We could create a small and general document about how to do it. But the most important part - setting up a reverse proxy - is already documented. :-)

Closing it as a duplicate of an issue I cannot find right now due to laying on my bed, writing from an iPhone.

**Comment by alexandernst** [comment]
Why can't this be handled by Mailcow?
I mean, Mailcow (dockerized) already has somewhere around 4268 containers bundled. Why can't one of those (or maybe even a new one) handle that? Isn't that the point of Mailcow: make sysadmin's lifes easier?

**Comment by mkuron** [comment]
Duplicate of #528 and #461. Mailcow‘s certificate handling is only meant to deal with the most common case. It is not intended for big multi-domain hosting setups — for example, it cannot handle more than 49 domains. Besides, this information leak is not critical at all as one can often obtain a list of all domains a mailserver is responsible for through DNS crawling services such as http://bgp.he.net.

**Comment by andryyy** [comment]
One app, one container. I think the previous mailcow installed more applications. Don’t confuse it with a virtual machine. 

Using a reverse proxy for this is not hard at all.
