### ISSUE TITLE
Linode Guide

### ISSUE THREAD

**Issue by ylluminate** [mailcow/mailcow-dockerized#1319]
A Linode guide for Mailcow could be worth the effort for a dev here. They pay up to $300 for a guide and Mail-in-A-Box has been up for a while. See: https://linode.com/docs/contribute/

**Comment by stevesbrain** [comment]
I don't know if it'd really qualify for a Linode guide, given it's basically just a `git clone` followed by a config file, and `docker-compose up -d` - normally they have to be a little more in-depth than that right? Otherwise basically every docker image could have a tutorial written almost identically :)

**Comment by mitchellurgero** [comment]
Yea but Mailinabox is even simpler than that and installs in one command.

Honestly mailcow has a large (compared to MIAB) wiki/docs section. Could be worth checking into at the very least I think :)

**Comment by Dragnucs** [comment]
@stevesbrain Details of DNS settings are also to be detailled and explained. They are crucial for a good mail server and very hard to get right for new commers. Think DKIM and other TXT and PTR records.

**Comment by stevesbrain** [comment]
@Dragnucs That's true, however, I guess what I mean is - Linode docs are normally written because other docs are either incomplete, or not specific to the Linode platform. Mailcow docs are quite complete + practically universal. Obviously, go for it if you want to! I'm just saying I don't *personally* see the need - but hey, if it nets you $300, then all the better :)
