### ISSUE TITLE
Migration from mailcow -> mailcow-dockerized

### ISSUE THREAD

**Issue by chrislp** [mailcow/mailcow-dockerized#132]
Is there a recommended way to move from mailcow to mailcow-dockerized?

I take from this note that you will not focus on developing mailcow (without dockerized) any further. Is that right?
![image](https://cloud.githubusercontent.com/assets/186817/24093373/cb749bda-0d53-11e7-8f18-b72f42e202b6.png)

**Comment by PhoenixPeca** [comment]
**THIS QUESTION IS A DUPLICATE OF** #112 
As of the moment there is no official way of properly migrating from the standard mailcow to the dockerized mailcow, but that does not mean it can't be done: "REFER TO #112 "


BTW, the standard mailcow will be updated soon. so stay tuned!!! 😄But for now, Andre's priority will be the dockerized version.

**Comment by chrislp** [comment]
@PhoenixPeca sorry ... didn't look in the closed issues. 🤦‍♂️
Thanks for your answer!

**Comment by wucke13** [comment]
I did the upgrade from 0.14 a few days ago. Here is what I did:

+ Backup.
+ Make a copy of your actual mailboxes and domains setup, e.g. save the page or take a screenshot.
+ Install docker and docker-compose.
+ Stop your actual Mailcow services, since they might block ports which are checked by docker while deploying Mailcow dockerized. To do so run:
`systemctl status fuglu.service spamassassin.service dovecot.service postfix.service`
+ Note: From now on your Mailserver is not available. Do this preferable during night or some time where no users become upset easy.
+ Follow the mailcow-dockerized installation. If you have another Webserver running, change the HTTP and HTTPS Port to some unused port and the bind adress to `127.0.0.1`, . Also add/modify a vhost file which rproxys to that ports you choose, so that Mailcow WebUI is accessible.
+ After the installation finishes, start copying all mails to the docker volume. To do so, I did the following: `rsync -avz /var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/`. Remember the / as suffix, otherwise rsync might do weird things.
+ While the copying is on going, recreate your mailboxes and domains setup. I used random password to recreate the user. Don't forget to tell them!
+ Some Mailbox folders did not show up in SOGo. This seems to be caching issue by dovecot. Delete all cache files recursively inside `/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/`. To do so, you could use `find . -name 'dovecot.index*'` to find these files recursively. Evaluate the output, if no wrong files are mentioned, append `-delete` to delete these files. Else adjust the pattern and retry.

This pretty much was it. You should probably restart SOGo. Don't worry if the number of messages in the mailboxes are wrong or equal zero, and don't worry if both SOGo and Mailcow show up 0MB used space. This adjusts itself after a few hours on the run.

Maybe it is possible to migrate with copying the users from the db, but the hash used might must be updated, since the format changed?

**Comment by andryyy** [comment]
Wow, thank you!

**Comment by wucke13** [comment]
Would it be helpful to add this to the wiki? Did the `mailbox` table change structural from mailcow to mailcow-cockerized? Or is the change from the hash used to hash the pw the only change?

**Comment by SISheogorath** [comment]
If you didn't import the sogo database the migration is not lossless. All calendar and contacts are missing without the database migration.

**Comment by wucke13** [comment]
That's true. However, I managed to get the contacts out of the roundcube db in VCF per user, so that they could re import them to their SOGo. The SQL string was:
`SELECT c.vcard FROM contacts c, users u WHERE c.user_id=u.user_id AND u.username='someone@mail.com'`

**Comment by broedli** [comment]
Please check the [guide](https://mailcow.github.io/mailcow-dockerized-docs/) in the documentation and try to improve it if necessary. Every PR is welcome!

I'm closing this issue for now. Please feel free to open a new Issue in the repository of our documentation if needed.

**Comment by Adorfer** [comment]
it's a pitty that there is no real working migration procedure (e.g. keeping the existings user passwords, keeping their Sogo-callendar/contacts)

in other words: This means i will be stuck on the "non-dockerized" version forever, since there is no chance to explain to the users such a loss of data.
