### ISSUE TITLE
update.sh: fatal: Refusing to fetch into current branch refs/heads/master of non-bare repository

### ISSUE THREAD

**Issue by bully1980** [mailcow/mailcow-dockerized#1321]
Hi,

I updated with update.sh today and now I get the following error:
fatal: Refusing to fetch into current branch refs/heads/master of non-bare repository
Maybe something in my git is broken. Is it possible to start fresh in a new folder?
Which files do I have to copy to the new folder and get updates in future?

best regards

JB

**Comment by mitchellurgero** [comment]
AFAIK this is just a git error and can be ignored, I looked at that as well. One of the devs would have to confirm though

**Comment by mitchellurgero** [comment]
UPDATE: It looks like git will ignore itself because of this. I had to run the following in order to update to latest commit. (Note it still throws the error)

`git fetch --update-head-ok`
`git pull`

Confirm you are still on master branch:
`git branch` (Should output `* master`) If it doesn't run `git checkout master && git pull`

Once the update is done, if you just updated to commit `05e026d` you will need to run `./update.sh`. This will STILL complain about the error BUT since you are on the latest commit it will rebuild the containers and restart them with latest code.

Once that is done, you will be prompted to delete `netfilter 1.11` tagged container. This is perfectly safe to do (and you should do it). Once that tagged container is deleted docker will switch to the new 1.12 tagged netfilter container and start it.

That will get you updated until this error can be fixed.

**Comment by andryyy** [comment]
Thanks for the update, Mitchell. :-)

**Comment by mitchellurgero** [comment]
Just happy to help! I love this project and want to contribute more! <3

**Comment by bully1980** [comment]
Thanks @mitchellurgero 
Works like a charm. I am system and network administrator, but I am not very familiar with git and I don't want to break anything :)

**Comment by mitchellurgero** [comment]
No problem! git is confusing at first but once you get the hang of it, it is very easy and quick to manage a lot of code changes. :) Versioning for the win!

**Comment by mitchellurgero** [comment]
Looks like the latest update.sh fixes this, run the above steps again and the error should disappear.
