### ISSUE TITLE
Custom recipient_delimiter

### ISSUE THREAD

**Issue by Dehalion** [mailcow/mailcow-dockerized#1352]
Hi!

What do I have to change in the configuration to use a recipient_delimiter other than `+`?

Delivery into subfolders works with the default `+` delimiter.
If I change it to `_` in `dovecot.conf` and `postfix/main.cf` mails are delivered into the inbox, not into subfolders.

Which configuration am I missing or where do I have to change something?

**Comment by mkuron** [comment]
Duplicate of #1146

**Comment by Dehalion** [comment]
I don't think this one is a duplicate, it is just related.

#1146 is marked as wontfix because it is not possible to set different recipient_delimiter characters for different domains (because of the way postfix and dovecot works).

I just want to set one delimiter (`_`) for the whole mailcow instance, just a different one.

I even don't need a global setting in `mailcow.conf` or something like that. I would be greatful if you can point me to the locations I have to change to make it work.

I also found the location in rspamd `settings.php` you mentioned in #1146 but I need some more hints how to
> the TAG_MOO rspamd symbol would need to be rewritten to not use the TAGGED_RCPT symbol (which only works with +) but extract the alias directly

**Comment by mkuron** [comment]
It‘s also wontfix because the dovecot and postfix configuration needs to manually be edited. We cannot make the delimiter editable through the web UI or via mailcow.conf.

For TAG_MOO, this is the place: https://github.com/mailcow/mailcow-dockerized/blob/4c31/data/conf/rspamd/lua/rspamd.local.lua#L17. For some inspiration on how to get the recipient, see https://github.com/vstakhov/rspamd/blob/c949b41dd7f6dd8e4312cdf640a791c2f02818a9/rules/misc.lua#L440-L468

**Comment by Dehalion** [comment]
thanks for the links, I'll look into it.
