### ISSUE TITLE
autoconfig with selected ports only

### ISSUE THREAD

**Issue by jol64** [mailcow/mailcow-dockerized#1382]
this is partly a request and partly a tip for others..
I am only exposing ports 25, 143, 587 to the public. However Thunderbird apparently prefers direct tls over starttls, and as I don´t expect all my users to know the correct combination, I was looking how to force autoconfig to tell the right settings..
I came up with the following in /opt/mailcow-dockerized/data/web/inc/vars.local.inc.php 
````
<?php
$autodiscover_config = array(
  // Enable the autodiscover service for Outlook desktop clients
  'useEASforOutlook' => 'yes',
  // General autodiscover service type: "activesync" or "imap"
  'autodiscoverType' => 'activesync',
  // Please don't use STARTTLS-enabled service ports here.
  // The autodiscover service will always point to SMTPS and IMAPS (TLS-wrapped services).
  'imap' => array(
    'server' => $mailcow_hostname,
    'tlsport' => getenv('IMAP_PORT'),
  ),
  'smtp' => array(
    'server' => $mailcow_hostname,
    'tlsport' => getenv('SUBMISSION_PORT'),
  ),
  'activesync' => array(
    'url' => 'https://'.$mailcow_hostname.'/Microsoft-Server-ActiveSync'
  ),
  'caldav' => array(
    'url' => 'https://'.$mailcow_hostname
  ),
  'carddav' => array(
    'url' => 'https://'.$mailcow_hostname
  )
);
````
However users are not supposed to pick pop in Thunderbird as then the connection will fail. Is there a means to disable pop entirely?
And maybe there is a better option to specify which ports are actually open?
The same question may be relevant for autodiscovery, only that most of my clients use EAS anyway.
Thanks, Joachim

**Comment by PhoenixPeca** [comment]
Hi, 
Please read the documentation about this: https://mailcow.github.io/mailcow-dockerized-docs/prerequesite-dns/#the-advanced-dns-configuration

> SRV records specify the server(s) for a specific protocol on your domain. If you want to explicitly announce a service as not provided, give "." as the target address (instead of "mail.example.org."). Please refer to RFC 2782.
_______________________________________

Basically, to disable POP all you need to do is set this in your DNS:
````
_pop3._tcp          IN SRV     0 1 110   .
_pop3s._tcp         IN SRV     0 1 995   .
````

**Comment by jol64** [comment]
I wanted to try that, but unfortunately I cannot, Cloudflare does not allow me to set a . record.
Also: does autoconfig really check DNS? Sounds strange to me, looking something up in a directory when it is local configuration.
Thanks, Joachim

**Comment by PhoenixPeca** [comment]
> does autoconfig really check DNS?

Yes.
https://github.com/mailcow/mailcow-dockerized/blob/a8d9b4359e78e80dc4689a8a38c0ef01742a5682/data/web/autoconfig.php#L51

_________________________


> I wanted to try that, but unfortunately I cannot, Cloudflare does not allow me to set a . record.

Seriously? you should really tell them about that. Anyway, If that's the case, you can manually remove the POP3 code block in `autoconfig.php`. The code block is line 50-71.
https://github.com/mailcow/mailcow-dockerized/blob/a8d9b4359e78e80dc4689a8a38c0ef01742a5682/data/web/autoconfig.php#L50-L71

Haven't tested it tho. Lemme know how it turned out. :-)

**Comment by jol64** [comment]
> Seriously? you should really tell them about that. 

already created a support request on that topic :) But don´t expect tham to answer today :(
>  you can manually remove the POP3 code block..

Any idea how to do this in /opt/mailcow-dockerized/data/web/inc/vars.local.inc.php - after all that is supposed to avoid modifications, correct?

**Comment by PhoenixPeca** [comment]
>...after all that is supposed to avoid modifications, correct?

Yes, you're right. But, as of this moment, there's no option that can be set in `vars.local.inc.php` to make it possible and it is unlikely that we will add that too because we can already do it via DNS. **But with your case, we might consider it.** After all, its not really mailcow's incapability but of cloudflare's.
