### ISSUE TITLE
merger #1383 , issues with dovecot-autoexpunge.php

### ISSUE THREAD

**Issue by extremeshok** [mailcow/mailcow-dockerized#1389]
Why was the php script allowed ? . Ie. I am completely against the current implementation

You are using shell_exec to run a php script when u could of done the database called directly in php and not via system shell, aka http://php.net/manual/en/mysql.examples-basic.php

The entire if(!empty($mailbox) && $domainAE===1) { ... } else { part could of been replaced with a  simple where clause in the mysql statement to do the filtering.

The entire php script can be written in bash, along with the redis logging. which would mean no php-redis and php-cli is required on the docevot image

**Comment by PhoenixPeca** [comment]
@extremeshok the php script works fine. I have rebuilt all containers from the ground-up in the dev branch to verify it. The php script is a complete translation of a bash script from that of [dovecot's official expire plugin documentation.](https://wiki2.dovecot.org/Plugins/Expire#Vpopmail_.28.2B-MySQL.29). **I am kind of rusty with bash scripting so I decided to switch to php mainly because I don't wan't to introduce new bugs by using a language that I am no longer familiar with**. After all, the implementation and algorithm is identical. Anyway, if there is something you can help me with by returning back to bash, I would be really happy.. 😄 

> Why was the php script allowed?

why not? PHP was not only designed to work on websites but also for cli. That's what PHP-CLI was built for. **But that's not my point, I did it because I am kind of rusty with bash; I don't want to use something that I am not familiar with and introduce more problems than what I should be fixing.** Aside from the fact that what I am doing is against all norms, I do not see anything with PHP-CLI that would make it any less better of a scripting language for this.

> You are using shell_exec to run a php script when u could of done the database called directly in php...

Yes, my bad. I'm working on this now. I translated it too literally from the original bash script. I spent all the time testing on this rather than focusing on the fundamentals. Anyway, I don't think this is really a problem because if I am using bash right now, I would also be doing the same way that I did with PHP.

### With all these, I admit there's more to be improved from the code. But, for now, I'm sticking to it as I rewrite everything to bash.

**Comment by extremeshok** [comment]
Well besides introducing all the php dependencies and the relevant security issues and increasing the size of the docker container, increase in memory usage, increase in cpu load (php and its modules requires cpu and memory).... yes it works..

The same argument can then be used to justify having mono bundled to run a small script and why not throw in some java aswell.

I will code it to shell (bash) and do a pr. My specialty is bash

@PhoenixPeca thanks for the enhancement (Auto Delete Emails in Junk/Trash After 30 Days)

**Comment by PhoenixPeca** [comment]
> Well besides introducing all the php dependencies and the relevant security issues and increasing the size of the docker container, increase in memory usage, increase in cpu load (php and its modules requires cpu and memory).... yes it works..

AFAIAC, the added dependencies are not as heavy as it looks (considering that the script is used to purge old emails to get back some space, I think any production environment can spare a few MBs for these) and with the current implementation. I don't also see any relevant security issues (it's not like users can interact directly with the script and perform code injection or something). And as far as the CPU load and memory is concerned, the script itself is not active all the time to be considered a problem (it is executed daily via cronjob and I might even consider executing it every other day or weekly if that's really concerning you).

> The same argument can then be used to justify having mono bundled to run a small script and why not throw in some java aswell.

That statement is out of the context as not all programming languages are the same. It's just a matter of perspective in the community standards. Besides, it is not right to compare Java and PHP as java is a complied language whereas PHP is not.

> If I have time this afternoon, I will code it to shell (bash) and do a pr. My specialty is bash.

That would be great. I am looking forward on testing that in my dev machine.

**Comment by PhoenixPeca** [comment]
Reverted. now closing.
