### ISSUE TITLE
Question: Move Mailcow from Server1 to Server2

### ISSUE THREAD

**Issue by rebek86** [mailcow/mailcow-dockerized#140]
Moin,

I want to move my cow to a larger server. This is how I proceeded:

1. /var/lib/docker/volumes/ copied to server2
2. on Server2, git clone mailcow...
3. copied mailcow.conf from server1 to server2
4. docker-compose pull
5. docker-compose up -d

Now I get the following error message:
`dovecot-mailcow_1    | 2017-03-22 07:30:49 auth-worker(73): Error: mysql(mysql): Connect failed to database (mail123cow): Access denied for user 'mail123cow'@'172.22.1.6' (using password: YES) - waiting for 25 seconds before`

Is this the right way to change the server or should I go another way?

Many Thanks :-)

**Comment by marrco** [comment]
i'd update the working server to the latest mc-d version, stop it, then [backup database](https://andryyy.github.io/mailcow-dockerized/u_and_e/#backup_1) and [maildir](maildir) 

Setup a clean mc-d on the new server, rsync mailcow-dockerized directory (if memory helps you have to update part of config file with new database login) then you just [restore database](https://andryyy.github.io/mailcow-dockerized/u_and_e/#restore_1)  and [maildir](https://andryyy.github.io/mailcow-dockerized/u_and_e/#restore)

**Comment by wucke13** [comment]
Are you shure that you did copy `mailcow.conf` and that you did not run `generate_config.sh` afterwards?

When you execute the `generate_config.sh`, it generates random password for the  DB access and stores them in `mailcow.conf`. So the new credentials are then put into the config of all docker containers which have access to the db, however the database itself is not changed. You see what happend here? All containers from now on have wrong passwords stored for db access. To solve this, copy the `mailcow.conf` from the working server to the new server, and then redeploy via `docker-compose pull && docker-compose up -d`. This should store the old, valid credentials for db access in all the containers, so that the database is accessible again for all containers.

**Interesting note:** if you lost your old mailcow.conf, you can spawn a shell in the database container, install an lightweight editor like nano via `apt-get install nano` and then edit the `/etc/mysql/my.cnf`. Under `[mysqld]` add `skip-grant-tables`. Restart the container, get shell access again and use `mysql -u root` to gain access to the db. Now you can easily update the password to the new passwords according to the new ones from mailcow.conf, just by running `update user set password=PASSWORD('<password>') where User='<user>';`. Also change the passwords for the debian root user according to `/etc/mysql/debian.cnf`. **Don't forget to remove `skip-grant-tables` from `my.cnf` afterwards!**

**Comment by rebek86** [comment]
Thanks :-)
