### ISSUE TITLE
ActiveSync - iOS - SOGo

### ISSUE THREAD

**Issue by jm3west** [mailcow/mailcow-dockerized#1414]
Hi everybody,

I try use ActiveSync ....
....
I create an exchange account on iPhone.
I fill in my email-address
I fill in my password

bum connect. yeah

iOS standard mail app > push-sync, yeah
iOS standard calendar app ...
From iOS to mailcow/SOGo > push-sync, yeah
From mailcow/SOGo to iOS > push-sync, fail (yes, I tick synchronize the calendar ActiveSync) 

iOS standard contacts app > push-sync, yeah. But wrong fields

Conclusion, SOGo ActiveSync and iOS aren't friends

regards
jm3west

**Comment by mitchellurgero** [comment]
This is a known issue with SOGo, you should open an issue with them :) cheers!

**Comment by andryyy** [comment]
It depends on “wrong fields”. Don’t know what that means. It has a limitation, yes, but not any wrong fields. I think something like multiple cell phone numbers won’t work or individual labels, not sure rn. 

There isn’t a problem from SOGo to iOS I’m aware of. And since you didn’t provide any log and just say EAS and iOS aren’t friends (which is not true, they actually love each other), I close this as “information” or general SOGo feedback.
