### ISSUE TITLE
Mailcow with Floating-IP

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#1420]
Good evening,

within the installation of mailcow a FQDN has to be given.
My thought is to build up two instances of mailcow with a sync job to keep all mailboxes up to date.
How can i use a Floating-IP especially in connection with a FQDN tp switch between both instances?

Best regards
Feuernatter

**Comment by mkuron** [comment]
This kind of setup is not supported, see #174, #669, #1266. There would be conflicts if mailboxes change on both instances simultaneously. Redis and MySQL would be even more trouble, You’d be better of running Mailcow in a virtual machine that can be replicated and failover between multiple hosts.
That being said, Mailcow only cares about the FQDN and not the IP, so that part would probably work.
