### ISSUE TITLE
Question: Is communication to cloudmark.com on port 2703 required

### ISSUE THREAD

**Issue by cmonty14** [mailcow/mailcow-dockerized#1453]
Hi,
my firewall is blocking communication to cloudmark.com on port 2703:
`DST=208.83.137.118 {d302.cloudmark.com} LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=23523 DF PROTO=TCP SPT=50294 DPT=2703 WINDOW=29200 RES=0x00 SYN URGP=0`

Is this required by mailcow?

THX

**Comment by andryyy** [comment]
I think that’s razor2 and not used by mailcow dockerized.

**Comment by cmonty14** [comment]
Please note I'm on "old" mailcow that is **not** dockerized.
But considering this statement I will keep this communication port closed.

**Comment by mkuron** [comment]
> Please note I'm on "old" mailcow that is not dockerized.

Then this is not the right place to ask this question. The non-dockerized version is quite outdated by now, its issue tracker has been shut down and its repository has been archived. So you should consider migrating.

> I think that’s razor2 and not used by mailcow dockerized.
> But considering this statement I will keep this communication port closed.

The old Mailcow used Spamassassin instead of rspamd. That does use razor and the connection should be allowed for best spam filtering results.

Also, please do not open a new issue for every outgoing communication you are seeing (#1451). Spam filters connect to all kinds of places to get their signatures, definitions and DNS blacklists, so you will be seeing quite a number of connections whose purpose is not immediately obvious. If you would like to understand what these connections are, look through the spam filter configuration and source code.
