### ISSUE TITLE
auto-config in Gnome Online Accounts doesn't work

### ISSUE THREAD

**Issue by pschiffe** [mailcow/mailcow-dockerized#1532]
Hi all,

when I try to add `Microsoft Exchange` account in Gnome Online Accounts, I get the following error:
```
Error connecting to Microsoft Exchange server:
Failed to find ASUrl and OABUrl in autodiscover response
```

Do anyone see the same? Any tips how to solve this?

Thanks,

peter

**Comment by mkuron** [comment]
That‘s because Evolution (Gnome‘s groupware application) tries to use the Exchange Web Services protocol, which Mailcow does not and will never support. Exchange ActiveSync is available but not supported by Evolution, so you have to use IMAP/CalDAV/CardDAV. Last time I checked, Evolution did not support autodiscovery for those unfortunately.

**Comment by pschiffe** [comment]
Thank you @mkuron for explanation.
