### ISSUE TITLE
RSPAMD - howto reset statistics and reboot bayes training

### ISSUE THREAD

**Issue by rdanton** [mailcow/mailcow-dockerized#1537]
Amazon mails for example have BAYES_SPAM(7.50)[100.00%]. I don't know what went wrong, but I would like to restart the bayes training. Is there somewhere a howto?
Thank you!

**Comment by andryyy** [comment]
Have you ever moved them from junk to inbox?

**Comment by rdanton** [comment]
Yes I have ... always the same result 7.50

**Comment by andryyy** [comment]
```
# docker-compose stop rspamd-mailcow
# docker-compose exec redis-mailcow /bin/sh
/data # redis-cli KEYS *BAYES* | xargs redis-cli DEL
/data # redis-cli KEYS RS* | xargs redis-cli DEL
/data # exit
# docker-compose start rspamd-mailcow
```
👍

**Comment by rdanton** [comment]
Thank you for your help! Now it has to learn again ... then we will see!

**Comment by flybyray** [comment]
The automatic learning of RSPAMD is useless. It also learns its own errors and produces unnecessary subsequent errors. We have used mailscanners for years and had always trained it manually, making the system almost unbeatable in detection rate. We had used it so that emails were forwarded to special mailboxes (spam@, no-spam@). I miss such a simple solution in Mailcow.
Currently the system is simply chaotic because we cannot use the move mechanism in mailcow mailboxes. Since there are no real mailboxes there are only alias mailboxes that forward to a larger internal mail server.
Tried to explain it here: https://github.com/mailcow/mailcow-dockerized/issues/1547 that there should be more mechanisms to use spam/ham learning.

**Comment by andryyy** [comment]
Autolearn was disabled a few days ago.

A mailbox solution is probably possible, but I don't have much free time left at this moment...

**Comment by supersophie** [comment]
Will this ever be fixed?

**Comment by andryyy** [comment]
Dont even know what you mean.

**Comment by supersophie** [comment]
Hi,  I meant the rspamd BAYES autolearing. 
I found no way to disable auto learning in rspamd to stop it breaking bayes.

**Comment by andryyy** [comment]
Ah. :) It is not active at this point. You can move mail from Junk to * (except for Trash) to learn it as ham or move any mail from * to Junk to learn it as spam.

Autolearn will be enabled with Rspamd 2.0, since it was improved a lot.

**Comment by supersophie** [comment]
How did you disable bayes?  In the local.d/bayes-classifier.conf? And which value did you set?

**Comment by andryyy** [comment]
Disable autolearn? This is already disabled since a few months.

If you want to disable it, I recommend to just reduce the scores to 0 in `data/conf/rspamd/local.d/statistics_group.conf`.

Edit: And restart rspamd-mailcow. :)

**Comment by supersophie** [comment]
Thanks!

**Comment by supersophie** [comment]
Like this?

**symbols = {
    "BAYES_SPAM" {
        weight = 0;
        description = "Message probably spam, probability: ";
    }
    "BAYES_HAM" {
        weight = 0;
        description = "Message probably ham, probability: ";
    }
}**

**Comment by andryyy** [comment]
Yes, should be fine.
