### ISSUE TITLE
Set different MTU for docker interfaces

### ISSUE THREAD

**Issue by alexanderrieder** [mailcow/mailcow-dockerized#1558]
Hello :)
is it possible to lower the mtu of all the docker network interfaces to 1400? :)

Thanks in advance,

Alex

**Comment by andryyy** [comment]
Hi,
This is probably what you need (4.1) => https://github.com/mailcow/mailcow-dockerized-docs/blob/master/docs/install.md

:-)

**Comment by alexanderrieder** [comment]
Thank you :) how will i apply this configuration change in an already running mailcow system?

**Comment by andryyy** [comment]
Just change the file, run docker-compose down and docker-compose up -d. It needs to recreate the network, that's why all containers need to be removed with down first. it would complain if you tried to change a network with active end-points.

**Comment by alexanderrieder** [comment]
ok, but all my email data will survive? Just to be sure :D

**Comment by andryyy** [comment]
Yes, no volume will be deleted. Just **do not run** down with "-v" appended. This would delete your vols.

**Comment by MichaelReibel** [comment]
Hi andryyy,
first thanks for your help!
But where do I need to set this option?
Since every container seems to have its own Section in this file, ...
> networks:
  mailcow-network:
>
aperas pretty often.
Do I need to edit them all, right now I just changed the last one which I understand is something like a mastertemplate for the others?
It works for me now but it's still a little bit slow, just wan't to make sure that I did it right. (Hetzner vswitch needs MTU 1400 btw.)

Maybe you can be a little bit more specific in the install.md.

**Comment by andryyy** [comment]
Hi, you need to set it at the very bottom of the compose file only.

**Comment by MichaelReibel** [comment]
Sorry to bother you again, but does mailcow/docker add any overhead to the mtu?
I.e. I need an MTU of 1400, does docker(?) add 20bits for some vlan/bridge kind of stuff or does an mtu of 1400 mean that I get Packages of max 1400 byte over my real Network Interface?
Receiving an Mail is a matter of seconds now but sending takes 2-4 Minutes.

**Comment by andryyy** [comment]
Did you recreate the network? With down and up -d?

How do you measure the 2-4 minutes? Do you look at logs?

You should check the logs, maybe a mail was greylisted.

**Comment by MichaelReibel** [comment]
Hmm... you're right, Postfix log says the Mails where sent instantly. I think I have to do some more testing here.
Let's think about this issue as an false alert.
Edit: Now Mails sent pretty fast tho. o.O

To complete this thread, does docker add any bytes to the mtu of the virtual interfaces? So does a MTU 1400 Docker-interface send packages and add some byte so the host has to handle Packages of 14xx byte?
Since it's seems to be pretty fast now I guess not.
