### ISSUE TITLE
BCC Maps doesn't work at all?!

### ISSUE THREAD

**Issue by lalaluuu** [mailcow/mailcow-dockerized#1568]
If i create a bcc map, an incoming mail should be delivered (via bcc) to the given other e-mail address, am i sure?

I already tried both ways, but there isn't delivered any thing at all to the given e-mail address - it seems it ignores the bcc map at all.

**Comment by andryyy** [comment]
Can you post your `data/conf/postfix/main.cf` file content? 

And ` source mailcow.conf; docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME} -e "select * from bcc_maps"`

**Comment by lalaluuu** [comment]
Hi,

i didn't even know what i did, but it seems to work now .. 
Sorry for the inconvenience.

**Comment by orbatec** [comment]
I saw it work once, and after that is doesn't work anymore and I can't get it to work anymore...this Bcc map is very unclear to me... also a shame that there doesn't seem to be an API to set Forwarding rules like the user sets for himself in Sogo...

**Comment by andryyy** [comment]
Would be best to check the Postfix docs for BCC maps use. :)

It would be pretty bad to allow a user to set alias addresses. I don't think we should allow that.

Or... do you mean something else? A forwarding to another mail address? Like a forwarder in SOGo/sieve?

**Comment by orbatec** [comment]
Well...it is a bit of an artificial use case..... via our platform users use service from service providers. However, we miss out on a lot of services since many providers haven't got a decent back-end to integrate with. So our "solution" is to generate a custom mailaddress for a user that he can use to register with such providers. These mailboxes are under our control, so we can then process incoming mails with receipts and orders and process them for the user.  If we code an IMAP trigger, it would be a PIA to have polling for every mailbox...so I'd like to see a copy of every mail that comes in be delivered to an administrative mailbox so we only need to poll that one. Bcc Map seems to come closest to. this...
