### ISSUE TITLE
Backing up vmail

### ISSUE THREAD

**Issue by kilo42L** [mailcow/mailcow-dockerized#1578]
Inside the backup script this command backs up the vmail directory
```
docker run --rm \
        -v ${BACKUP_LOCATION}/mailcow-${DATE}:/backup \
        -v $(docker volume ls -qf name=${CMPS_PRJ}_vmail-vol-1):/vmail \
        debian:stretch-slim /bin/tar --warning='no-file-ignored' -Pcvpzf /backup/backup_vmail.tar.gz /vmail
```
Can I just backup the (virtual directory) with a script ?
cp `/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/`*  /somewhere/backups
?

Also.. how can I post this as a question and not an issue?

**Comment by PhoenixPeca** [comment]
Hi @kilo42L,
The helper script follows the best practices on backing up and restoring data from docker so it is recommended to use the _backup_ script. Hence the possibility of losing data is very unlikely. However, (I think) the `cp` method can also be used but you may risk messing up with the file permission and ownership or have problems with restoring.

**Comment by stAn47** [comment]
is there any way to refresh permissions in vmail after they are loaded from a backup (or migration) ? we just moved over 1TB of emails and chmod 777 does not seem to be the best solution. imapsync would take weeks to get synced, so we used just tar on maildirs.

as from within host view (/var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/) , mailboxes had "unknown" user:group when they were created. 

thanks, stan

**Comment by PhoenixPeca** [comment]
Hi @stAn47,
mailcow backup script uses `tar` (to preserve all permissions) and `gzip` to compress the _tar_ package. So, these permissions should remain intact on backup restoration.

**Comment by kilo42L** [comment]
The CP command was a bad example I just wanted proof of concept.
I will be using for this borg backup or rsync and it will preserve files.

The reason I ask the question is the simple backup script takes a long time to back up 20gb of email and during that time more email has already come in so for instance if I run a snapshot on my computer and test something out, if I have to restore then I have lost some incoming emails. With rsync it just backs up changed files.  In seconds I can roll back a snapshot and update vmail with rsync.

**Comment by PhoenixPeca** [comment]
> ... backup script takes a long time to back up 20gb of email and during that time more email has already come in ... **if I have to restore then I have lost some incoming emails.**

Or you can just stop all mailcow services and start the backup or restore. You could setup any number of failover mechanisms (while the mailcow is down) but in all reality, 99% of all email servers will simply queue the email (usually for a maximum of 48 hours) and continue to retry sending the email until your server is available again.

_helpful source: https://serverfault.com/questions/298477/storing-emails-elsewhere-when-exchange-server-goes-down_

**Comment by stAn47** [comment]
thank you, my point was mostly "how to restore permissions" when doing restore/migration some other way. 

i cannot really use tar since it's limited only to 64gb size (as far as i am aware) and if you wanted to move 1Tb mailboxes with tar, you would need another 1Tb for uncompressed tar and another 0.7Tb for gzip which would also take quite a lot's of CPU cycles as well and would take much longer to get it compressed then to get it downloaded over 1gbps or 10gbps line. since mails are already compressed there is no need for second round with gzip. 

we can use only self-made tar migrators without compression and for localhost the only possible backup solution is the rsync system. 

so the only point remaining is how to get those permissions fixed / to be the most secure. if all mailboxes use same user_id:group_id it's not a problem (i could execute chown vmail:vmail -R inside docker probably), but in case it separates domains with own user_id:group_id it would be nice to get it updated as needed. 

maybe this is the proper solution to my question: 
https://github.com/mailcow/mailcow-dockerized/issues/687

```
chown -R 5000:5000 /var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/*
```

i wonder what is the proper chmod for domains+mailboxes+folders+individual files. 

best regards, stan

**Comment by PhoenixPeca** [comment]
@stAn47 thanks for pointing that out. 😊😊😊

@kilo42L I hope we answered your question.

**Comment by strarsis** [comment]
Is there also an example for backing up one single mailbox completely, including SoGo stuff?
The whole domain and mailbox aren't needed anymore on that mailcow mail server.
I have to archive the old mailbox data so I can remove the unused mailbox from the mailcow mail server.

**Comment by andryyy** [comment]
Writing from my mobile and only guessing the pathes:

Copy the mailbox data from /var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/domain.tld/my-mailbox-I-want-to-copy
