### ISSUE TITLE
Dkim fails

### ISSUE THREAD

**Issue by Kironai** [mailcow/mailcow-dockerized#160]
Hello,
No matter how many times i create dkim and assign to my domain + put it in my cloudflare dns it says fail.. When testing mailing to gmail. I also tried other service which says fail also
Thanks

**Comment by andryyy** [comment]
Can you please update your images (`docker-compose pull`) and re-create Rspamds container? => 

```
docker-compose stop rspamd-mailcow
docker-compose rm rspamd-mailcow
docker-compose up -d
```

**Comment by fairlygood** [comment]
I had the same issue and this resolved it for me.

**Comment by mindsolve** [comment]
This seems to be a kinda common problem, is there something we can do to fix this? @andryyy
(Your solution also worked for me)

**Comment by andryyy** [comment]
Have you been using an older Rspamd image? Are you on master and not on dev? Is the DKIM signature really missing or do you just see logs saying "no key for domain xy"?

**Comment by mindsolve** [comment]
Well, I installed mailcow just 4 weeks ago (and forgot to note down the image version), and I didn't even look in the logs, but indead I have a "quarantine and inform" DMARC policy on my server/dns, so I got e-mails from some hosters I wrote to (like Google) that my mails were quarantined because DKIM failed.
And with the help of a website to diagnose dkim problems I saw that the DKIM header on the mail was signed wrong. After that I searched for "mailcow dkim" and vois là, here I am.

Edit: So for me the problem is solved, but maybe I can help in any way?

**Comment by andryyy** [comment]
The problem was not a wrong but a missing DKIM signature. So this is not related. The DKIM signing is not a problem. Maybe your DNS was not updated?

There was a problem in an older Rspamd Docker image that was fixed a while ago. So nothing to worry about anymore. :-)

**Comment by broedli** [comment]
I guess this is resolved.

**Comment by Braintelligence** [comment]
@broedli Maybe I should hire you for my issue solving :p
