### ISSUE TITLE
ActiveSync Calendar Names

### ISSUE THREAD

**Issue by ssm3e30** [mailcow/mailcow-dockerized#1631]
Hi All,

Thanks for the great package that is MailCow. I noticed after testing that the calendar links do not update with the change in a calendar name on SOGo. What this results in if you have several domains, is several calendars on a client (ie.Outlook) named "Calendar". Its tough to know which calendar you are adding events too at that point as that all have the same name.

Hopefully there is a work around or quick fix!

Shaun

**Comment by wizdude** [comment]
this behaviour seems consistent with outlook and exchange. my work environment uses outlook and exchange and you cannot rename the default calendar. i have multiple exchange accounts and thus multiple "Calendar"'s. i doubt this can be changed as it would potentially break compatibility.

you can rename the primary calendar in SOGo and this name does reflect on activesync, but not on outlook. I did a test now by renaming the calendar and the name changed on my iPhone calendar. i then created a new calendar on my iPhone and this appeared on SOGo and also on outlook all with the correct name.

what DOESN'T work, however, and i don't understand why, is if i create a new calendar in SOGo. this doesn't appear on my iPhone or outlook. I believe this part is a bug, because if i create the calendar from my phone it appears everywhere else.

cheers, wizdude.

**Comment by wizdude** [comment]
i've just worked out part of my issue - when you create an address book or a calendar, it's not set to sync via activesync by default. if you go to the properties of the address book or calendar there is an "Synchronize (Microsoft Enterprise ActiveSync)".

This works fine with SOGo and activesync devices such as iPhone, however outlook appears to have two specific limitations:

1. the primary calendar is called "Calendar" and can't be renamed (this appears to be the same with a full exchange/outlook implementation and probably by design)
2. you can only have one contact folder. i believe this could be a bug or limitation of activesync.

cheers, wizdude

**Comment by wizdude** [comment]
i've since discovered that there are specific limitations in Outlook in respect to SOGo and Activesync.

https://sogo.nu/files/docs/SOGoInstallationGuide.html#_microsoft_enterprise_activesync

Outlook 2013/2016 does not search the GAL. One possible alternative solution is to configure Outlook to use a LDAP server (over SSL) with authentication. Outlook 2013/2016 also does not seem to support multiple address books over ActiveSync.
