### ISSUE TITLE
Any guide on Performance tuning for mailcow?

### ISSUE THREAD

**Issue by adityadhawan22** [mailcow/mailcow-dockerized#1706]
How do I speed up Postfix for outgoing mails?

**Comment by andryyy** [comment]
Needs more information. :-(

Try to disable Rspamd with a settings map rule.

**Comment by adityadhawan22** [comment]
Already added this rule:
priority = 10;
authenticated = yes;
apply "default" {
  symbols_enabled = ["DKIM_SIGNED", "RATELIMIT_UPDATE", "RATELIMIT_CHECK", "DYN_RL_CHECK", "HISTORY_SAVE", "MILTER_HEADERS", "ARC_SIGNED"];
}

And added this in main.cf
smtpd_error_sleep_time = 0
default_destination_concurrency_limit = 200
default_process_limit = 200
smtpd_client_connection_count_limit = 200

**Comment by andryyy** [comment]
How fast is it right now?

**Comment by adityadhawan22** [comment]
150000 emils in 5 hours

**Comment by andryyy** [comment]
Sounds like those mails nobody wants. :-(

**Comment by adityadhawan22** [comment]
Promotional Emails to my List :-(

**Comment by tkorves** [comment]
150.000 mails? This looks indeed as it could be spam - sorry to be that honest.

**Comment by EnriqCG** [comment]
Hey @adityadhawan22, if you need to send (legit) bulk email the best possible idea is to use third-party email infrastructure.

**Comment by Mr-Martinez** [comment]
Mailcow is a mail server suite, not intended for mass emails. 
A newsletter application such as [Sendy](https://sendy.co/) might be something to consider as a self hosted solution.

**Comment by denisgomesfranco** [comment]
Sendy is a nice self-hosted solution which relies on Amazon SES to send e-mails. 150k mails would cost $15 to send.

But everyone is right, @adityadhawan22 should use a mass sending solution such as SendGrid, Mailchimp or Elastic Email. Far more reliable, better tools, list management functions, etc.

**Comment by maarsaks** [comment]
It's been a while since the issue was created so any solutions to increase performance?
We want to send about **5 000 000** mails per month... I know it's a lot, but we are looking for an **open-source self-hosted** solution which is scalable. We will use OVH bare metal servers or AWS Instances on Kubernetes.
So, any thoughts? Will mailcow be able to handle it or how to prepare the server?

Second, any tools to monitor the performance? With Prometheus, Grafana or Zabbix?
