### ISSUE TITLE
Redirect http to https without breaking acme-client

### ISSUE THREAD

**Issue by drosskopp** [mailcow/mailcow-dockerized#1715]
Redirect HTTP to HTTPS in the Documentation
https://mailcow.github.io/mailcow-dockerized-docs/u_e-80_to_443/

If 
```
server {
  listen 80 default_server;
  listen [::]:80 default_server;
  include /etc/nginx/conf.d/server_name.active;
  return 301 https://$host$uri$is_args$args;
}
```
is changed to
```
server {
  listen 80 default_server;
  listen [::]:80 default_server;
  include /etc/nginx/conf.d/server_name.active;
  location /.well-known {
      try_files $uri $uri/ =404;
  }
  location / {
      return 301 https://$host$uri$is_args$args;
  }
}
```
it will not break the acme-client needed on port 80 and everything else is redirected to https.
If this would be default in mailcow (Who wanna serve http if it's not absolutely necessary) also the warning on https://mailcow.github.io/mailcow-dockerized-docs/firststeps-ssl/ could be removed.

**Comment by mkuron** [comment]
The ACME validator follows the redirect, so there is no need to treat it specially. Since it always checks port 80 for the challenge (that's what the warning is about), it either needs to be accessible there, but it follows redirects, so an unconditional redirect to port 443 works too.

Also, you unconditional redirect of /.well-known breaks CalDAV/CardDAV autodiscovery.
