### ISSUE TITLE
Questions about Mail relay

### ISSUE THREAD

**Issue by hunter-nl** [mailcow/mailcow-dockerized#1724]
I've created a domain with a relay host specified, enabled Relay domain and enabled Relay all recipients.
What I expect when message gets delivered to mailcow for this domain, gets relayed to the specified relay host. But what it does is lookup de MX DNS records and just sent it to one of these MX hosts. And one MX record is pointing just to this same mailcow host and just sending the message to itself.
Is this as designed behaviour of Mailcow? Or I'm doing something wrong? What is the function of specifying the relay host if it is not used?

**Comment by HesselTjeerdsma** [comment]
You are confusing two options I think. The "relay this domain" is for backup-mx servers. When you select this option mailcow will store the email and relay it to the primary email server when that comes back online. If you deselect these boxes, and then specify the relay host it should work!

**Comment by hunter-nl** [comment]
When I deselect the boxes, then relay host still not working. When there is no mailbox created for this domain, then postfix will not accept any address.
`550 5.1.1 <user@example.tld>: Recipient address rejected: User unknown in virtual mailbox table`
When I create a mailbox with an email address for this domain, then the message is accepted and delivered locally for this email address only. Not relayed to the relay host. It looks like the relay host is only for outbound messages when it has been created in the user mailbox.
So, how can I relay this domain without using the MX records and just to a specified relay host for all incoming messages? Maybe a new enhancement, andryyy?

**Comment by Mr-Martinez** [comment]
You need that MX records in order to store email on the relay server when your primary server is down. 
It lets other servers know that these servers specified in your MX records are authorized to accept mail on your domains behalf. So when one is down, emails go to the next on the priority list.

As for sending mail between users on the same domains, thats how [SMTP](https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol) works.
Your mail doesn't even enter the internet (in the case of single mailcow server).
