### ISSUE TITLE
Docker Stack compatibility

### ISSUE THREAD

**Issue by Dunky13** [mailcow/mailcow-dockerized#1806]
Hi,

Right now I have to run MC-dockerized in a seperate VM. I'd like to run in as a Docker stack on the main machine instead of in a VM/dedicated machine.

Docker stack uses the same/similar docker-compose.yml file structure. But V2.1 doesn't work for me.
Also the current set up counts on the `generate_config.sh` script.

Docker stack also allows for higher availability (from what I've read).

Hope this feature could be implemented.

**Comment by mkuron** [comment]
I don't know Docker Stack, but it looks similar to Docker Swarm. Please see https://github.com/mailcow/mailcow-dockerized/issues/1004#issuecomment-366689423. Mailcow has some complexities that don't work with Swarm, but most of it should work.

You can run the config script anywhere and just copy the resulting config file to your server.

High availability is going to be difficult because Mailcow has so much state (databases, mail queues,  etc.). There are open issues where this was requested. Spreading out services over multiple hosts could work though.
