### ISSUE TITLE
Non docker installation???

### ISSUE THREAD

**Issue by KipourosV** [mailcow/mailcow-dockerized#1813]
Can we please have traditional install instructions/method for installation outside docker?

**Comment by Braintelligence** [comment]
Not this discussion again... There are several issues discussing this already and not even once could anyone explain a valid reason for ditching docker.

**Comment by KipourosV** [comment]
Can you point me to those issues pls?
Would like to deploy in lxc container, that's my reason.
What is the reason behind only docker version?

**Comment by Braintelligence** [comment]
Googling for Mailcow dockerized lxc would have pointed you to this issue: https://github.com/mailcow/mailcow-dockerized/issues/670

**Comment by damdinsharav** [comment]
Hello @Braintelligence,

Can you write guide on how to install Mailcow on Proxmox LXC container?

**Comment by Adorfer** [comment]
As a a user of more than 10 physical servers running proxmox, i hardly advise to use (qemu) VMs instead of LXC. throtteling/taming issues are really diffucult to overcome on LXC on something complex like a mailserver setup. 
For your questions: 
1) why docker: Because the maintainer opted for that and that's in terms of maintenance the only feasable option: focus on one path. 
2) how to change it: if you want something else than dockerized mailcow: 
fork, build a team, maintain and backport. No other option available.

**Comment by damdinsharav** [comment]
@Adorfer Thank you. I will go with VM.

**Comment by mjapple** [comment]
thanks for all efforts 
please consider:
-docker made the other mysql unstable 
-running nginx or httpd we have issue, i have httpd for other other webpages and now trying different ports and have no answer

**Comment by andryyy** [comment]
Docker doesn’t make MySQL unstable. 

Just use a reverse proxy or bind mailcow to another port (the latter will obviously break Lets Encrypt verification).

**Comment by bernd-wechner** [comment]
> Not this discussion again... There are several issues discussing this already and not even once could anyone explain a valid reason for ditching docker.

This made me laugh ;-). Sorry. But it's what we calla non-sequitur. That is, if "Not this discussion again... " holds true then "not even once could anyone explain a valid reason for ditching docker" cannot simultaneously hold true. That the issue is recurrent demonstrates demand and that other see valid reasons ... inability to see them  or more likely simply disagreement with them, is fine but does not perforce invalidate them, that is the nature of different perspectives, needs, desires, dreams.

Personally hold no great view on the matter and am happy with a docker install but might add, I would always prefer to avoid nginx and mysql (I roll out exclusively lighttpd and postgresql) but would not feel any need to justify that to anyone it simply is, and for that reason, don't like to see them bundled into complete solutions. That said, my objection to nginx and mysql is not so strong that I'd refuse to install mailcow:dockerized, but I do have a more sympathetic understanding of folk who start "this discussion again... " I guess, and less dismissive. 

For that reason alone I'm always pleased when dockerized solutions also publish simple even if unsupported, raw install summaries. But hey, I can't insist on that, I just enjoy it and understand the broader desire for it among others.
