### ISSUE TITLE
Donating via Paypal requires login or creation of a Paypal account

### ISSUE THREAD

**Issue by brendonmackenzie** [mailcow/mailcow-dockerized#1833]
I really like mailcow-dockerized and want to donate although I do not want to create a Paypal account to do this. The current configuration of the Paypal doesn't seem to allow this:
![paypal](https://user-images.githubusercontent.com/43494886/46448727-d718d580-c7e4-11e8-9e7d-d4c70c2f3a8f.png)

**Comment by mitchellurgero** [comment]
Their bitcoin donation link allows for anon / no-login-required donations: https://mailcow.email/

**Comment by MAGICCC** [comment]
As far as I know there is an option in the donate button settings to allow non paypal users to donate. Maybe they removed it after changing their layout to the new one
@andryyy may check this

**Comment by andryyy** [comment]
Hmmmm, that's strange. I enabled "PayPal account is optional" in the settings. :-(

**Comment by Adorfer** [comment]
Even if you do not "have to have a paypal account", if you read the ToS, you will be aware that you will become a paypal-member with an internal account as well. You just can not log into this account (due to a lack of password/credentials) until you finally decide to "open up" an account... and voila, there are the "non account"-transfers....

(But that's not the point of this discussion i assume)

My suggestion would be to add something like gofundme and/or patreon. 
Especially patreon is (in my point of view) a commonly used platform which is not in the realm of a "data harvester", but off course ToU-discussions are everywhere.

**Comment by sorcer1122** [comment]
It seems like donating now requires a full registration, including address, phone no etc. Any change to donate without it?

**Comment by ValdikSS** [comment]
> Their bitcoin donation link allows for anon / no-login-required donations: https://mailcow.email/

I can't find Bitcoin address on the website. Could you point where is it?

**Comment by Adorfer** [comment]
Just use Patreon or Github sponsorship, both is available. 
(And don't blame the author for the ToU of those payment providers. They are obliged by law to keep valid records if the pay out more than a certain amount to single people. and that value is more in the low than in the high 4 digits USD/EUR range. And i do totally support when a project stays clearly away from the cryto currency stuff for ethical reasons.)

**Comment by MAGICCC** [comment]
Best would be using a SAL https://www.servercow.de/mailcow?lang=en#sal
With that you can also enable `WATCHDOG_EXTERNAL_CHECKS=y` in your mailcow.conf file

**Comment by ValdikSS** [comment]
>Due to recent events we will require customers to register without VPN or proxy service. Please excuse the circumstances.
>Your order can not be processed at this time.

**Comment by ghost** [comment]
> >Due to recent events we will require customers to register without VPN or proxy service. Please excuse the circumstances.
> 
> >Your order can not be processed at this time.

Just disable it and enable it again after? 🤷🏻‍♀️
