### ISSUE TITLE
needed user rights / file rights while using mailcow

### ISSUE THREAD

**Issue by lgusewski** [mailcow/mailcow-dockerized#1893]
I run a mailcow since months with success and also the updates runs mostly fine. To have a backup, i added on my local Synology NAS a server backup plan to fetch every day the files from the mailcow repository on my server. But in this backup job i found some errors about missing rights. The files are in data/conf/postfix/sql and had the user "root" and group "systems-timesync". I wonder a little bit about "root" user and the group. Additional files had to do with the certificates.
Because i use a user with sudo rights, i had started and updated mailcow every time with the sudo command and i works, but it was also clear why the Synology backup job can't work completely. I tried what happened when i change the user and group to my user and i broke my cow. It seems not be possible to use mailcow only with "normal" user rights. Later i found some warnings about wrong rights in postfix config:

warning: not owned by root: /opt/postfix/conf/./postscreen_access.cidr
warning: not owned by root: /opt/postfix/conf/./smtp_dsn_filter
warning: not owned by root: /opt/postfix/conf/./main.cf
warning: not owned by root: /opt/postfix/conf/./master.cf
warning: not owned by root: /opt/postfix/conf/.

Then i tried what i got when i fetch a new instance of mailcow in /opt/mailcow-dockerized and run again with sudo and my old conf file. In this case i found some others warnings in my log:

warning: mysql:/opt/postfix/conf/sql/mysql_virtual_domains_maps.cf: query failed: MySQL server has gone away
warning: mysql:/opt/postfix/conf/sql/mysql_virtual_alias_maps.cf: query failed: MySQL server has gone away

After a short shock i restart the container and the warnings are gone. There was also a line about default settings, so perhaps they are the reason. After checking around all logs, it seems that my cow is healthy again. No mails are missing, all containers are green and i also wake up the watchdog, which also said everything is running fine.

Next step was reading twice the documentation about the first install, but i did not found some information about the needed user rights for the user, which is starting the mailcow instance.

So the actual stand is that my cow is moved from a directory inside the user home to /opt like in the documenatation recommended and is started again over sudo. Owner of the files is "root".

Is this the needed way or are there betters ways i did not thought about to minimize security problems? Used linux distribution is ubuntu server 18.04.01 LTS.

**Comment by andryyy** [comment]
There is no security problem starting mailcow as root. Adding a non-root user to the Docker group will also spawn the container "privileged" with all procs inside the container running as root by default. 

We drop the privileges inside the container where we need to. These are (more or less) isolated environments.

When you mount a file into, for example, dovecot-mailcow and chown it root:401, it will belong to group "dovecot" or "dovenull" _inside the container_. GID 401 will probably be a different group (if any) on your host system. That's why you may see root:systemd-timesync on your host - group ID 401 would be systemd-timesync here.

I think sudo carries the users environment, you should at least run sudo -i or sudo su and run as root when you update or install mailcow.

After all... you use your own backup routine (ok, but not supported) and seem to skip file permissions (not sure, but bad), that will not work. It is also not a bug report or feature request, our issue template states that you can ask for support on IRC. :-)

Postfix auto-fixes file permissions with the latest image, btw.

**Comment by lgusewski** [comment]
Thanks for feedback. Only to clarify: The Synology backup service should only copy the local repository files and the backup files, i created over the helper scripts, outside the server to my nas. I thought that so backup both is a good idea.

**Comment by andryyy** [comment]
Okay. :-) Try to copy with cp -rp.
