### ISSUE TITLE
Messages I send are tagged with MID_RHS_NOT_FQDN

### ISSUE THREAD

**Issue by wblondel** [mailcow/mailcow-dockerized#1979]
Hello,

Thank you for developing this project.

I can send and receive emails without problems. I just noticed one issue which may cause my emails going to the spam folder of @gmail.com recipients: the "message ID" of the emails I send do not contain a fully-qualified domain name.

Here is the message ID of an email I just sent:
```
39-5bdddf80-3-4abf3d80@195860742
```

How do I put my FQDN instead of  `195860742` ?

Thank you for your help

**Comment by K2rool** [comment]
The email going to Spam folder on Gmail will not because of the Message-ID as Email I send via SOGo got the same format for Message-ID and get inbox no issues.

The real reason for email going to spam folder could be but not limited to Incorrectly setup dns/dkim, spamming looking email content, poor domain or sender ip reputation e.g. blacklisted ip.

**Comment by wblondel** [comment]
Ok, so this format of Message-ID won't cause any issue, that's 100% sure?

When I test my emails with https://www.mail-tester.com/?lang=en I get 10/10, DKIM/SPF/DMARC is correctly setup, and my ip isn't blacklisted anywhere.

**Comment by mkuron** [comment]
The message ID is generated by the client, e.g. SOGo or Thunderbird. Commonly it is an FQDN, which is why rspamd tags MID_RHS_NOT_FQDN if it‘s not, but that is not a hard requirement.

You can register for Google‘s Postmaster service. That usually tells you why and how many of your messages are being tagged as spam by Gmail.

**Comment by wblondel** [comment]
I registered for Google's Postmaster service few days ago, but it only shows data once the email volume is important (200 messages / day, which will never happen).

Regarding the message ID, ok, thank you for the information. What setting should I modifiy if I want to include my FQDN? Thanks

**Comment by mkuron** [comment]
In SOGo? Recompile it yourself after editing the function that generates it: https://github.com/inverse-inc/sogo/blob/a257607a0676b5a4b1612cc731b126bb59e1b24d/SoObjects/Mailer/NSString%2BMail.m#L559-L570. In Outlook, you are probably out of luck. In Thunderbird, it may be configurable in some obscure place. Really, you don't need to change the Message-ID.
