### ISSUE TITLE
Split Domain Routing

### ISSUE THREAD

**Issue by catcun** [mailcow/mailcow-dockerized#206]
I am migrating a domain from external IMAP to Mailcow Dockerized but I need to do it incrementally. So, I am trying to setup Split Domain Routing and I need help as I have not been able to make it work. Here is what I have:
Domain: mydomain.com
Server1: Current SMTP/IMAP server; MX records for mydomain.com point here
Mailcow1: New server. Has mydomain.com as a regular domain and mydomain.helperdomain.com as an alias to mydomain.com. MX records for mydomain.helperdomain.com point here.
Mailboxes: bob@mydomain.com and jane@mydomain.com

I want to move bob@mydomain.com to Mailcow1 so I have the following redirection: bob@mydomain.com -> bob@mydomain.helperdomain.com on Server1 and a regular mailbox on Mailcow1.
I have been playing with Postfix transport_maps and I have been able to send/receive from the Internet (other domains) without a problem. After playing a lot trying to trick Postfix and creating a local Mailcow1 account for jane@mydomain.com I have been able to send from bob to Jane, but I have not been able to send from Jane to Bob no matter what.
I guess that I may have to play with the sql files but I’m not sure where to begin. Can anyone direct me to the right path? The only changes that I have from a current stock Mailcow Dockerized are:
main.cf:
	transport_maps = hash:/opt/postfix/conf/transport
/opt/mailcow-dockerized/data/conf/transport:
	jane@mydomain.com  smtp:[mail. mydomain.com]:25
	bob@mydomain.com :
Thank you.
//catcun

**Comment by andryyy** [comment]
Hi,
Just to be sure: You postmap'ed the transport map?
Can you show me the output of `docker-compose logs --tail=300 postfix-mailcow` after trying to send a mail which does not route correctly?

**Comment by catcun** [comment]
Hello,
Yes, I created the hash database with postmap. I had to use docker-compose exec postfix-mailcow postconf -e "transport_maps = hash:/opt/postfix/conf/transport" instead to edit main.cf as postfix was not loading the changes when editing, at least postconf -n didn’t reflect them.
By the way, there is only one mailbox in Mai.cow: bob@mydomain.com
Anyway, here are the anonymized logs:

[logs.txt](https://github.com/andryyy/mailcow-dockerized/files/928607/logs.txt)

**Comment by andybeesee** [comment]
Just to clarify, Jane is using the original e-mail server and can not send to Bob on the Mailcow server?

If the above statement is correct then I don't think setting up transport maps on Mailcow will be able to solve your problem.  The [postfix manual](http://www.postfix.org/transport.5.html) says transport maps are only for determining the outgoing transport.  You will need to set up transport maps on the original server (where Jane's account is located) in order to send to Bob on Mailcow1.

I'm working out a migration path to Mailcow right now as well. I am using transport_maps on mailcow to direct mail from users on mailcow to users on our old e-mail server. For users that are migrated to Mailcow I use [Fetchmail](http://www.fetchmail.info/) to pull their e-mails from their inbox on the old server in to their Mailcow account. It isn't instant, but it is a bit simpler. You could also use [GetMail](http://pyropus.ca/software/getmail/) for pulling e-mail from one server in to the local server.

While testing I added the field `transport` to the `mailbox` table in order to hold transport information. Added this line `transport_maps = proxy:mysql:/opt/postfix/conf/sql/mysql_transport_maps.cf` to main.cf, and this is my `mysql_transport_maps.cf` file:

```
user = mailcow
password = password
hosts = mysql
dbname = mailcow
query = SELECT transport FROM mailbox WHERE username='%s';
```

I haven't run in to any problems in the past day. If there is interest I can flesh out the implementation and submit a pull request.

**Comment by catcun** [comment]
Hello,
Jane is on Mailenable (ME) who holds the MX records and Bob is on ME as a forward to a helper alias domain and as a mailbox on Mailcow (MC) like this: bob@mydomain.com (ME) -> bob@mydomain.helperdomain.com (MC alias) -> bob@mydomain.com (MC). And that works wonderfully so I do not need special routing on ME.

The problem is that Postfix sees mydomain.com as a local domain and tries to always deliver locally to it, ignoring the MX records. I need to configure Postfix as a SmartHost that delivers locally to accounts on MC and using MX records for accounts not present on MC. That's the way Office 365 works.
As every email that gets on ME is forwarded to MC I only care about moving old messages. For now, that is covered using imapsync, later I may finish/use a custom script to move ME's EML messages directly to dovecot Maildir while preserving UIDs.

Your solution with a transport field sounds very interesting, I would like to know more about it. And yes, I have not been able to make the Split Domain Routing work.
Thank you.

**Comment by catcun** [comment]
Hello,
Here is my temporary solution:
In addition to what was explained in my first post:
-	I changed smtpd_sender_restrictions in main.cf to include 
check_sender_access hash:/opt/postfix/conf/sender_access 
-	The sender_access table in data/conf/postfix/sender_access has 
jane@mydomain.com OK
-	Built the map table with portmap.
-	I created a dummy mailbox for jane@mydomain.com (to avoid Recipient address rejected: User unknown in virtual mailbox table error)

I am not very comfortable with how I am handling sender_access but for now this seems to be working. I will share a better solution if I find one. Thanks to everyone.
