### ISSUE TITLE
Using separate user for Docker containers

### ISSUE THREAD

**Issue by chmich** [mailcow/mailcow-dockerized#2069]
Hi,

in your [tutorial](https://mailcow.github.io/mailcow-dockerized-docs/install/)
could you please add:
As which user is it to install?
is this all as root?

Thanks,
Christian

**Comment by MAGICCC** [comment]
Normally you don't  want to run things as root, but honestly most users run docker as root.
Of course you can add your user to the docker group and ensure that your user has access to the mailcow directory

**Comment by andryyy** [comment]
Si.
All containers drop rights where possible and necessary. To start the containers you need a privileged user. It does not make a difference wether or not you start the stack as root or privileged user within the Docker group. :)

**Comment by roelofz** [comment]
Hi,

Before on topic: I'm very impressed with the total package, have migrated already from server to server, using the (freshly created instructions), very impressed by the documentation and how complete the solution looks! I am confident I will succesfully migrate my existing home server to the new moo!
 
On topic!
As found on multiple sources: 

"9) Don’t run processes as a root user – “By default docker containers run as root. (…) As docker matures, more secure default options may become available. For now, requiring root is dangerous for others and may not be available in all environments. Your image should use the USER instruction to specify a non-root user for containers to run as”. (From Guidance for Docker Image Authors)"

I must admit, I'm new to docker, so it may be my problem to fix this.
But as mentioned above, the image should use the "user" instruction to specify a non-root user.
Can you change this in the images (possibly with the requirement to create a local user at first)?

Thanks!

Roelof

**Comment by andryyy** [comment]
All containers drop rights where possible and necessary. 

:)

**Comment by roelofz** [comment]
What if I want to establish a higher security level by running all Mailcow containers using another account? How to establish this, being also assured it won't be rolled back with an update?

Do you have an advice?

**Comment by mkuron** [comment]
@roelofz, it will definitely cause conflicts with future updates, so we advise not to do it. It wouldn’t actually give you higher security because Docker is designed to provide isolation through kernel namespaces, which does not need user isolation.

As long as the Docker developers themselves don’t say that you shouldn’t use root inside a container (and that seems highly unlikely, since this is how they designed Docker), we aren‘t going to change what users Mailcow runs as.

> Guidance for Docker Image Authors

I assume you are referring to http://www.projectatomic.io/docs/docker-image-author-guidance/. That says things like "A docker container running as root has full control of the host system.", which is just wrong and would defeat the point of Docker, so I would not trust their advice.
