### ISSUE TITLE
Question: Mailcow without IPTables

### ISSUE THREAD

**Issue by AndreKoepke** [mailcow/mailcow-dockerized#2104]
Hey,

I had problem with mailcow.
My docker-installation running without iptables (aka `--iptables=false`), so have to take on my iptables for my own.
So I enabled the ports of the docker-container of mailcow in my iptables.

But this tactic is not good. Postfix dosen't see this forwarding process. All incoming transmissions are from the host-docker-ip ... and everyone can use SMTP without authenfication (because the host-ip is part of the mynetwork-setting in the postfix-container).

What can I do?

**Comment by mkuron** [comment]
Run Docker with `--iptables=true`, check which rules are created (`iptables --list`), and create them yourself. Then switch back to `--iptables=false`. Note that the IP addresses used by the containers are randomly generated, so you will need to query Docker every time Mailcow is brought up in order to find out which IP address the Postfix, Dovecot and Nginx containers have been assigned.

> Postfix dosen't see this forwarding process.

You are probably masquerading instead of just forwarding.

**Comment by AndreKoepke** [comment]
Are the rules not somewhere saved? (The docker-iptables-rules causing serious problems)
