### ISSUE TITLE
Active Sync not working anymore

### ISSUE THREAD

**Issue by ntimo** [mailcow/mailcow-dockerized#2112]
**Describe the bug**
After Upgrading to the latest version of Mailcow Active Sync is not working anymore on iOS "The connection to the server failed". I tested it on my Mac and Apple Mail on my Mac works via IMAP it works

**How to reproduce Reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
1. Try to setup Active Sync on a iPhone
2. Conntection error

**Expected behavior**
E-Mails should sync and push should work

**System**
 - OS: iOS 12.1.2
 - Apple Mail

**Comment by Stargate85** [comment]
I have the exact same issue. I use Mailcow dockerized for more then a year. I updated it today and since then Active Sync isn´t working anymore. Its independend from the Client. So it doesn´t work with iOS and also not with Outlook.
Everthing else works fine (IMAP, Web Access...)

I can see a connection in the SoGo logs coming but nothing else:

21.12.2018, 19:53:04	notice	[61]: 79.203.28.XXX "OPTIONS /SOGo/Microsoft-Server-ActiveSync HTTP/1.0" 200 0/0 0.003 - - 0
21.12.2018, 19:53:02	notice	[61]: 79.203.28.XXX "OPTIONS /SOGo/Microsoft-Server-ActiveSync HTTP/1.0" 200 0/0 0.012 - - 1M
21.12.2018, 19:53:02	notice	[58]: 79.203.28.XXX "OPTIONS /SOGo/Microsoft-Server-ActiveSync HTTP/1.0" 200 0/0 0.004 - - 0

Update: New SoGo Container fixed it after running update. Thanks andryyy

**Comment by ntimo** [comment]
Fixed
