### ISSUE TITLE
Can´t access mailcow under new domain on port 80 (http)

### ISSUE THREAD

**Issue by DJIronic** [mailcow/mailcow-dockerized#213]
Hello,

I am trying to add new domain to mailcow.

I added the domain into administration...

I can access mailcow under HTTPS (non-valid cert), but I can´t access it under HTTP - connection refused.

So I can´t add this new domain to LE cert => I can´t add this domain.

This problem I have only with this domain, on already added domains...I can access amilcow under HTTP.

You can see it here, I can access mailcow under https://mail.fusionolomouc.cz, but I can´t access it under http://mail.fusionolomouc.cz

**Comment by chaosbunker** [comment]
The problem is, that LE can't connect to mail.fusionolomouc.cz, because nginx does not know about it

Just add `mail.fusionolomouc.cz` in `data/conf/nginx/server_name.active` and do `docker-compose up -d` then you can expand your certificate

**Comment by DJIronic** [comment]
Thank you for you answer...but I don´t have data/conf/nginx/server_name.active in mailcow-dockerized folder :(

**Comment by chaosbunker** [comment]
Well, normally as soon as you executed the generate-config.sh and ran `docker-compose up-d` for the first time, `data/conf/nginx` folder shadows `/etc/nginx/conf.d` - part of the startup routine when you run mailcow-dockerized is to insert the value of ${MAILCOW_HOSTNAME} into the templates you see in the template folder inside the nginx folder and then write all that into the file server_name.active (and the ports into the listen files) .. that happens inside of the container. but since `data/conf/nginx` is mounted as a volume you can get to the files easily.

So if you follow the instructions on how to install, the file will show up;-)

**Comment by DJIronic** [comment]
Thanks, I got it :)

**Comment by chaosbunker** [comment]
I realized, you have to add your domain to `data/conf/nginx/templates/server_name.active` so your changes don't get overwritten again
