### ISSUE TITLE
SOGo Theme

### ISSUE THREAD

**Issue by patrick7** [mailcow/mailcow-dockerized#2144]
Is there a way to get the old mailcow theme back?
The stock SOGo is horrible.

**Comment by aurixtech** [comment]
Is fixing the blue theme on the project list at all?

I understand why the mailcow theme has been disabled, but SOGo's default theme is really terrible once you are used to the old mailcow blue theme.

Currently, the mailcow documentation just says the theme "would not be fixed in the near future". I'm just hoping reverting to the custom theme is part of the future planned commits.

**Comment by patrick7** [comment]
It seems I'm not alone :-)
Is there a way to install it on my own risk?

**Comment by AienTech** [comment]
hey there... so, still no solutions? is there any way to change the SOGOs default theme?

**Comment by DatAres37** [comment]
Check this out: https://sogo.nu/files/docs/SOGoDevelopersGuide.html#_defining_an_alternate_color_theme
Get the old JS via `wget https://github.com/mailcow/mailcow-dockerized/raw/4755bb323b1d16f593c45c7695b2ff1645b455e9/data/Dockerfiles/sogo/theme-blue.js` and replace the theme.js
Get the old CSS via `wget https://github.com/mailcow/mailcow-dockerized/raw/4755bb323b1d16f593c45c7695b2ff1645b455e9/data/Dockerfiles/sogo/theme-blue.css` and replace theme-default.css

Path in the sogo container: `/usr/lib/GNUstep/SOGo/WebServerResources/js/` and `/usr/lib/GNUstep/SOGo/WebServerResources/css/`

**Comment by G2G2G2G** [comment]
> hey there... so, still no solutions? is there any way to change the SOGOs default theme?

https://mailcow.github.io/mailcow-dockerized-docs/third_party-roundcube/
I'd try roundcube, it's far more usable than SOGo is, 70% of the UI is wasted not sure why anyone thinks this is a good idea *cough microsoft*

**Comment by DatAres37** [comment]
> 
> 
> > hey there... so, still no solutions? is there any way to change the SOGOs default theme?
> 
> https://mailcow.github.io/mailcow-dockerized-docs/third_party-roundcube/
> I'd try roundcube, it's far more usable than SOGo is, 70% of the UI is wasted not sure why anyone thinks this is a good idea _cough microsoft_

Roundcube seems kinda outmoded and stale to me + I don't really want to support them anymore as they messed up the whole Roundcube Next project, which I was really looking forward to. Some plugins just don't work anymore and aren't maintained or other stuff...
I think SOGo is great in terms of compatibility and collaboration and you can change the theme with the solution I've posted.

**Comment by G2G2G2G** [comment]
@DatAres37 Are the plugins even made by them? Roundcube out of the box seems infinitely more usable than SOGo, and after discovering they display passwords in plaintext I'm not sure I'll even allow my company to use SOGo. 
I agree SOGo is great in terms of compatibility and keeping up with stuff, the user interface is easily the worst that I've seen exists for email, it is insane how much wasted space there is. And it is extremely slow for how little information is displayed. Theme is far from the only issue. 

I can't find any other WEB + IMAP softwares that exist that are as data dense as roundcube, for email.

**Comment by AienTech** [comment]
> @DatAres37 Are the plugins even made by them? Roundcube out of the box seems infinitely more usable than SOGo, and after discovering they display passwords in plaintext I'm not sure I'll even allow my company to use SOGo.
> I agree SOGo is great in terms of compatibility and keeping up with stuff, the user interface is easily the worst that I've seen exists for email, it is insane how much wasted space there is. And it is extremely slow for how little information is displayed. Theme is far from the only issue.
> 
> I can't find any other WEB + IMAP softwares that exist that are as data dense as roundcube, for email.

@G2G2G2G in this case you can easily disable the sogo container, run a roundcoube container separately and connect it to your docker-compose setup.

**Comment by G2G2G2G** [comment]
Yea I have that already, I just think it's ridiculous they're storing plain text passwords in JSON.. I thought they were better than the $8 an hour bank programmers who get laughed at for that.

**Comment by andryyy** [comment]
Just disable external accounts. It does NOT store credentials if you don't add external profiles. What the heck...

**Comment by DatAres37** [comment]
> @DatAres37 Are the plugins even made by them? Roundcube out of the box seems infinitely more usable than SOGo, and after discovering they display passwords in plaintext I'm not sure I'll even allow my company to use SOGo.
> I agree SOGo is great in terms of compatibility and keeping up with stuff, the user interface is easily the worst that I've seen exists for email, it is insane how much wasted space there is. And it is extremely slow for how little information is displayed. Theme is far from the only issue.
> 
> I can't find any other WEB + IMAP softwares that exist that are as data dense as roundcube, for email.

No, most of the plugins are not made by Roundcube, which adds another layer of error-proneness and complexity. I used Roundcube some month ago and I never managed to get the calendar plugin running properly for example. Not sure if it was even meant to work still.
Roundcube also has some nice skins by third-parties, but only if you pay for them and even then you can't be sure they're not buggy or will be discontinued (which happened to me). 

Over all it's obviously a personal choice, but I was glad when I saw that mailcow doesn't use Roundcube by default, because I was sick of it. Maybe there are other users with more luck or dexterity. I've also no idea what people mean with "extremely slow" when they use SOGo. I used it on multiple devices without problems + you can change or disable effects for example.

**Comment by G2G2G2G** [comment]
That's understandable when you don't actually use your email, but people at companies who handle possible hundreds of estimates per day need data density lists. Not an ugly theme that takes 40% of your screen to display 5 lines. Also it's in angular which in nature is slow. The load time on a processor with 4.5GHz is 853ms average, just because of how angular lazy loads stuff. Themes and colors aren't relevant to work performance.

**Comment by DatAres37** [comment]
Not sure what you mean with "use your email". If I'm running a mail server, I'm obviously using it. And no offense to Mailcow, but if you're running a company, that has specific requirements and huge workloads like that, you'd probably want to use one of the big-player business solutions anyway that is supported throughout the business including maintenance agreements with dedicated servers instead of Docker, although I'm appreciating the use of open source tools. I think you're missing the intended use here a bit tho.

SOGo is perfectly fine for smaller communities or private use and is widely used by universities in Germany with no problem.
But I guess we should just be glad that there are solutions for anyone :)

Am 6. August 2019 21:21:42 MESZ schrieb G2G2G2G <notifications@github.com>:

**Comment by AienTech** [comment]
There are two things you have to pay attention to @G2G2G2G , one thing is the SOGo and another one is the whole Mailcow platform.
I actually do use SOGo and in my opinion and for my use-cases it's the best solution, much much more than Roundcube. I've set it up for a ~15 companies and so far so good.
There were also some which didn't like the SOGo and they had their reasons, thankfully the Mailcow platform is not dependent on the SOGo to work, so all I did was disabled SOGo for them and setup a Roundcube instance. that was it! it took me around 15mins.
It's really not too complicated to do so, and to be honest, most of the companies in Germany (as far as I learned) prefer to use SOGo instead of Roundcube.
Hope you can do well with changing from SOGo to RC :)

**Comment by hesoyam1123** [comment]
for anyone who want to find answer about theming mailcow-dockerized:
https://docs.mailcow.email/manual-guides/SOGo/u_e-sogo/#apply-custom-sogo-theme
