### ISSUE TITLE
Multiple IPs?

### ISSUE THREAD

**Issue by itsbhanusharma** [mailcow/mailcow-dockerized#2157]
I can't quite figure this out yet, I kinda want to attach more than 1 Public IP (maybe 2 or 3) primarily to dedicated an IP to a domain on our server particularly known to send too much of internal/external emails. 

Server has enough horsepower but I'm kinda paranoid of domain reputation so I just want to be safer than sorry. 

What I want is to one particular domain have some sort of 'special' MX record or internal assignment so that all of their mails are routed to that IP (which we can move to a different server at our disposal in future if required) 

The big question here is that how mailcow knows the public IP of a server and how it decides which IP to use for communication and if it is okay to just enroll multiple A records under the same hostname to introduce redundancy?

**Comment by mkuron** [comment]
For incoming connections, Mailcow doesn‘t care about the IP and will happily accept multiple IPs. For incoming purposes, IPs are not considered to have something like a reputation, so you can just use the same MX record on all domains.

For outgoing connections, Mailcow will use the default route, but you can force a specific IP address using the `SNAT_TO_SOURCE` configuration variable. Note that there is no way to use different outgoing IPs for different domains.

**Comment by itsbhanusharma** [comment]
Oh!

That's sad. But will see maybe deploying another mailcow is the only safe option in such case.

**Comment by mkuron** [comment]
Duplicate of #1273. With some slightly complex configuration, Postfix is actually capable of this kind of thing (https://serverfault.com/questions/92181/how-to-make-postfix-use-another-ip-address/436703#436703), but that kind of solution won't work inside Docker. Multiple Mailcows would certainly work though.

It's not a very commonly used scenario however; if you think you need multiple IP addresses, you should really think about whether you do actually need them. Most corporations, ISPs and email service providers are using just one IP per mail server, often shared by tens of thousands of users. The one use of multiple IPs that I can think of is to have one for sending out mass mailings (spam) and one for "serious" communication, but Mailcow obviously does not condone spamming.

**Comment by strarsis** [comment]
@mkuron: Let's Encrypt SAN limit (for one IP address) is currently 100. So a mailcow server with one public IP address can have about 50 domains (2 for each host, autodiscover.* and autoconfig.*), if autoconfiguration should work properly (autoconfiguration requires working HTTPS, otherwise the client won't accept the answer and at least show some scary invalid certificate error, also security would be worse here). If "vanity" addresses should also be used (e.g. mail.that-domain.tld instead of one single mail.primary-host.tld), then number of domains would be further split into a third, to around 33.

When multiple public IP addresses can be used, this should be scalable to a much larger amount of domains.
Could I add a 2nd public IP address to that mail server and then make the mailcow ACME client generate and Let's Encrypt certificates that have 100 SANs each?

**Comment by DipenduDas73** [comment]
Multiple IPs are needed for actual server to run without server downtime

**Comment by strarsis** [comment]
> Multiple IPs are needed for actual server to run without server downtime

Ah, so two mailcow instances can run with 
an IP address each? As primary and secondary MX?

**Comment by DipenduDas73** [comment]
yeah then two instances needed to setup right, if one instance could handle more than one public IP then that instance could handle to send email without server downtime if one IP's ISP would be off it could send mail from another IP, in my server setup, I am using multi wan, but one of my IP is detected by mail server and another public IP not showing.
