### ISSUE TITLE
Activesync Hangs on large mailboxes in Outlook 2016

### ISSUE THREAD

**Issue by kallenp** [mailcow/mailcow-dockerized#2206]
Activesync Hangs on large mailboxes in Outlook. 
Problem is only in Outlook 2016. Outlook says that all folders are downloaded, but the data in some folders are missing. In the webmail everything is OK. Other clients like macOS, iOS, emClient, have no problem. 

**Problem is similiar to this**
https://github.com/mailcow/mailcow-dockerized/issues/783
https://forum.iredmail.org/topic10785-iredmail-support-sogo-problem-with-activesync-outlook-2016.html

![screenshot 2019-01-20 at 18 37 46](https://user-images.githubusercontent.com/26544218/51442979-2c6cea00-1ce3-11e9-88d8-3793cd0a31fc.png)

Please, can I ask for a help howto fix this problem ? 
Any idea howto solve it and make it work ? 

Thanks,
Petr

**Comment by ssm3e30** [comment]
+1 I have the same issue, however its not just for large mailboxes. I have 4 mailboxes connected from Outlook 2016 to my Mailcow instance, and have this issue with only 1 of the mailboxes. The mailbox with this problem is not the largest of the 4. Checked the SOGo logs the only difference is the mailbox experience issues has this log entry:

[829]: <0x0x56401d24f1c0[SOGoActiveSyncDispatcher]> Cache cleanup needed for device EE81C35297D34E36B324A0554E265BDF

Not sure its related. I have tried restarting the SOGo container, clearing the cache in Outlook and expanding the number of SOGo workers to no avail. 

Edit: Oh another data point that might help. Sending mail from from the mailbox using Outlook works fine, this issue seems to be only in regards to syncing folders (inbox, sent mail). The status indicator at the bottom of Outlook continually fluctuates between "All folders up to date" and "Waiting for server response".

**Comment by andryyy** [comment]
Clearing the EAS cache is what this message is about. Nothing related to Outlook. :)

Furthermore you need to try other Response- and WindowSize values in sogo.conf. You could even comment both values out and try again after cleaning the EAS cache.

I recommend not to use Outlook with EAS on a desktop. Cannot say that too often. So many better clients are available. emClient works really nice for example.

**Comment by kallenp** [comment]
I try everything what andryyy wrote, but the problem is still present and the problem is only with one big size mailbox (7.2 GB). 

I found this two links...
https://sogo.nu/files/docs/SOGoInstallationGuide.html#_microsoft_enterprise_activesync_tuning
http://docs.nethserver.org/en/v7/sogo.html

I will try their recommendations this night.

**Comment by andryyy** [comment]
Our sync interval is already that large.

Check with SOGo support for a msg that cannot be parsed.
