### ISSUE TITLE
Access through haproxy(pfsense)

### ISSUE THREAD

**Issue by RudySixOw** [mailcow/mailcow-dockerized#2221]
Hi, 
I try to access from internet to my mailcow-dockerized behind haproxy on pfsense.
haproxy redirect http(80) to https(443) and do SSL Offloading.
All websites like nextcloud works but not mailcow. In my LAN everything works.

PS: I use haproxy just for the web(sogo, dav, mailcowui ...) at this time :)

Thanks in advance.

**Comment by andryyy** [comment]
That’s not enough info. You should post all config sat least. And describe the problem. :)

Do you copy the certificate to mailcow? Not relevant for this issue, but relevant for your mailcow.

**Comment by RudySixOw** [comment]
Thanks, 
Yes I copy my cert(letsencrypt) into /opt/mailcow-dockerized/ and thats works in local, I can see the good cert. But when I try to connect from net I have connection timeout. I see this on nginx log :+1: 
"OPTIONS / HTTP/1.0" 405 150 "-" "-"
If you want more info ask me. Sorry for my english, i'm french.

**Comment by asifbacchus** [comment]
Need to see your HAproxy configuration, as @andryyy said.  Right off the bat, it seems like it may be misconfigured since you said you are redirecting port 80 (HTTP) to 443 (HTTPS) and offloading SSL.  No browser will be expecting an SSL session on port 80.  Therefore, the browser will be expecting unencrypted traffic but your server behind the proxy will be supplying encrypted traffic which is bound to cause problems.  Unless I misunderstood?

**Comment by RudySixOw** [comment]
HAPROXY
frontend http-to-https
        bind                    xxx.xxx.xxx.xxx:80 name xxx.xxx.xxx.xxx :80   
        mode                    http
        log                     global
        option                  http-keep-alive
        timeout client          30000
        http-request redirect scheme https


backend Mail_ipvANY
        mode                    http
        id                      104
        log                     global
        timeout connect         30000
        timeout server          30000
        retries                 3
        option                  httpchk OPTIONS / 
        server                 mail 1xxx.xxx.xxx.xxx:8443 id 105 ssl check inter 1000  verify none


MAILCOW
# ------------------------------
# HTTP/S Bindings
# ------------------------------

# You should use HTTPS, but in case of SSL offloaded reverse proxies:
HTTP_PORT=8585
HTTP_BIND=0.0.0.0

HTTPS_PORT=8443
HTTPS_BIND=0.0.0.0

**Comment by andryyy** [comment]
You should check your firewall when connections from outside fail but internal works. OO

Also set the correct headers. Or does HAProxy set forwarded headers automatically?

**Comment by RudySixOw** [comment]
when i look tcpdump under mailcow i see :+1: 
17:41:41.382070 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 569)
    pfSense24462 > mailcow.8443: Flags [P.], cksum 0x3fd4 (correct), seq 1:518, ack 1, win 513, options [nop,nop,TS val 21543473 ecr 221781426], length 517
17:41:41.382100 IP (tos 0x0, ttl 63, id 37658, offset 0, flags [DF], proto TCP (6), length 52)
    mailcow.8443 > pfSense.24462: Flags [.], cksum 0x7d59 (incorrect -> 0x3cb7), seq 1, ack 518, win 235, options [nop,nop,TS val 221781426 ecr 21543473], length 0

And on browser :+1: 
503 Service Unavailable
No server is available to handle this request.

**Comment by andryyy** [comment]
PHP logs?

**Comment by RudySixOw** [comment]
php-fpm-mailcow_1    | xxx.xxx.xxx.xxx -  21/Jan/2019:22:37:55 +0100 "GET /forwardinghosts.php" 200
php-fpm-mailcow_1    | xxx.xxx.xxx.xxx -  21/Jan/2019:22:38:38 +0100 "HEAD /settings.php" 200
php-fpm-mailcow_1    | xxx.xxx.xxx.xxx-  21/Jan/2019:22:38:38 +0100 "GET /settings.php" 200
php-fpm-mailcow_1    | xxx.xxx.xxx.xxx -  21/Jan/2019:22:38:41 +0100 "HEAD /forwardinghosts.php" 200

nginx-mailcow_1      | xxx.xxx.xxx.xxx - - [26/Jan/2019:17:47:43 +0100] "HEAD /forwardinghosts.php HTTP/1.1" 200 0 "-" "-"
nginx-mailcow_1      | xxx.xxx.xxx.xxx - - [26/Jan/2019:17:47:43 +0100] "GET /forwardinghosts.php HTTP/1.1" 200 27 "-" "-"
nginx-mailcow_1      | xxx.xxx.xxx.xxx - - [26/Jan/2019:17:47:44 +0100] "OPTIONS / HTTP/1.0" 405 150 "-" "-"
nginx-mailcow_1      | xxx.xxx.xxx.xxx - - [26/Jan/2019:17:47:44 +0100] "HEAD /settings.php HTTP/1.1" 200 0 "-" "-"
nginx-mailcow_1      | xxx.xxx.xxx.xxx - - [26/Jan/2019:17:47:44 +0100] "GET /settings.php HTTP/1.1" 200 9225 "-" "-"
nginx-mailcow_1      | xxx.xxx.xxx.xxx - - [26/Jan/2019:17:47:45 +0100] "OPTIONS / HTTP/1.0" 405 150 "-" "-"
nginx-mailcow_1      | xxx.xxx.xxx.xxx - - [26/Jan/2019:17:47:46 +0100] "OPTIONS / HTTP/1.0" 405 150 "-" "-"

**Comment by andryyy** [comment]
HAProxy does not pass anything to your mailcow.

**Comment by asifbacchus** [comment]
You are doing this on a pfSense system, correct?  I'm assuming you are using the GUI?  If so, I will spin up a VM and try to duplicate what you are doing then post my settings here assuming I get it to work.  Might take me a little time to cobble that all together though.  Just do me a favour and confirm I understand what you are trying to do:

pfSense w/ HAproxy acting as a reverse proxy to access Mailcow admin panel and SOGo/DAV? Using one domain for everything (e.g. mail.myserver.net and mail.myserver.net/SOGo)?  You are not trying to port forward or anything, right? Just want port 80 to redirect to your Mailcow with SSL offloaded to HAproxy, correct?

**Comment by andryyy** [comment]
Thank you. :)

**Comment by RudySixOw** [comment]
We can see that the frames return well on mailcow but do not come out.
 You're right, i want to connect on my admin panel , sogo and webdav for sync caldav and carddav.

**Comment by asifbacchus** [comment]
Is that your complete haproxy setup? Because you have a redirect for HTTP > HTTPS but don't actually have a proxy rule on the front-end. You need both. Plus firewall rules. Check those for me. In the meantime, I got it working on my VM so I'll start preparing screenshots and stuff to post here but that will take me at least 15 minutes.

Cheers.

**Comment by RudySixOw** [comment]
thank you very much for the time spent

**Comment by RudySixOw** [comment]
i forgot that:

frontend Sites
        bind                    xxx.xxx.xxx.xxx:443 name xxx.xxx.xxx.xxx:443   ssl crt-list /var/etc/haproxy/Sites-Sixow.crt_list  
        mode                    http
        log                     global
        option                  http-keep-alive
        option                  forwardfor
        acl https ssl_fc
        http-request set-header         X-Forwarded-Proto http if !https
        http-request set-header         X-Forwarded-Proto https if https
        timeout client          30000
   
        acl                     webmail var(txn.txnhost) -m end -i webmail.domain.com



        use_backend Mail_ipvANY  if  webmail aclcrt_Sites

**Comment by asifbacchus** [comment]
Ok, I'll try to keep this short, but there's a lot of steps.  I'm also going to try screenshots, hopefully they attach properly and it all works out.  Please note, this is a VERY basic and not polished setup, it's just to illustrate the proper settings... or at least, settings that worked for me on a quickly slapped together VM network.  For reference, I set things up with pfSense on one machine and mailcow on another machine, but I think it should be a pretty similar setup on the same machine, you'd just have to really watch your IP bindings and references.

Ok, you already have HAproxy set up. So go to the settings. Make sure you enable HAProxy :-)  Also, under "Tuning" change the "Max SSL Diffie-Hellman size" to at least 2048 or 4096 depending on how powerful a server you have.  Otherwise, you'll get an annoying warning constantly.

Go to the backend.  Create a new one.  Give the backend a name.  Then add a server.  Give it a name, set it to active, select "Address+Port", fill in the address and port as relevant to your set up.
![02-backend-01](https://user-images.githubusercontent.com/10538275/51792048-6d448300-2169-11e9-84d7-de433048bd17.PNG)  Scroll down to "Health checking".  Set "Health check method" to "Basic" or "None" for now.  If you want to use HTTP you'll have to get @andryyy to help you with the parameters since I don't know what kind of headers Mailcow generates and I'm too lazy to check :-)  
![02-backend-02](https://user-images.githubusercontent.com/10538275/51792064-99f89a80-2169-11e9-9a56-0da130e89014.PNG).  Save the backend.

Ok, go to the Frontend and add a new one.  Give it a name, then under "External Addresses" choose your WAN address and port 443.  Check "SSL Offloading".  Set the "Type" to "http / https(offloading)". 
![03-frontend-01](https://user-images.githubusercontent.com/10538275/51792089-ddeb9f80-2169-11e9-9f91-c30c3bd3af3f.PNG).  Create a new ACL and name it, "Expression" should be "Host matches:" and the value should be your external domain name.  Under Actions, choose "Use Backend", reference the ACL you just created and select the backend you made in the last step.  No default backend.
![03-frontend-02](https://user-images.githubusercontent.com/10538275/51792106-0d021100-216a-11e9-8742-9627169760cd.PNG).  Set "Use 'forwardfor' and any other proxy headers you think you need in the "Advanced settings" section.  
![03-frontend-03](https://user-images.githubusercontent.com/10538275/51792111-2c993980-216a-11e9-8ecb-bf761260906a.PNG).  Under "SSL Offloading" choose the appropriate certificate and check BOTH boxes ("Add ACL for certificate CommonName..." and "Add ACL for certificate Subject Alternative Names").  Save this Frontend.

Create a new Frontend.  Name it something like "redirectHTTPS" or whatever you like.  External Address is your WAN address, port 80.  Type: http / https(offloading).
![04-redirect-01](https://user-images.githubusercontent.com/10538275/51792123-6e29e480-216a-11e9-8037-804563d082a5.PNG).  Under actions:  Action: "http-request redirect" then fill-in rule: "scheme https".  
![04-redirect-02](https://user-images.githubusercontent.com/10538275/51792131-8b5eb300-216a-11e9-9496-64df53ad887c.PNG).  Save it.

Your Frontend rules should look like this: 
![05-frontends](https://user-images.githubusercontent.com/10538275/51792132-99143880-216a-11e9-9254-97b8c17a445b.PNG)

Finally:  Go to your Firewall > Rules and create the following two rules:  
![06-firewall](https://user-images.githubusercontent.com/10538275/51792136-a92c1800-216a-11e9-8724-89ae0fe7b860.PNG)

For reference, they are:

1. TCP, source any port any destination "This Firewall" port 80 (HTTP inbound)
2. TCP source any port any destination "This Firewall" port 443 (HTTPS inbound)

Save your configuration.  Give your services a restart to be sure.  Should be working for you :-)

Assuming it's all good, you'll want to do some research and update the allowed ciphers to increase the security since the default HAProxy settings are a little too liberal in accepting older ciphers (like TLS 1.0, etc.)

Hope that helps... let me know if you need anything else.  Good luck!

**Comment by RudySixOw** [comment]
Thanks  for everything. Thanks to you I was able to identify the error. It was: Scroll down to "Health checking". Set "Health check method" to "Basic" or "None". I did not understand why but when it is in HTTP it does not work.
Thanks again, all I have left is my sieve problem (require "vnd.dovecot.filter";).
