### ISSUE TITLE
SoGo Native Outlook Compatibility

### ISSUE THREAD

**Issue by Braintelligence** [mailcow/mailcow-dockerized#223]
Hi there 😸.
Just to clarify: Is the SoGo native outlook compatibility given per https://sogo.nu/files/docs/SOGoNativeOutlookConfigurationGuide.html#_about_this_guide or not?

**Comment by mkuron** [comment]
It's not currently supported because that requires an Active Directory/LDAP backend for authentication.

**Comment by Braintelligence** [comment]
@mkuron If I understand the guide correctly, a Samba4 backend is good enough, as well.

**Comment by mkuron** [comment]
That doesn't make a difference. Samba implements the Active Directory protocol, which in turn is a superset of LDAP. Samba cannot use the current MySQL database as authentication backend and the password hashes stored there couldn't be migrated into Samba either due to different hashing methods.

Furthermore, OpenChange, the library used by SOGo for Outlook communication, appears to be essentially dead (https://github.com/openchange/openchange/), and even its most popular fork (https://github.com/zentyal/openchange/) hasn't been updated in a year. It seems like it isn't even needed anymore as Outlook 2013 and 2016 support Exchange ActiveSync, which SOGo on Mailcow supports for mobile device syncing.

**Comment by Braintelligence** [comment]
I see, but does delegating and the other sogo features work over ActiveSync?

**Comment by andryyy** [comment]
Openchange is dead, there is no way we should implement it. :)

**Comment by Braintelligence** [comment]
That's alright but does Outlook support SoGo features like delegation and free/busy? :)

**Comment by andryyy** [comment]
At least free/busy. You can find here https://sogo.nu/files/docs/SOGoInstallationGuide.html#_microsoft_enterprise_activesync :)

**Comment by Braintelligence** [comment]
Thanks for clarifying! Looks like 2016 supports it better, good to know!
