### ISSUE TITLE
SMPT Server offline

### ISSUE THREAD

**Issue by YourGameSpace** [mailcow/mailcow-dockerized#2238]
Hey, wo ist hier das Problem? Es wurde nichts verändert etc. und jetzt erscheint dieses Problem..
Es kommen auch keine E-Mails mehr rein..

http://prntscr.com/mddcrd

Bitte um Hilfe!

LG TUBEOF

**Comment by YourGameSpace** [comment]
Hey, where is the problem? Nothing was changed etc. and now this problem appears ..
There are no more emails coming in ..

http://prntscr.com/mddcrd

Please help!

LG TUBEOF

**Comment by Conan179** [comment]
**Notice (you can delete this paragraph)**
Please understand that we use GitHub as **bug tracker and for feature requests only**.
For general (community) support and other discussion, you are welcome to visit us @ Freenode, #mailcow
Answering may take from a few seconds to hours, please be patient. :-)
Immediate commercial support is available via info@servercow.de

**Describe the bug**
A clear and concise description of what the bug is.

**How to reproduce Reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
1. ....
2. ....
3. ....

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Logs**
Please take a look at the [documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

**System**
 - OS: [e.g. iOS]
 - Browser: [e.g. chrome, safari]
 - Other clients involved:

**Additional context**
Add any other context about the problem here.

**Comment by andryyy** [comment]
Yes, we need at least some logs. Postfix for example. Are all containers up and running?

Start `docker-compose logs -f --tail=1 postfix-mailcow`, try to mail, stop docker-compose logs and paste the output somewhere, please.
