### ISSUE TITLE
G-Suite Split Delivery is being rejected

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#2390]
**Steps to reproduce**

- Setup G-Suite Split Delivery (example shown [here](https://mediatemple.net/community/products/dv/211978166/g-suite-split-delivery))
- Setup a basic mailcow instance
- Add your domain to mailcow
- Create a test mailbox
- Send an email from mailcow to your G-Suite mailbox
- Send an email from G-Suite to your mailcow mailbox

**Logs**
postfix-mailcow: https://pastebin.com/tvrvd2YF
G-Suite: [LogSearchResults-20190302-2338](https://docs.google.com/spreadsheets/d/1iQi2MikQK6me4bNRtqxZYyvYdudnDaISuCbSFLfbBqI/edit?usp=sharing)

**Expected**
Send emails from mailcow to another mail server running on the same domain.
Receive emails from another mail server running on the same domain to mailcow.

**Reality**
mailcow is rejecting both outgoing and ingoing emails from third-party mail server if they're meeting certain conditions, such as running on the same domain.

**Comment by andryyy** [comment]
I don't think I understand this issue.

Please try to only post relevant logs, we don't need solr-mailcow or sogo-mailcow logs etc. for a routing problem. :)

What I understand and see is, that Google wants to relay a mail to your server and it gets a "relay access denied".

You should, first of all, reset all Postfix configs to default and post postfix-mailcow logs again.

**Comment by ghost** [comment]
I hope it's now more understandable what I want to do. @andryyy

**Comment by ghost** [comment]
Related issues:

- #380
- #396

**Comment by andryyy** [comment]
You could try to use transport maps to force a route for some users. But these users must exist in mailcow nevertheless. You’d need to create dummies to make mailcow accept them as recipient.

If it fails, you can try to mark the domain as relay domain and THEN add transport map entries like “domain.tld smtp:gmailbla” to route all unknown users, and “user@domain virtual:” to route users locally. This needs to be set in a transport map outside of mailcow UI, because we only support “smtp:” transports there. My previous idea could be implemented in mailcow UI.

**Comment by Ric878** [comment]
@PublicByte Were you able to get this resolved. I am having a very similar problem, except I am using O365. I can get email to come into O365, and accepted on mailcow, but I cannot send from mailcow to users that are in O365 as it does a local lookup first and then rejects it.

I can get it to work if I use transport maps in the mailcow ui, but as @andryyy  mentioned, I have to create a dummy user for each user in O365 which is tedious. Any luck with an easier approach?

**Comment by ghost** [comment]
I was unable to solve the problem.
