### ISSUE TITLE
Auto File Attachments to Server Location

### ISSUE THREAD

**Issue by ssm3e30** [mailcow/mailcow-dockerized#2414]
**Is your feature request related to a problem? Please describe.**
Hi everyone, this is less of a feature request more of understanding how MailCow handles attachments.

**Describe the solution you'd like**
What I want to know is would it be possible to have the attachments sent to a specific mailbox be filed in a specific location on the server? This is an attempt to automate the filling of receipts that are usually sent as a PDF.

For example:
User sends email with receipt to MAILBOX -> Attachment is stripped and moved to another folder on the server

I don't think filters can achieve this. I was thinking an Rsync of that specific mailboxes attachments but could not find where attachments are stored.

**Additional context**
Add any other context or screenshots about the feature request here or remove this section

**Comment by andryyy** [comment]
This would work with mdbox (for example) which I’m not planning to use at the moment. A switch to use it by default exsists, but is not yet fully implemented.

**Comment by extremeshok** [comment]
this is already being used on our production servers with mdbox+sis+lz4
#1007

with millions of messages and attachments ;P

To convert your existing setup to mdbox and sis is not an easy task and there is a very high potential of nuking your mail folders or causing permanent corruption to the indexes. Currently not going to submit a PR with the conversion script, can just imagine the flood of negative issues caused by blindly doing the conversion.

**Comment by ssm3e30** [comment]
Ok thanks for the replies! I am in no rush and would prefer to keep the current stability vs experimenting with switching to mdbox. However I might spin up a separate VPS just to try if I find the time :)
