### ISSUE TITLE
Updating lots of changes.

### ISSUE THREAD

**Issue by Hickstead** [mailcow/mailcow-dockerized#2465]
In my cow I have made many changes and added new options, not knowing how to best update them with a new code on GitHub, without break other users who will have this issue how will fix it.

Thank.

**Comment by Braintelligence** [comment]
So what's your question, exactly?

**Comment by andryyy** [comment]
As long as the changes are useful, TESTED AND DOCUMENTED and not hacky or dangerous, we can merge them.

**Comment by Hickstead** [comment]
I;ve areada ask my question.

**Comment by Braintelligence** [comment]
You just stated that you don't know 
> how to best update them with a new code on GitHub, without break other users who will have this issue how will fix it

that's not a question; it's a statement.

If your question is how to actually do this it would help to know how much experience with git-based development you have, so we can better assess on where to start explaining. If you've got enough experience andryyy's comment should help you out.

**Comment by Hickstead** [comment]
i don't think you underztond

**Comment by Braintelligence** [comment]
Ok, @andryyy can help you out; he's the maintainer 😸.

**Comment by Braintelligence** [comment]
Actually, if you made changes to the code itself there should be an open repo (or otherwise publicly available current version of the code) of this per the license of this project. Where can we inspect this code? I see no open repositories under your GitHub account.

**Comment by K2rool** [comment]
I think he asking how to update Mailcow if you have done lots of changes to the code, I might wrong don't want to sound rude but there seem to be a bit of language barrier.

**Comment by Braintelligence** [comment]
@K2rool Oooh, ok. Well, as long as only configuration stuff is involved, there should be no issue updating, I think. (You should always backup anyway.) If functionality was added, he is bound by the license to make his code publicly available, though. I can't speak for @andryyy but in his stead I wouldn't want to support anyone who is violating the license.

**Comment by Hickstead** [comment]
Did ./update.sh it stoped working

**Comment by Braintelligence** [comment]
This is the point in time where you save the logs of the update,restore your backup and show us what the logs say. Though I don't know if anyone might want to help you as long as you're violating the license.

**Comment by Hickstead** [comment]
modilfy to rspamd scores i did

**Comment by Braintelligence** [comment]
I don't think this should break anything, but we still can't help without some diagnostic output... Follow the issue template and if you think your rspamd scores make more sense you should create a PR.

**Comment by K2rool** [comment]
@Braintelligence I don't think adding new functionality to Mailcow would count as a license violation even if they don't release the code as long as they are not distributing it.

**Comment by mkuron** [comment]
> Though I don't know if anyone might want to help you as long as you're violating the license.

Please stop claiming that @Hickstead violates the license. He's most likely not doing that. Simple stuff like the Dockerfiles and configurations is too trivial to be copyrightable, so the license mainly applies to  the scripts, web UI, etc. Besides that, the GPLv3 only requires you to provide the code if you _redistribute_ the software (e.g. if someone started selling Mailcow for other people to run on their own servers), not if you are only _running_ it (either for your own use or as a hosting company that provides managed Mailcow instances). This is different from the AGPLv3, which, for example, requires you to provide the code as soon as you are allowing someone to use the software over the network.

> I;ve areada ask my question.

These kinds of comments indeed do not help. Please provide a full explanation of your problem and all relevant logs. When you created a new issue, the template actually asked you to do precisely that.

**Comment by Hickstead** [comment]
all fixed

**Comment by andryyy** [comment]
Huh. :) Okay. Thought he wants to contribute code.

**Comment by Braintelligence** [comment]
@K2rool @mkuron As stated in https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)

> You may copy, distribute and modify the software as long as you track changes/dates in source files. Any modifications to or software including (via compiler) GPL-licensed code must also be made available under the GPL along with build & install instructions.

There is no mention that you don't need to make the code available after a modification of the code if you're only using it for yourself. Actually it suggests otherwise.

That's why I didn't ever dig further into this. On the other hand we have this: https://www.gnu.org/licenses/gpl-faq.html#GPLRequireSourcePostedPublic

> But if you release the modified version to the public in some way, the GPL requires you to make the modified source code available to the program's users, under the GPL.

Releasing means "conveying" here, as per the GPL:
https://github.com/mailcow/mailcow-dockerized/blob/master/LICENSE#L99

So actually you're 
>~~right. If I provide mailcow as a service to customers and change the code I don't have to make the source code available as long as I do not enable other parties to access or copy the code. Only user interaction would be provided then, as it is allowed. That's propably why MongoDB created their new license model, too.~~ 

wrong.

We have JavaScript as part of this repo. And now see this: https://www.gnu.org/philosophy/javascript-trap.html
Since we use Ajax calls the javascript part of the code is explicitly considered **NOT** to be trivial as per the link provided.

Since you're making part of the GPL code available directly to the public just by visiting the mailcow site, you WILL have to disclose any changes to the code IMHO. Correct me with a reliable source please, if I missed something.

I'm now even more confused about @andryyy's comment here https://github.com/mailcow/mailcow-dockerized/issues/693#issuecomment-424683277 though 😖.

EDIT: Here's someone who made a whole read-up on this and basically confirms what I said, with the difference of considering the JavaScript portion of the code as its own program if the server-side code is not GPLd (which it is and also belongs to the same project in our case...): http://greendrake.info/#nfy0|a=distr

**Comment by K2rool** [comment]
I don't think andryyy care if someone modify or add stuff to Mailcow unless they are posting screenshot or asking for help to fix issue caused by their modification. Even if andryyy did wanted ever bit of code from a user that  modified their Mailcow install it not like he's going to even know about it unless the person messages him saying I've modified your code you want a copy.

**Comment by Braintelligence** [comment]
That's why I mentioned https://github.com/mailcow/mailcow-dockerized/issues/693#issuecomment-424683277 where he actually asked for it.

**Comment by Hickstead** [comment]
I have close why still messageing

**Comment by K2rool** [comment]
Did anyone teach you manners if allof (header :contains "X-GitHub-Sender" "Hickstead") { discard; } that shoud keep my inbox clear of you.

**Comment by hachre** [comment]
I'm willing to believe there was a big language-barrier problem (maybe auto translate) and all the talk of violating licenses may have scared Hickstead, so his comment about still messaging may not have been meant the way it came across. 👍

**Comment by Braintelligence** [comment]
Sorry, didn't want to scare anyone or get offtopicky. :(
I'd be happy if anyone could cite something that disproves what I found out, though, just for clarity, because that's how I always interpreted Mailcow to behave in context of GPL. :+1:

**Comment by mkuron** [comment]
Your interpretation is probably a bit strict, @Braintelligence. Commonly one only insists on publishing the source code if someone provides (usually by selling) the software to someone else to run on their own computer. So all internal use is not affected, and neither is use in a hosted environment.

It's unclear to me whether the redistribution of the JS code also requires the publication of modifications to the server-side code. My guess is no (as the license also applies to each file individually, one can redistribute them individually), but that question can basically only be answered by a lawyer.

I already locked this discussion, but since you are team members, you can continue commenting here. I just ask that we stick to the actual technical questions instead of discussing nitpicky licensing details that none of us is an expert on.

**Comment by Braintelligence** [comment]
Agreed. Thanks for clarifying. :+1:
