### ISSUE TITLE
ERROR: Network "mailcowdockerized_mailcow-network" needs to be recreated - option "com.docker.network.bridge.name" has changed

### ISSUE THREAD

**Issue by RudySixOw** [mailcow/mailcow-dockerized#2510]
Hello,
I have a problem after an update.

I have this message:
ERROR: Network "mailcowdockerized_mailcow-network" needs to be recreated - option "com.docker.network.bridge.name" has changed

So nothing starts.

I tried to remove with: docker network rm mailcowdockerized_mailcow-network

Error response from daemon: error while removing network: network mailcowdockerized_mailcow-network id 90e179d2f9e95a07289a0ba4c8cb6374608756b40c94c938266d61a43726379a has active endpoints

I turn in a loop and my system is planted.

Thank you in advance.

**Comment by MAGICCC** [comment]
Already tried
```
docker-compose down
docker-compose up -d
```

**Comment by RudySixOw** [comment]
I did but not work

root@mail:/opt/mailcow-dockerized# docker-compose down
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
Removing network mailcowdockerized_mailcow-network
ERROR: error while removing network: network mailcowdockerized_mailcow-network id 90e179d2f9e95a07289a0ba4c8cb6374608756b40c94c938266d61a43726379a has active endpoints

**Comment by hachre** [comment]
```
docker-compose down
systemctl restart docker
docker-compose down
docker-compose up -d
```

Seems docker has hung up...

**Comment by RudySixOw** [comment]
not work

**Comment by hachre** [comment]
Reboot the entire machine...

**Comment by RudySixOw** [comment]
I find th e solution:
root@mail:/opt/mailcow-dockerized# docker network disconnect mailcowdockerized_mailcow-network mailcow-dockerized_clamd-mailcow_2
root@mail:/opt/mailcow-dockerized# docker network disconnect mailcowdockerized_mailcow-network mailcow-dockerized_memcached-mailcow_2
root@mail:/opt/mailcow-dockerized# docker network disconnect mailcowdockerized_mailcow-network mailcow-dockerized_solr-mailcow_2
root@mail:/opt/mailcow-dockerized# docker network disconnect mailcowdockerized_mailcow-network mailcow-dockerized_dockerapi-mailcow_2
root@mail:/opt/mailcow-dockerized# docker network disconnect mailcowdockerized_mailcow-network mailcow-dockerized_watchdog-mailcow_2

docker network rm mailcowdockerized_mailcow-network

after 
docker-compose up -d

**Comment by GrantZero** [comment]
Hi there,
i have updated my system since a hour.
I have the same problem.
`Removing network mailcowdockerized_mailcow-network
ERROR: error while removing network: network mailcowdockerized_mailcow-network id 1eccb40d03efb59b1b277a32d9cfe9a365cdd5f73188aa62ea981c63195c464d has active endpoints
`
The solutions form @RudySixOw and @hachre don't work.

**Comment by je-s** [comment]
I'm using Mailcow behind a Traefik reverse proxy, and after a recent update (and some changes to my Mailcow configuration) I ran into the same error.

Since all the above didn't work, I have found another solution:
In case you're using a compose-file with a service (in my case Traefik) where you want to connect to and hence alias `mailcowdockerized_mailcow-network`, you need to state that the network is external (namely: it already has been created; `external: true`):
```
networks:
  proxy:
    name: traefik-proxy
  mailcow-network:
    name: mailcowdockerized_mailcow-network
    external: true
```

I suppose that [this](https://github.com/mailcow/mailcow-dockerized/commit/40dda01d917578381a4c014e16eb1b5c43b823c9) update caused the problem. My Mailcow configuration was untouched for quite a long time now, and I suppose the network has never been updated/recreated since then. And now that I've recreated it once, it started conflicting with my Traefik compose-file, because the bridge names started interfering with each other. After defining the network in my Traefik compose-file as external the error vanished and I could start again without any problems.

This should apply analogously to all similar cases as well. :)

**Comment by hcouplet** [comment]
@je-s you saved my life.   Around end of 2024, network changed from mailcow-network to mailcowdockerized_mailcow-network.  As I didn't notice php could not connect to mysql, acme has no connection to nginx and cert were not update.  I kept an old releasea.  

I am also using an external network and updated the name, restarted and not it works with the latest version.

Here is my create network script : 

SUBNET=172.21.0.0/16
EXTERNAL_IP=5.196.125.70
DK_NAME="mailcowdockerized_mailcow-network"
IF_NAME="dk-mailcow"

docker network create --driver bridge ${DK_NAME} \
    --subnet=${SUBNET} \
    -o "com.docker.network.bridge.name=${IF_NAME}" \
    -o "com.docker.network.bridge.enable_ip_masquerade=false" \
    -o "com.docker.network.bridge.host_binding_ipv4=${EXTERNAL_IP}"

Also updated my docker-compose.override.yml to : 
networks:
  mailcow-network:
    external: true
    name: mailcowdockerized_mailcow-network

**Comment by DubbaThony** [comment]
Ive stumbbled uppon similar issue today, that required some `docker network disconnect`
Since it was first search result, for completeness and anyone who stumbles upon this in future

Put mailcow down:
`docker compose down`
Check to know which things to disconnect:
`docker network inspect mailcowdockerized_mailcow-network`
and
`docker network inspect host`
In `host` network you may have other docker things, for me it also contained mailcow netfilter, which I had to remove too.
In the output there are endpoints with name, ex. `mailcowdockerized-rspamd-mailcow-1` in `.Containers.{hash of container}.Name`, these names are what you are intrested in. For items in first command, for all of them:
`docker network disconnect --force mailcowdockerized_mailcow-network <name>`
for second one, only items starting with `mailcowdockerized`:
`docker network disconnect --force host <name>`
And finally:
`docker network rm mailcowdockerized_mailcow-network`

After that docker compose up -d should work. For me it wasn't obvious there is dangling connection to host network.
