### ISSUE TITLE
lets encrypt, cannot add domain

### ISSUE THREAD

**Issue by LordOfTheRams** [mailcow/mailcow-dockerized#2579]
Hi!
I have a fresh installation of mailcow. After running it for a few days I saw some strange messages in the acme service log. Seems like it is trying to register some domains that I added. After first install everything was perfectly registered, but now there is something wrong. I have no Reverse Proxy and Port 80 is forwarded by the firewall. I cannot see what is wrong here. 

How can I debug this?

```
acme-mailcow_1       | Sun May  5 21:57:34 CEST 2019 - Found A record for mail.gefi.at: 80.120.176.44
acme-mailcow_1       | Sun May  5 21:57:34 CEST 2019 - Confirmed A record 80.120.176.44, but HTTP validation failed
acme-mailcow_1       | Sun May  5 21:57:34 CEST 2019 - Found A record for smtp.gefi.at: 80.120.176.44
acme-mailcow_1       | Sun May  5 21:57:34 CEST 2019 - Confirmed A record 80.120.176.44, but HTTP validation failed
```

**Comment by andryyy** [comment]
It cannot connect from the mailcow-br (bridge) to your external interface. Fix that or disable ufw/firewalld. 

You'd need to stop and disable the fw service, stop mailcow, stop Docker, start Docker and start mailcow.

Make sure your firewall does not leave empty chains behind.

**Comment by LordOfTheRams** [comment]
Thanks for your reply! I have no local firewall running on the mailcow machine. All existing chains were created by mailcow. The firewall is external and just forwards the port 80 to the mailcow.  That works, unless I would not be able to access it from outside.

**Comment by andryyy** [comment]
Then it disallows the access from within Docker to the external interface. You need to trace it on your firewall. :)

**Comment by LordOfTheRams** [comment]
OK, I just wonder, how the initial registration of the certs was possible. There must be a difference somewhere between inital registration and renewal.

**Comment by stAn47** [comment]
hello, i happened to have exactly same problem today when whole SSL collapsed in my mailcow. i am using a few tens of domains and it seems that mailcow adds the autodiscover subdomain as SAN to the main certificate (instead of using SNI) . since all of the clients are configured to use a single domain for both smtp and imap which is also a mx server we are ok with one central domain which has a single certificate. the only possible certificate issues would come from autoconfigure clients but this is not the case right now. 

the behavior that i noticed today: 
- for domains which had no AAAA records, the mailcow log still listed AAAA to the main IPv6 of the sever
- some client domains which are not even online any longer (had expired) are still part of "autodiscover" and this broke validation of the main certificate

i decided to: 
- use our own lets encrypt validated domain that is managed outside docker and points to webroot of docker:
```
certbot certonly --webroot -w /opt/mailcow-dockerized/data/web/ -d mx..domain..com
```

copy these certificates to ssl in mailcow + adjust cron to update them regularly

then i decided to upgrade mailcow to the latest version and suddently i am stuck with "502 Bad Gateway" that i am going to describe in another post here  

(in my case 502 Bad Gateway is caused by php-fpm-maicow/./docker-entrypoint.sh which when it waits for mysql to initialize receives 
"1cabaa5565de52a9fd07b935ae27795919c04a431b45bbd9ef418aa6d3019670 34b29a39fcf66163560d59811d8d9a4cb4e2e5430fd98a0776f30f51e166943f"  (with a space in the middle ) 

and thus it gets stuck within:
```
until [[ ! -z "${CONTAINER_ID}" ]] && [[ "${CONTAINER_ID}" =~ ^[[:alnum:]]*$ ]]; do
 CONTAINER_ID=$(curl --silent --insecure https://dockerapi/containers/json | jq -r ".[] | {name: .Config.Labels[\"com.docker.compose.service\"], id: .Id}" 2> /dev/null | jq -rc "select( .name | tostring | contains(\"mysql-mailcow\")) | .id" 2> /dev/null)
```

i am not an expert on docker, but since mysql over here runs ok, i should be ok to remove all mysql upgrade code from this file - i don't really understand why php-fpm should do this, and not the mysql container itself. 

after running php-fpm manually inside the container, the 502 error is gone and web interface works OK. 

stan

**Comment by LordOfTheRams** [comment]
Well I did an update and all kind of stuff and ended up with the same errors like you.

After hours of struggling the solution to get it up running was:

```
docker-compose down
docker rm -f $(docker ps -a -q)
systemctl restart docker
docker-compose up -d
```

taken from issue #1582

Did not solve the LE registration problem though. Should the acme service be intelligent enough to extend a existing cert and add new domains?

**Comment by andryyy** [comment]
It is. 

If acme-mailcow cannot connect to your external hostname, you should check your firewall OR your DNS. Perhaps acme-mailcow does resolve MAILCOW_HOSTNAME to an internal IP?

**Comment by andryyy** [comment]
for domains which had no AAAA records, the mailcow log still listed AAAA to the main IPv6 of the sever

DNS propagation or an internal DNS that still resolves the name? There is no magic here, it just uses dig on that hostname.

    some client domains which are not even online any longer (had expired) are still part of "autodiscover" and this broke validation of the main certificate

That's related to the previous error. It is possible their names still resolve. Why do you have those domains as active in your mailcow, when they already expired?

    "1cabaa5565de52a9fd07b935ae27795919c04a431b45bbd9ef418aa6d3019670 34b29a39fcf66163560d59811d8d9a4cb4e2e5430fd98a0776f30f51e166943f" (with a space in the middle )

There should not be two SQL instances. The update script or you did not shutdown all containers, there were some containers (i.e. a mysql-mailcow container) left up and running.

    i don't really understand why php-fpm should do this, and not the mysql container itself.

We use an untouched MariaDB Docker image. The default Docker image cannot run this upgrade.

---

You should debug your setup.

**Comment by stAn47** [comment]
> If acme-mailcow cannot connect to your external hostname, you should check your firewall OR your DNS. Perhaps acme-mailcow does resolve MAILCOW_HOSTNAME to an internal IP?

hmm, i tried dig command but i just could not get the internal address for these. no firewall is used here. maybe if you can help me with full dig params that are used (or point me to a bash file that does it) i could know more. (it always resolved either to a wrong IPv4 for unconfigured or to our IPv6 where we used cname)

generally i believe it would be nice if those "autodiscover" subdomains would be only optional within the main certificate (at all services) since right now the certificate reveals all domains hosted on the server which could be also a security issue (especially if internal relay may skip some validatons if both from/to domains are on the same server)

within cpanel code i saw they use SNI's on devocot which seems to do the job very well. also nginx or apache supports SNI without problems. if client connects to the server with non-SNI capable email client, it's also possible the same email client accepts any type of invalid certificate and thus this should not play that much role. 

i solved all of the above by genering a new certificate for a single domain which became the only cert for all services. 

regarding the resolving of the autodiscover subdomain: 
- one thing is if it "resolves" and the other is if it resolves to our own server
- does mailcow know all IPs which are assigned to the server (i.e. all single IPs + all single IPv4s + all ipv4 subnets + all ipv6 subnets)
- maybe if it validates the resolved ipv4 or ipv6 to our own server it could then remove all those unresolved (+wrongly resolved) autodiscover domains from the certificate automatically and ask acme to validate only those that were passed it's own tests (maybe it's how it works now, but with our 80 domains in mailcow it just stopped working)

best regards, stan

**Comment by LordOfTheRams** [comment]
> It is.
> 
> If acme-mailcow cannot connect to your external hostname, you should check your firewall OR your DNS. Perhaps acme-mailcow does resolve MAILCOW_HOSTNAME to an internal IP?

Think I found the problem. You are right, it seems to be a firewall/routing issue. It just took a while for me to believe that because Mailcow ist reachable on port 80 from outside. The translation of MAILCOW_HOSTNAME to the right IP address is also correct. But I cannot access Mailcow from the inside through the outside http address. The reason is that the host is behind a NAT and accessing a natted address from inside does not seem to work.

Solution: SKIP_HTTP_VERIFICATION=y

Thanks for your help. Mailcow is great!
