### ISSUE TITLE
Alias domain filtering

### ISSUE THREAD

**Issue by patrick7** [mailcow/mailcow-dockerized#2601]
The "All domains" Dropdown is not working in "Mail Setup"

**Comment by andryyy** [comment]
Yes, it is non-existing. Need to fix JS for this, PRs are very welcome. :)

**Comment by Kraeutergarten** [comment]
Is there a reason for loading it async? 
See: https://github.com/mailcow/mailcow-dockerized/blob/9eebc7c524f46b1916b318b22bc2dbcdca607c41/data/web/js/site/mailbox.js#L11

Otherwise this might be the reason for the bug.
I changed it on my installation, now it works.

**Comment by evilstiefel** [comment]
I think that's correct, working on a PR now (but keeping it async).

*Edit:* Turns out keeping it async is hard with the way the mailbox javascript is programmed, since all the functions that reference the FooTable-instance are set up before any async requests can finish. So either I wrap the whole mailbox.js within the $.ajax or we simply switch to `async=false`. The latter works, but is "problematic" since technically, that flag is deprecated and keeps the whole page hostage/unresponsive while data is being fetched. The way it is now, either way, doesn't use the result of the call anyway (since the domain_list is assigned synchronously below the ajax call).

**Comment by andryyy** [comment]
It is not really deprecated, I think (!). It still has its use-case - just like ours. :) We need to fetch the domain list, before we acutally construct the table with its filtering component. At some point we will always need to wait for query A to return its stuff to pass it to query B.

I'm not good with JS, so if anyone can fix that, feel free to create a PR.

With async disabled, it will work occasionally, but will eventually fail after a few tries (race condition between the queries).

**Comment by andryyy** [comment]
@Kraeutergarten The alias domain table has no filtering component (the dropdown), so it cannot work after changing this variable.

**Comment by Kraeutergarten** [comment]
Em, without async it does work. I checked it on the alias table.

**Comment by andryyy** [comment]
Alias domain.

**Comment by Kraeutergarten** [comment]
Alias domain does not have this filter, I know.
Mailbox, alias and resources have the filter, that isn't working.

**Comment by Kraeutergarten** [comment]
Question:
Do we need all domains or only the domains that are existing in the table?

For the 2nd option i have a working solution, without a second ajax request.

**Comment by andryyy** [comment]
Oh, I assumed it was about the alias domain filter only (see title!).

Didn't know the other dropdowns broke.

No, I think the domains of the table are enough.

**Comment by andryyy** [comment]
Ah, damn, when did I revert this to async: true? It should not be async, because _then_ those race conditions appear.

Strange. Need to check the history... :)

**Comment by Kraeutergarten** [comment]
See: https://github.com/Kraeutergarten/mailcow-dockerized/commit/84a78dbd0d37f5f1968d3914423076de1a070322
for enhancement.

If you like it, i make a PR

**Comment by andryyy** [comment]
Nice, yes, a PR is very welcome!

Thanks for fixing that!
