### ISSUE TITLE
Create legal disclaimer on the login page of SOGo?

### ISSUE THREAD

**Issue by infracritical** [mailcow/mailcow-dockerized#2671]
Would like to have a customizable disclaimer of about 60-80 characters (or if too long, 35-40 characters) for a legal disclaimer along the lines of this:

```
WARNING:  Unauthorized access to this system is forbidden and will be
          prosecuted by law. By accessing this system, you agree that your
          actions may be monitored if unauthorized usage is suspected.
```

Is this possible?  The reason is, is that if you're going to have Internet-facing webmail, you SHOULD have legal disclaimers to protect you if you require legal coverage with federal law enforcement.  Look up the reason for having a legal disclaimer here: 

[https://security.stackexchange.com/questions/59589/are-legal-notices-in-a-login-banner-legally-significant-in-terms-of-computer-mis](url)

**Comment by infracritical** [comment]
BTW, here's our standard disclaimer that we use for all connection where length is not an issue:

```
                                -------------
                                W A R N I N G       
                                -------------

                      THIS IS A PRIVATE COMPUTER SYSTEM.

This computer system including all related equipment, network devices
(specifically including Internet access), are provided only for authorized use.
All computer systems may be monitored for all lawful purposes, including to
ensure that their use is authorized, for management of the system, to facilitate
protection against unauthorized access, and to verify security procedures,
survivability and operational security. Monitoring includes active attacks by
authorized personnel and their entities to test or verify the security of the
system. During monitoring, information may be examined, recorded, copied and
used for authorized purposes. All information including personal information,
placed on or sent over this system may be monitored. Uses of this system,
authorized or unauthorized, constitutes consent to monitoring of this system.
Unauthorized use may subject you to criminal prosecution. Evidence of any such
unauthorized use collected during monitoring may be used for administrative,
criminal or other adverse action. Use of this system constitutes consent to
monitoring for these purposes.

```

NOTICE: For those of you who would want to use this login banner, you hereby have permission granted to use, free of charge, without attribution.

**Comment by andryyy** [comment]
You don’t have to have it. It also depends on the country.

It is a commercial grade feature. I’m open for PRs or sponsoring. 

It is not like you cannot add a signature in your client (even in SOGo). :)

**Comment by infracritical** [comment]
Well...that sucks.  I guess when there's a will, there's a way.  Alright...I will let the group know what I find out from the SOGo team.

In the meantime, if I access the container created by docker-compose, and make active changes whilst the container is active, does it retain it's modifications?  If not, how do I make them permanent?

**Comment by MAGICCC** [comment]
Depends what you mean by changes. Everything which is mounted to your host filesystem is permanent. See the docker-compose.yml to check which is mounted to the host filesystem

**Comment by infracritical** [comment]
> You don’t have to have it. It also depends on the country.
> 
> It is a commercial grade feature. I’m open for PRs or sponsoring.
> 
> It is not like you cannot add a signature in your client (even in SOGo). :)

I beg to differ.  In the Land of Lawyers, every bit of legal disclaim is always helpful.  ;)

**Comment by Braintelligence** [comment]
@infracritical Considering at least Germany most lawyers seem to agree that mail disclaimers within the mail are not only not needed but even completely useless due to the fact that they are an ex parte/one-sided agreement. I can't find many sources that state otherwise. Many relevant things within such disclaimers unfold through general applicable law anyway, which introduces redundancy.

So I definitely agree with @andryyy here. I don't know about legal necessities of mail disclaimers in other countries for sure, though; still, it would be kind of funny that one-sided agreements would mean anything.

**Comment by mkuron** [comment]
This is the digital equivalent of putting up a "please don't break in" sign in front of your house. Just by having a lock on your door (or putting up a login screen), you are already stating that this is not publicly accessible space. So any reasonable situation should not require such a message. (I said _should_ because law does not always seem to follow the rules of reason... at least to us non-lawyers.)

> every bit of legal disclaim is always helpful

That's not entirely true. For example, there are situations where disclaiming something that can't be disclaimed may have negative consequences for you. Or having a disclaimer today and accidentally removing it tomorrow might look like you are now allowing people to break in. So be careful with disclaimers too.
