### ISSUE TITLE
Removing network mailcowdockerized_mailcow-network ERROR

### ISSUE THREAD

**Issue by GrantZero** [mailcow/mailcow-dockerized#2684]
Hi there,
i have updated my system since a hour.

`Removing network mailcowdockerized_mailcow-network
ERROR: error while removing network: network mailcowdockerized_mailcow-network id 1eccb40d03efb59b1b277a32d9cfe9a365cdd5f73188aa62ea981c63195c464d has active endpoints
`

Can anybody help me?

**Comment by andryyy** [comment]
That's not the same problem. Some container is using the network and is not removed.

Purge all containers (ALL, as in "removes all containers"):

```
docker-compose down
docker stop $(docker ps -a -q)
docker rm -f $(docker ps -a -q)
systemctl restart docker
docker-compose up -d
```

**Comment by GrantZero** [comment]
I'm sorry.

Thanks a lot @andryyy!!!

That is the solution.

**Comment by needToRoll** [comment]
Hi 
A quick note for everyone checking this issue in the future.
The proposed solution by @andryyy stops all containers running on that docker host.
The problem appears to be that sometimes stale endpoints exists from the shutdown.

A less invasive solution to this problem would be to just remove the stale endpoint from the network.

What I ended up doing looks like this.

Problem:
1. I ran the update script.
2. The step to take the containers offline reported an error because one network still hand active endpoints
     * The script continued to run, I am assuming this is because all containers have been stopped.
3. The startup script failed because the newer version of the container that did not shutdown properly failed to attach to the network.

Solution (Credit to [this comment](https://github.com/moby/moby/issues/17217#issuecomment-918943971))
1. I ran `docker-compose down` to stop all containers that were started by the update script but are not in a working state
    * Take note of the network_id that causes the problem
        - The error message looked like this: `ERROR: error while removing network: network mailcowdockerized_mailcow-network id {network_id} has active endpoints`
     * Optionally you can check if no container are running for this project by using `docker-compose ps`
2. Use `docker network inspect {network_id}` and take note of the endoint name that has become stale
3. Run docker network `disconnect -f {network_id} {endpoint_name}` to forcefully disconnect the stale endpoint from the network
4. Optionally: Remove the old network by running: `docker rm {network_id}`
5. Restart the containers by running `docker-compose up -d` or restarting the update script.

@andryyy Is this something that could be added to your update docs? Or would you be open to a PR for your update script?
