### ISSUE TITLE
Add Simplified Chinese translation.

### ISSUE THREAD

**Issue by OrvilleQ** [mailcow/mailcow-dockerized#2685]
I want to add Simplified Chinese translate to your webui but I don't use php.

So what should I do beside lang.zh.php (or lang.zh_cn.php I guess?)

**Comment by ntimo** [comment]
I am not mistaken, the two php files containing the translation is all you need to add :)

**Comment by OrvilleQ** [comment]
So should I add lang.zh.php or lang.zh_cn.php?

Because you know, zh_CN and zh_TW are Chinese write in whole different ways.

**Comment by ntimo** [comment]
Then it would be lang.zh.php :)

**Comment by PhoenixPeca** [comment]
Hi @OrwillT ,

"Avoid region, script or other subtags except where they add useful distinguishing information. For instance, use `ja` for Japanese and not `ja-JP`, unless there is a particular reason that you need to say that this is Japanese as spoken in Japan, rather than elsewhere."

As as defined in an [W3 internationalization article](https://www.w3.org/International/articles/language-tags/), we can specify the regional difference between language codes by adding the region subtag of where the concerned language is being spoken.

`language-region` = `zh-cn` = `Simplified Chinese - China`

I suggest to rename it to `lang.zh-cn.php` for future compatibility in case somebody wants to translate mailcow for Traditional Chinese in taiwan `zh-tw`.

Anyways, just create a PR for this and we'll be happy to review merge.

Thanks!

**Comment by andryyy** [comment]
Thank you! The language file is enough, we will take care of integrating it. :)

**Comment by OrvilleQ** [comment]
Just finished part of the collage exam, start the translation, will be completed in a week or so.

**Comment by andryyy** [comment]
Thank you very much!
