### ISSUE TITLE
Problem with concepts in outlook 

### ISSUE THREAD

**Issue by GlowManCZ** [mailcow/mailcow-dockerized#2724]
Hi,

I` have a problem when a colleague writes an email in an Outlook. And he writes it for about 4 hours and adds something to it. Then he wants to send it but outlook writes that the message was not found and that it is not possible to send it and must write it again. It looks like a limit in concepts.

Thx

**Comment by Adorfer** [comment]
This is not limited to 4 hours or 3 hours, it may even happen after 10 minutes, at least in my setup.
I wonder where this 4 hour-criteria derives in your setup. 
In mine it's lined to background-tasks via imapmove, touching the concepts-folder as well (which should really not be touched while users are active)

**Comment by andryyy** [comment]
Imapmove?

If you speak of imapsync: No, it should not care or check if users are active via IMAP. If Outlook is too stupid (guess you use EAS) then I don't care. I don't care about Outlook at all, tbh. 

You should file a report with SOGo, if the ActiveSync implementation has problems with Drafts in Outlook. :) We cannot change this behavior on our side.

**Comment by Adorfer** [comment]
Correct, imapsync. i assume that outlook expects some kind of locking mechanism (only supported by exchange?) 
in other words: Not much mailcow can do about it. This could be only handled upstream either in imapsync (eventually) or better in dovecot. 

The big question for is is: Why does it happen at @GlowManCZ only after 4 hours. Since i can encounter that even after a few minutes. So perhaps there is multple aspects in this.
