### ISSUE TITLE
Separate subdomain for webmail/admin from MX records

### ISSUE THREAD

**Issue by timothymiller** [mailcow/mailcow-dockerized#2738]
I would like to send emails from <username>@domain.com
I would also like to keep the root domain https://domain.com open as a landing page
Because of the above requirement, I need to place the admin/webmail software under a separate subdomain, such as https://webmail.domain.com

Is this officially supported, or require a custom nginx configuration?

**Comment by fm** [comment]
is the domain.com landing page going to be hosted on a different server? If so, just point webmail.domain.com to the mailcow IP. 

On my instance, I have it set so that the admin resides at portal.mydomain.com, and I have mydomain.com added as a domain with no issues. No nginx weirdness. I did add the subdomain to the mailcow.conf user ADDITIONAL_SAN so it gets issued an SSL cert.
