### ISSUE TITLE
ipv6nat - Container Very High CPU usage

### ISSUE THREAD

**Issue by anonfreak** [mailcow/mailcow-dockerized#2781]
Hi, today i updated mailcow to the latest version, but unfortunately the ipv6nat-Container ist totally freaking out and eating up all my CPU on the server, which from time to time causes downtimes of the whole server, which is kind of annoying. 

Also when I open ```top```, I see at position 1 with 100% CPU usage the command ```iptables-nft```.

To quick-fix the problem i just killed the container, as I don't know that it is doing exactly, so i hope i don't need it.

Weirdly this wasn't before the update so I think it has to do with the update. Before I was on a version around late 2018, before i updated today

I'm running a root server from Netcup with 2 CPUs.

**Comment by andryyy** [comment]
You should disable IPv6 now. 

Any logs of that container would have been helpful.

**Comment by anonfreak** [comment]
I could do that, but arent't there disadvantages of disabling IPv6 for mailcow?

As I said, when i tried to get some logs by using docker logs [container-id of ipv6nat] nothing appeared.

**Comment by andryyy** [comment]
You didn't mention that about. If you did, I'm blind. :)

The issue template is completely missing. No system info. Cannot try to reproduce it. 

You should also open an issue at https://github.com/robbertkl/docker-ipv6nat

Update, upgrade and restart your VM, please. Don't forget the issue template information.

**Comment by thomasvt1** [comment]
![image](https://user-images.githubusercontent.com/2271011/61225362-b214a400-a720-11e9-85f5-6fa55b02b48d.png)

Have the same issue.. didn't enable ipv6

**Comment by Braintelligence** [comment]
@thomasvt1 Please go on and provide what the issue template asks of you. We need more info than that.

**Comment by andryyy** [comment]
You don't enable IPv6 in mailcow. It is enabled by default...

But I cannot help without any info. Iptables output, system info, Docker Info etc. 

This does not happen on any mailcow I support, so I don't know what I can do for you, besides asking for your system info to replicate it, when I find time.

**Comment by thomasvt1** [comment]
**System information and quick debugging**
General logs:
https://gist.github.com/thomasvt1/9462badda43cee263bf41975f4a7d764


Further information (where applicable):
 - Your OS (is Apparmor or SELinux active?)
   - Ubuntu 18.04.2 LTS
 - Your virtualization technology (KVM/QEMU, Xen, VMware, VirtualBox etc.)
   - OpenVZ (7)
 - Your server/VM specifications (Memory, CPU Cores)
   - 2GB RAM
   - 2 vCPU Cores
 - Don't try to run mailcow on a Synology or QNAP NAS, do you?
   - Nope
 - Docker and Docker Compose versions
   - Docker version 18.09.7, build 2d0083d
   - Docker-compose version 1.24.1, build 4667896b
 - Output of `git diff origin/master`, any other changes to the code?

![image](https://user-images.githubusercontent.com/2271011/61226482-c9549100-a722-11e9-91a6-23127f3f21c6.png)

 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
   - [iptables -L -vn](https://gist.github.com/thomasvt1/772eef5ecff7efbcbfca5557a1e7adcf)
   - [ip6tables -L -vn](https://gist.github.com/thomasvt1/00bdf8b5dc753cfbd3341b74456f148c)
   - [iptables -L -vn -t nat](https://gist.github.com/thomasvt1/f37fd5bf12f38eb7dc999f78ebf55956)
   - [ip6tables -L -vn -t nat](https://gist.github.com/thomasvt1/1c7763312af3ca431a104a1a1b4a42a6)
 - Reverse proxy? If you think this problem is related to your reverse proxy, please post your configuration.
   - Using traefik shouldn't matter tho as killing mailcowdockerized_ipv6nat container fixes the high cpu load
 - Browser (if it's a Web UI issue) - please clean your browser cache and try again, problem persists?
   - Not a browser issue
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?

[VPS bought from here](https://clients.inceptionhosting.com/cart.php?a=add&pid=123)

**Comment by mkuron** [comment]
Might be an OpenVZ limitation? It shares one Linux kernel between multiple customers, so it might restrict what you can do in terms of networking, firewalling, or Docker. Perhaps someone running Mailcow on OpenVZ could report their experiences. It's not very commonly used anymore.

**Comment by thomasvt1** [comment]
@anonfreak are you running OpenVZ aswell?

**Comment by anonfreak** [comment]
No I'm not running on OpenVZ...

**Comment by DatAres37** [comment]
I just had the same problem with the watchdog container, but restarting fixed it.
Do you have zombie processes by any chance?

**Comment by andryyy** [comment]
I think there might be a problem with watchdog at the moment, but it is not related to the ipv6nat container.

I think the whois command is what causes a strange loop somewhere. I already made changes and added them to the managed mailcows to keep an eye on it.

**Comment by BerFoe** [comment]
I'm facing the exact same problem on my vServer. The problem is definitely caused by the ipv6nat-container. When I restart it, the process _iptables-nft_ disappears and starts again after a short wile.
I updated and restarted everything just this morning, but the problem still exists.
As my hoster 1blu does not support IPv6, I disabled it via docker-compose-file, just as described. Activating it does not make a difference. 
The host uses Virtuozzo, which is based on OpenVZ. The vServer is running Ubuntu 18.04 LTS, has four cores and 12GB memory.
Docker version: 19.03.0
Docker-Compose version: 1.24.1
The ipv6nat-container does not seem to log anything. At least I did not find anything.
Can I provide you any further information?

In the meantime, until the problem is fixed, is stopping the container completely an option, or would there be any issues? As I already said my hoster does not support IPv6, so maybe this would be a workaround.

**Comment by mkuron** [comment]
If you don't have an IPv6 address on your host, you can safely disable that container.

**Comment by thomasvt1** [comment]
This is still an issue

**Comment by andryyy** [comment]
I don't support OpenVZ stuff, sorry.

**Comment by thomasvt1** [comment]
OP @anonfreak doesn't use OpenVZ though

**Comment by andryyy** [comment]
So what shall I do now?
