### ISSUE TITLE
ClamAV stays enabled in rspamd config

### ISSUE THREAD

**Issue by snake-4** [mailcow/mailcow-dockerized#2852]
Even if user disables ClamAV when installing mailcow, in the antivirus.conf file of rspamd the ClamAV stays enabled, I think this slows down mail sending time because when I removed ClamAV from the file the mail sending time went from 10s to 2s. The verbose postfix logs indicate that rspamd was taking around 7 seconds and the rspamd logs were indicating it was caused by ClamAV even if I disabled ClamAV when installing mailcow.

Further information (where applicable):
 - CentOS 7
 - 2GB Ram, 2 core CPU
 - No changes to code.

**Comment by andryyy** [comment]
Rspamd remembers the upstream as down.

**Comment by snake-4** [comment]
Oh damn, for some reason postfix gets stuck on milter for 10 seconds, I will send logs when I get home

**Comment by andryyy** [comment]
I will also try to reproduce it. :)

**Comment by Braintelligence** [comment]
@SnakePin did you fix your problem?

**Comment by snake-4** [comment]
Nope it still takes 10 seconds to send mail when ClamAV is in configs but I see this in logs when ClamAV is not removed `2019-09-04 12:40:34 #22(normal) <12bcc2>; lua; clamav.lua:119: clamav: failed to scan, maximum retransmits exceed`

**Comment by wblondel** [comment]
Same here, Rspamd doesn't seem to remember that ClamAV is down since it tries to transmit every received email.
![rspamd](https://user-images.githubusercontent.com/7508531/68537387-f167a000-0362-11ea-92c3-ba2c03f4de76.png)

**Comment by mkuron** [comment]
Whether an upstream is down or not is only cached for 10 seconds (https://github.com/rspamd/rspamd/blob/24f973e828f0aa313ea8a8fd8f04478db9e0ea9a/src/libutil/upstream.c#L140). Since you don't receive a lot of messages, you won't see that the state is cached. 10 seconds seems a good compromise between server load and not letting too many messages pass unchecked when e.g.  clamav is being restarted, so I advise against changing that in general. However, you can certainly disable clamav entirely in your local copy of antivirus.conf.

**Comment by andryyy** [comment]
Funny idea: spawn a simple tcp server to emulate a ClamAV pass when ClamAV is disabled by config. 

Note: I don't want to remove the file if skip_clamd is set to y. I often use dedicated scanners and deleting the file is contra productive for my setups.
