### ISSUE TITLE
Clam AV OOM & CPU load

### ISSUE THREAD

**Issue by patrick7** [mailcow/mailcow-dockerized#2877]
Since some time ClamAV (freshclam) uses 100% on my system. Also today it made the system OOM.
Any hints how to troubleshoot?

**Comment by Braintelligence** [comment]
Why do you ignore the issue template?

**Comment by patrick7** [comment]
Because:
- 8 out of 10 open issues are not using it (I miss your comment there ;))
- There's nothing to do to reproduce it
- It's ways to long for this problem

The only relevant thing in the template is:

| Question | Answer |
| --- | --- |
| My operating system | Debian 10 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc) | KVM |
| Server/VM specifications (Memory, CPU Cores) | 4GB RAM, 4 Cores |
| Docker Version (`docker version`) | 19.03.1 |
| Docker-Compose Version (`docker-compose version`) | 1.24.1 |
| Reverse proxy (custom solution) | None |

**Comment by Braintelligence** [comment]
- It's strange how you assume that I have to look into every issue and tell people to follow the issue template if they want help from people that devote their free time for this
- Sure there's something to do to reproduce it, at least in one's head: Own a similar environment like yours, which we can't know if you just post something a lá "Subsystem X doesn't work, any hints?"
- You're obviously able to tell that some points can be important to get a better scope of your possible issues leading to the symptoms you're looking at, and still decided not to provide them even though the issue template gives you a hint on doing so

Since you're sure that logs are not relevant to your issue I myself have no clue how to help you other than saying that you are very close to maybe not having enough RAM for Mailcow+ClamAV+SOLR.

Maybe someone else has an idea from the provided information; we have no way of telling if you're a victim to zipbombs or anything, since you think that related information is not relevant.
