### ISSUE TITLE
Lost Two-Factor Authenctication

### ISSUE THREAD

**Issue by Karljklung** [mailcow/mailcow-dockerized#2894]
I've had mailcow running for a while now and it has been great to use. Two-Factor Authentication has been enabled on the admin user for a while which has worked completely fine. My phone got messed up this summer, so I lost everything on it since there are no signs of life in it now.

I would like to disable Two-Factor Authenctication on this admin user in a easy way if it is possible. I did lookup this at the other posts here about the same topic, but I did not really understand the procedure in order to get this fixed.

If there are any posibility to create a domain admin via the terminal, that would be the easiest part to just logon and then use that one. Not sure how that works or if it does even. Could anyone help me here?

**Comment by altnd** [comment]
Hey Karljklung,

you can find the needed command in the documentation =>  

https://mailcow.github.io/mailcow-dockerized-docs/debug-reset_pw/

type in your terminal: 

1. source mailcow.conf

2. docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME} -e "DELETE FROM tfa WHERE username='YOUR_USERNAME';"

**Comment by Karljklung** [comment]
Hey altnd,

Thanks alot for the quick reply. I can confirm that this did work completely fine for me.

I'm back again into the admin panel. ;)

**Comment by dasfilter** [comment]
> 
> 
> Hey Karljklung,
> 
> you can find the needed command in the documentation =>
> 
> https://mailcow.github.io/mailcow-dockerized-docs/debug-reset_pw/
> 
> type in your terminal:
> 
>     1. source mailcow.conf
> 
>     2. docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME} -e "DELETE FROM tfa WHERE username='YOUR_USERNAME';"

Hi.
I've got a similar problem. From one day to the other I couldn't use mit 2FA with my Yubikey on my admin account anymore. Maybe the problem is my https connection, but that's not the point. I use these two command strings und now I could noht connect to my mailserver at all. No IMAP, no https, no nothing. :( 
In portainer I see that the dockers are running.

In the log files of nginx ist see this error:

2020/05/03 17:02:07 [emerg] 13#13: SSL_CTX_use_PrivateKey("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx: [emerg] SSL_CTX_use_PrivateKey("/etc/ssl/mail/key.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)

**Comment by dasfilter** [comment]
I now used the helper script to reset the admin account but no success.
