### ISSUE TITLE
Mailcow is eating my disk space

### ISSUE THREAD

**Issue by haiopaii** [mailcow/mailcow-dockerized#2949]
Hey guys,

I´m using mailcow now for a long time, no problems so far.

Since ~3 weeks, I am getting problems with my disk space.
The drive (40GB) is running out of space, BUT I do not need that much mailspace.

After running an update and deleting old image tags, the drive space is fine again.
Today I got the same problem and stopped the compose.
I ran "docker system prune" and it deleted 29GB of space.

Is there any bug in my installation?

I attached you some screenshots, maybe someone can help.

![reclaim](https://user-images.githubusercontent.com/36101628/65068645-4d2c3300-d989-11e9-8319-5ef06a4d64cf.PNG)
![diskspace](https://user-images.githubusercontent.com/36101628/65068646-4d2c3300-d989-11e9-9144-f836e56b3f10.jpeg)

**Comment by andryyy** [comment]
I don't know about your system specs, you deleted the template... :) Could be clamd-mailcow oom dying and filling the temp folder.

**Comment by haiopaii** [comment]
I got a 4GB RAM, 2 CPU, 40GB NVME Server (CX21) from Hetzner Cloud.
running latest debian 10

**Comment by MAGICCC** [comment]
A `docker system df -v` may help for a first check. Also `ncdu` is a nice tool

**Comment by andryyy** [comment]
I also recommend to run `ncdu /var/lib/docker/volumes/` as soon as it fills your disk. Please post the results afterwards.

**Comment by PaoloVi** [comment]
Probably is not a Mailcow issue, but a Docker peculiarity.
When you upgrade Mailcow you should delete old images and volumes. The first is an automatic operation inside update script: "Do you want delete old images?" (more or less).
For the second one, you must run prune command manually.
After updates, you must be sure that all services are up and running (you can see them in "debug" page or your mailcow gui panel: configuration -> system information -> System and containers. Here you also can view your disk usage)
Go to /opt/mailcow-dockerized and run "docker system prune -a --volumes".
Now refresh your debug web page and take a look at your disk space usage.
Be sure that every mailcow service are up and running, because this command delete every unused volumes.

**Comment by WFWG** [comment]
This must be within Mailcow.
Had this problem also a few days ago.
Mailcow data volumes (mail, db,redis,rspam,postfix,crypt) are seperate from the /var/lib/docker in my architecture and the docker mount runs out of space. Just a simple restart frees 75% of the space. No update done in between

**Comment by patschi** [comment]
As @MAGICCC suggested you might want to use `ncdu` to track down the exact folder or service which is continously filling up your space. Without any further details, it's hard to determine the cause of this. As there are not much reported issues like that, it seems to be an more isolated issue.

**Comment by WFWG** [comment]
@patschi "du" should be sufficient to track down the folder. but ncdu is helpful - not everyone likes to install additional software ;)

right now its operating normal so nothing to see. I will configure my monitoring to track this in detail. if it comes up again I will share the data. 
Stuff like this happens from time to time - for me it's no big deal - I just came over this issue reading the issuelist and added my 20cents.

**Comment by andryyy** [comment]
Never seen this. Need the du or ncdu output. :)

**Comment by haiopaii** [comment]
After disabling ClamAV everything works fine.
Looks like clamav runs oom and eats the disk space after.

**Comment by andryyy** [comment]
The new image at least cleans up after itself. I can check for watchdog-mailcow. If a worker dies, it writes a Redis key and howls.
