### ISSUE TITLE
mailcow - open relay?

### ISSUE THREAD

**Issue by X1Aaron** [mailcow/mailcow-dockerized#2967]
https://www.lowendtalk.com/discussion/160389/mailcow-server-was-compromised

I don’t think this is true, but I wanted @andryyy to know and to be able to reply if wanted :-/

**Comment by andryyy** [comment]
Can't open the link. But I'm sure that is related to the guy with the misconfigured firewall, using hide NAT to his cow, so every connection came from his internal gateway. Hello open relay. All connections are trusted. 

If you want me to know, mail me. This is not my inbox. 

If there is a security issue, write it down. The issue is useless like this.

**Comment by Braintelligence** [comment]
Reading the forum thread I'm convinced, that it's an open relay issue.

**Comment by andryyy** [comment]
I logged in.

> The log shows these emails were sent from trusted login of 172.17.. (my docker bridge address) and the account is <*.bbc.co.uk> (of course not of my domain, and I never granted any mailboxes to send as other users).


Setup your mailcow correctly then. If they install it with broken NAT or manual iptables (and don't actually configure it manually) or use hide-NAT with a firewall, all connections MAY end up trusted.

Do not install a mail server if you cannot do any of this. 

**The default Docker gw in mailcow is 172.22.1.1** - something was changed and not configured correctly. I think they used a manual iptables config.
