### ISSUE TITLE
activate DANE? 

### ISSUE THREAD

**Issue by wuast94** [mailcow/mailcow-dockerized#2974]
i am a bit confused so sry if I miss understood the whole thing. 

I want to enable DANE on my mailcow instance. but how? I didn't find settings for that. is it enable by default? I am using Cloudflare for my DNS Records and on mailcow dns test all entries are checked so from this side should be all fine ? 

What must I do to enable DANE on my server ?

**Comment by MAGICCC** [comment]
As long as you have TLSA records its fine

**Comment by wuast94** [comment]
can I test if this works ?

**Comment by wuast94** [comment]
ok my TLD (check domain) seems to have no support for DNSSEC so DANE etc can't work right? I contact the support of check domain because of KNOCK KNOCK -  2019 is here surprise :D

**Comment by ggmanugg** [comment]
Your registrar must support DNSSEC too otherwise the TLSA entries have no affect. Check if in your Cloudflare Dashboard (home -> example.com -> DNS -> DNSSEC) DNSSEC is enabled and confirmed.
![image](https://user-images.githubusercontent.com/37898579/65604884-7c096100-dfa8-11e9-84d2-448a43f69913.png)

**Comment by wuast94** [comment]
I changed my registrar and now all works fine :) I close this issue :)
