### ISSUE TITLE
Why Persistence data is stored in different locations? 

### ISSUE THREAD

**Issue by wuast94** [mailcow/mailcow-dockerized#2991]
Today I learned to read Dokus properly and to test backup mechanisms. 
I was thinking that just backup the mailcow dir is enough. All may docker applications works like that that I have an folder that contains the docker-compose.yml and all the persistence data. but mailcow stores some data in his own directory and some in the docker volume directory. 

but I don't understand why. And my question is why there are different directorys where data is stored and not all in the mailcow dir ? would make backups a lot easier because I can just stop docker .. copy this one folder and start docker again.

**Comment by mkuron** [comment]
Configuration and scripts are in the Mailcow directory, while all data is stored on Docker volumes. You wouldn‘t want to store the data inside a folder that‘s also a Git repository (even if you gitignore the data directory) because certain Git operations (like `git clean`) could still endanger it.

So please read documentation and test your backups. If your backup only takes a few seconds, even though you have gigabytes of messages, it‘s probably not complete...
