### ISSUE TITLE
AutoDiscovery not working correctly after update

### ISSUE THREAD

**Issue by CptWonderful** [mailcow/mailcow-dockerized#3039]
Hey guys,

after one of the last upgrades my AutoDiscovery is not working anymore (accounts which were setup before seem to be working).

https://testconnectivity.microsoft.com has the following output:

![testconnectivity_output](https://user-images.githubusercontent.com/56501136/66712661-26062d00-eda0-11e9-86fb-98852602f388.png)

Autodiscover Log in the webinterface:

![Autodiscover_log](https://user-images.githubusercontent.com/56501136/66712659-15ee4d80-eda0-11e9-80c2-d379c1724b4b.png)

When I'm trying to add it via outlook android client, it works, but no emails are synched. Furthermore the additional settings are missing after the setup - Differs from the behavior before the update.
IMAP is working fine.

Any other logs I can provide?

**Comment by andryyy** [comment]
Autodiscover.php has not been touched since 9f0be1d on 11 Oct 2018.

MS Connectivity tester never worked with SOGo.

So no, the update did not break anything regarding autodiscover.

Please don't delete the whole issue template next time.

The realm https://domain.de:443/autodiscover/blabla is also not valid. The correct realm is autodiscover.domain.de/autodiscover/blabla. :)

It returtned "WWW-Authenticate: Basic realm="Zugriff verweigert"" etc. ... that's not a string we return, too.

I don't know if you are using a reverse proxy etc., but I think you should join the Telegram group for this kind of support.

**Comment by andryyy** [comment]
For some crazy reason it actually works today. :| 

![image](https://user-images.githubusercontent.com/2972950/66712724-45ea2080-eda1-11e9-88a9-17df4f0b6fdb.png)
