### ISSUE TITLE
Can't add mailbox to GMail App

### ISSUE THREAD

**Issue by MAGICCC** [mailcow/mailcow-dockerized#3132]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?
GMail App throws an error when you are trying too add your mailbox to the app
![photo_2019-11-09_13-05-31](https://user-images.githubusercontent.com/3279213/68528345-b24d3680-02f1-11ea-9250-3f5dbd39f410.jpg)

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1. Use GMail Version 2019.10.20.278647676.release
2. Add a mailbox

**Comment by andryyy** [comment]
How exactly do you add it?

**Comment by itsbhanusharma** [comment]
Hi @andryyy , 
I came to telegram trying to get a resolution for this, Here is what exactly happened:

All the emails were working fine until about 5 Hours ago when I saw a notification that my exchange account needs attention. 

Opened it to the above given screenshot. 

Tried removing and readding:

Accounts > Add another account > Exchange and office 365 > Log in with my mailcow username/password and then it shows the same warning again. 

As far as I know, Nothing had changed in terms of device/server until the time I had first faced the issue. Since then, I've tried to update mailcow to latest which didn't help. (my installation was about 2 weeks out at this point so I thought that might help)

I've tried searching through google and haven't been able to figure out what may be the problem here.

**Comment by apoc4lyps** [comment]
Hi, I have two devices with the same gmail build number. One of them has the same issued, the other works fine (diffrent mail accounts / same server). Already tried to reset the Active Sync Cache and readding the account.

**Comment by andryyy** [comment]
I don't know and I don't know what we could do about this anyway. You can ask for support at SOGo. The interface is provided by them. On the other hand it is obviously an app issue. We cannot change that either.

Don't use the Gmail app.

**Comment by apoc4lyps** [comment]
Found a workaraound (https://support.google.com/mail/thread/13559203?msgid=19126118)
- remove EAS account
- uninstall the Gmail (update)
- add EAS account
- install Gmail update

**Comment by lemonsquash** [comment]
I have the same issue, it seems like integrated EAS in Android was changed somehow with the latest update of Gmail (I've received it on Saturday, since then the problem exists on all my Android devices). Also, my Calendar and Adressbook sync is no longer working.
Maybe this is due to updated requirements for device security policies which SoGO is not able to provide within its EAS implementation afaik...

**Comment by andryyy** [comment]
Try the steps mentioned above and read the thread @ Google. 

You can try to set a 8 digit PIN on your phone, too. Blame the app. :-)

**Comment by OCram85** [comment]
Same problem here. Downgrading the gmail app works as workaround like described.

**Comment by dragoangel** [comment]
My coworker said it was fixed with GMail update

**Comment by MAGICCC** [comment]
Seems Google pushed an update
