### ISSUE TITLE
DomainConnect integration

### ISSUE THREAD

**Issue by RobertB93** [mailcow/mailcow-dockerized#3208]
Hey guys,

what do you think about adding support for the domainconnect protocol (https://www.domainconnect.org/)?
This would make the DNS setup for some users even easier.

**Comment by mkuron** [comment]
We had previous requests for integrating a DNS server and for automatically publishing the DNS validation records for ACME, which at the time we decided not to do because of complexity and lack of standard protocols, respectively. Domain Connect certainly looks like a solution to this problem. If it gets support from a few more DNS providers, it might indeed be worthwhile to implement. However, it does not currently support PTR records, so some manual DNS editing would continue to be required.

**Comment by RobertB93** [comment]
That's true about the PTR records, but it's usually not even standardized how to set them anyway, as many providers have their own solution there.
Domainconnect could at least facilitate the mx, spf and dkim setup which are the most "complex" records in this setup.

**Comment by dragoangel** [comment]
@mkuron PTR is managed by ASN owner of IP subnet what you use for mail server. NS in addr-arpa, which in most cases this is ISP. In really rare cases own NS.
@RobertB93 DNS records creation must be managed by people. If mail administrator doesn't understand such base stuff, better he begin to learn it. Each company|mail owner want own SPF, DKIM & DMARC. Question about security: even when you validate ACME via DNS correctly thinking people do not want allow full access to some server to your production domain and many people use https://github.com/Neilpang/acme.sh/wiki/DNS-alias-mode because of that.
