### ISSUE TITLE
fix key exchange parameters

### ISSUE THREAD

**Issue by wuast94** [mailcow/mailcow-dockerized#3223]
i cheked my mailserver with internet.nl and become one error on key exchange. 

used is DH-2048 wich is insufficient. 

there is a explaination too and also wich Elliptic curves should be used for ECDHE

**Comment by andryyy** [comment]
Care to explain why exactly 2048 is insecure?

**Comment by wuast94** [comment]
ok I got a bit deeper into that thing. for now its not insecure but its just a question of time I think. 
I close this issue but we should have this in mind I would say :)

**Comment by Wastus** [comment]
The document linked here: https://english.ncsc.nl/publications/publications/2021/january/19/it-security-guidelines-for-transport-layer-security-2.1 (see page 16)
RSA is considered phase out because it doesn't provide forward secrecy. Thus only ECDHE and DHE are considered good or sufficient.
So it's not 2048 bits causing this message but the availability of RSA.

**Comment by aronmal** [comment]
So DH-2048 and RSA are "enabled"? And RSA will sooner or later be removed (in mailcow)?

-----

I got the same message when I checked my server with internet.nl and below it displayed this:

![image](https://github.com/mailcow/mailcow-dockerized/assets/57275207/08598d51-6665-4744-a311-8e565cd5f286)

But if you guys say DH-2048 is good, I'm fine. But why not have dhparams.pem file with 4096 for new instances (or is it already the case?)?
