### ISSUE TITLE
Mailcow on Debian 10 stops psad daemon from adding iptables rules

### ISSUE THREAD

**Issue by soulsymphonies** [mailcow/mailcow-dockerized#3229]
Hello,

just a short question, as I found no recommendation in the manual, but is there any preferred base operation system for mailcow, for example, which Debian version would you suggest.

I had installed mailcow on Debain 9 Stretch for a over a year now and it worked just fine.

Now recently I have installed my mailcow on Debian 10 Buster, but then it stops my psad daemon from adding firewall rules as soon as I start mailcow. 

The behavior is as following, starting Debian 10 and psad and not starting mailcow yet, psad works just fine. Starting mailcow, psad runs still but can not add any more rules to the iptables chains.

So should I rather use Debian 9 again or is this just some issue with mailcow in combination with the new default firewall via nftables in Debian 10, that could be corrected?

Kind regards and a merry christmas.

Robert

**Comment by mkuron** [comment]
I believe Debian 10 uses nftables while Debian 9 uses iptables, so that‘s probably where the difference lies. We generally recommend a recent, supported version, so both Debian 9 and 10 should be fine.

> then it stops my psad daemon from adding firewall rules

Docker and custom firewall rules don‘t play nice. That‘s not a Mailcow problem and we can‘t really support you in figuring out how to make it work because it can be different in every distribution and every firewall tool.

**Comment by andryyy** [comment]
Have you checked if the rules exist by using iptables-legacy?

I don't see why or how mailcow could block that. Hm.
