### ISSUE TITLE
How to cut down the size of mailcow installation?

### ISSUE THREAD

**Issue by akash07k** [mailcow/mailcow-dockerized#3255]
I want to know that is there any way by which I can cut down the size of mailcow installation on my docker machine?
Right now I have very limited server with only 40 gb of SSD and 1GB of RAM.
Is there any way that I do not install unwanted components such as redis and all?

**Comment by andryyy** [comment]
Please use the Telegram channel for these questions. :(

No, you cannot. You can decrease the workers of SOGo to something along 3-4. Deleting the SA rules file `data/conf/rspamd/local.d/spamassassin.conf` and restarting rspamd-mailcow does help, too. It does not help filtering, but it helps with resources.
1 GB will not work reliable anyway, sorry.

**Comment by MAGICCC** [comment]
40GB SSD is enough space, but 1GB of RAM is pretty low. We recommend to have atleast 3, better 4GB of RAM.
https://mailcow.github.io/mailcow-dockerized-docs/prerequisite-system/#minimum-system-resources

**Comment by akash07k** [comment]
Oh, ok. even though I disable clamav, then too it is not going to work properly on 1gb ram?

**Comment by akash07k** [comment]
If no, then can you please suggest me any light opensource mail server? :(

**Comment by mkuron** [comment]
Any solution that provides functionality similar to Mailcow‘s SOGo and has a modern spam filter like rspamd will end up very close to that 1 GB limit. You can actually get Mailcow below 1 GB RAM if you disable ClamAV and tweak rspamd and SOGo a bit, but you still need memory for the operating system. So for all aims and purposes, 2 GB is going to be the minimum for Mailcow and probably any modern fully-featured groupware solution.

 If you need to fit into 1 GB of RAM (effectively ~800 MB accounting for kernel and background services), your best bet is to just run a bare Postfix and Dovecot (which might consume 100-200 MB each). You‘ll also want to have a few hundred MB of free space that the kernel can use as cache etc. and you don‘t want to max out your RAM because things tend to get quite sluggish when the kernel starts swapping to disk once you are out of RAM.

**Comment by Adorfer** [comment]
Please make some kind of FAQ section in the doc about RAM&CPU footprint of MTAs with effective antispam. (i run frequently into discussions "why mailcow is a RAM-hogger", explaining the above over and over again.)

**Comment by andryyy** [comment]
That's a good idea.

**Comment by turbcool** [comment]
> If no, then can you please suggest me any light opensource mail server? :(

I suggest [Mailu](https://github.com/Mailu/Mailu)

**Comment by andryyy** [comment]
I also found mox to be a cool alternative that's pretty lightweight: https://github.com/mjl-/mox
