### ISSUE TITLE
MX backup-only mailcow instance

### ISSUE THREAD

**Issue by Xenthys** [mailcow/mailcow-dockerized#3345]
**Is your feature request related to a problem? Please describe.**
As briefly discussed on IRC, a few people (including me) would love to setup a backup MX without having all the fluff of a fully fledged installation. Components like SOGo are very nice, but have no use in a backup MX that mostly requires holding received emails to transfer them back to the main server once it gets back up.

**Describe the solution you'd like**
A partial solution would be a way to have SOGo removed from the equation. Though it can be stopped after being started once as mentioned in issue #1955, this isn't very optimal. If a fully-fledged solution was possible, it might be possible to lighten a few other parts. It would also be nice to have a way to synchronize a few settings from the main server as well as disable their edition on the backup, aka. "this is a backup node, its settings can't be changed directly" if you follow me.

**Additional context**
Consider this as a low priority, backup MX don't fit everyone's needs and remain niche enough. On top of that, if the features described above were to be implemented, I assume it's not going to be as easy as it may look like from the outside. Best moos!

**Comment by julianwachholz** [comment]
I was recently forced to move my host because of hardware instabilities and this missing feature meant I had no emails for a couple hours.

**Comment by andryyy** [comment]
Nothing holds you back from installing a backup MX. It works as of today (you can setup mailcow to relay a domain).

You cannot blame mailcow for this, really....

**Comment by mkuron** [comment]
> I had no emails for a couple hours

You shouldn't have lost any messages because of this though. Servers will attempt to re-deliver messages for a few days, so as long as your server is not down for extended periods of time, messages will not be lost, only delayed.

A backup MX would only eliminate this delay. Your users obviously can't access their messages while the main MX is down and messages are typically re-delivered within a few hours of the server coming back up, so they probably don't care too much about a backup MX. Keep in mind that running a backup MX costs time and money too, so for most Mailcow installations, having a backup MX won't really be worth it.
