### ISSUE TITLE
Multiple SMTP Ports? 

### ISSUE THREAD

**Issue by RogerSik** [mailcow/mailcow-dockerized#3365]
**Is your feature request related to a problem? Please describe.**
We want another server to relay to mailcow. But the SMTP Ports are blocked. An earlier workaround with none mailcow server was to add SMTP additional port example 54320

**Describe the solution you'd like**
In mailcow.conf add additional port to

SMTP_PORT=25,54320

to make SMTP listen under port 25 **AND** port 54320

**Comment by mkuron** [comment]
It's impossible to simply do that with a variable because Docker Compose doesn't support that kind of syntax. You can however just add `- "54320:587"` here:
https://github.com/mailcow/mailcow-dockerized/blob/49d4f6f89789db89603f0d15dcc19477f3330a11/docker-compose.yml#L266-L269

Alternatively, you could create a user account on your Mailcow, disable sender address checking and do authenticated SMTP on ports 587 or 465.

**Comment by RogerSik** [comment]
Thanks! That works and helped. :) 

> Alternatively, you could create a user account on your Mailcow, disable sender address checking and do authenticated SMTP on ports 587 or 465.

Sadly this ports (and port 25) are blocked by the hoster. Because of that we want to use a none common port
