### ISSUE TITLE
Disabling 2FA from Command Line

### ISSUE THREAD

**Issue by FrinkMan** [mailcow/mailcow-dockerized#3393]
I'm not sure if this is the right place to post this, but I'm having an issue. My phone crashed on me, and I had 2FA enabled on my admin account in Mailcow, and I need to disable it now. Is there a way to do this from the command line? I have full access to SSH.

**Comment by MAGICCC** [comment]
See here:
https://mailcow.github.io/mailcow-dockerized-docs/debug-reset_pw/#remove-two-factor-authentication

**Comment by Braintelligence** [comment]
https://mailcow.github.io/mailcow-dockerized-docs/debug-reset_pw/#remove-two-factor-authentication

Next time please read the docs first.

**Comment by FrinkMan** [comment]
Much facepalming. Sorry for the hassle!

**Comment by vkukk** [comment]
Documentation suggestion to reset 2FA is not optimal if admin account is shared. Resetting means everybody has to have new shared secret. If you have access to database, instead of deleting tfa, check/print existing totp secret and enter it into Google Authenticator. Now you can log in again with TOTP.

**Comment by djdomi** [comment]
> Documentation suggestion to reset 2FA is not optimal if admin account is shared. Resetting means everybody has to have new shared secret. If you have access to database, instead of deleting tfa, check/print existing totp secret and enter it into Google Authenticator. Now you can log in again with TOTP.

I agree to this point, the original request isn't such bad. I mean, myself added the browser as an option. But this fails on android and a fail back to the TOTP which is still configured is not (easy) available. I would suggest, to add a button to choose which Authenticator should be used, instead of automatic selecting the last installed one - or easier said: let the user choose and not the system.
