### ISSUE TITLE
Please help me with SPAM

### ISSUE THREAD

**Issue by petarkozic** [mailcow/mailcow-dockerized#3394]
I have a problem at the one mailcow server. Server sending SPAM and I can't figure from which user get that.

I'm using Mikrotik router with NAT, public IP was NAT-ed to private IP and in the log I only see localc router IP address.
In mail queue I can see too much mails from same sender as on screenshot below.
On server I have two domains.
How can I fast found where is problem and who send spam?

<img width="1290" alt="Screenshot 2020-03-07 at 22 55 19" src="https://user-images.githubusercontent.com/17702869/76153038-c9950880-60c6-11ea-8770-6fb89b78c38b.png">
<img width="1279" alt="Screenshot 2020-03-07 at 22 55 29" src="https://user-images.githubusercontent.com/17702869/76153042-cdc12600-60c6-11ea-960a-fcbf86175b16.png">

Thank you.

**Comment by Adorfer** [comment]
This is not a valid bug report, it's missing the template. 
For community support please consider e.g. the TG channel. 

guess: you opened port 25 from external/WAN and forward it to your mailcow?

https://github.com/mailcow/mailcow-dockerized/blob/b5c844d70496aa01dd1ff31e64db79c87926aa77/data/conf/postfix/main.cf

        mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 [fe80::]/10 [fc00::]/7

-> All senders coming from your mikrotik-GW are considered as MYNETWORK, due to the RFC1918 address. 

Setup will not work this way until you exclude the GW address from mynetworks.

**Comment by mkuron** [comment]
Actually, this looks like your router is translating the address on incoming packets as well, making them all appear as coming from your router. This makes your Mailcow an open relay. Please stop Mailcow immediately until your router configuration is fixed.
