### ISSUE TITLE
Compliance and record keeping

### ISSUE THREAD

**Issue by sam2kb** [mailcow/mailcow-dockerized#3430]
Here's a problem, say I need to keep all email messages (incoming and outgoing) for a period of 5 years for compliance. 

Is there a way to completely prevent email deletion, or is there an easy way to setup a read-only copy that will gather and keep the messages forever?

**Comment by shiz0** [comment]
Hi!
Please be aware, that this is an issue tracker, NOT a support channel!
For community support, please join our Telegram Channel: https://t.me/mailcow, or board: https://community.mailcow.email/
Furthermore, it's invalid due to the template beeing ignored/discarded.
So I'm closing this, sorry.

As for your request, you could set up a second instance or mailserver for mirroring, or develop a backup and archiving strategy which meets your requirements.
For further discussion, please use the ways mentioned above.
