### ISSUE TITLE
Decoupled Database container to use manages database services

### ISSUE THREAD

**Issue by asifkhanpathan** [mailcow/mailcow-dockerized#3470]
### **Problem:-**
mysql container is mounting socket on the volume and all other services are using that socket to connect to database container which is very tightly coupled and we can not use managed database service like aws RDS.

**### Proposed Solution**
1. add a environment variable DBHOST=mariabd
1. replace all socket connection to hostname connection like mysql -h ${DBHOST}

**Comment by andryyy** [comment]
SQL != SQL. Does it fit mailcows requirements? :) 

You can mount a socket using `helper-scripts/docker-compose.override.yml.d/EXTERNAL_MYSQL_SOCKET/docker-compose.override.yml`. This socket can be a proxysql or something like that (https://github.com/sysown/proxysql). Works, but is unsupported.

**Comment by asifkhanpathan** [comment]
hi thanks for help 

i am sorry that i didn't test out override but my point was that if we are using docker to manage services that means we are supporting micro service architect that it should be easy to leverage other solution and easy to swap service .
i did manage to change socket connection to host connection and it work perfectly wit aws RDS and local mariadb container it did not breaks backward compatibility and introduces new flexibility to the project that is why i am suggesting this method. and i am not very much comfortable with git pull request with git :-) so i am limited there  but i can provide all the patch i have done so far
once again thanks for great project

**Comment by andryyy** [comment]
We previously had TCP connections but prefer sockets now. Will not be reverted, sorry. 

The socket solution works fine. :)

Keep in mind there is ZERO support for external SQLs. We have a working stack with pinned versions for every installation. That's why it works so painlessly everywhere. :)

There are also several triggers and views, that need to be validated. JSON needs to work properly with the syntax used in mailcow, too. There are several obstacles with JSON and different SQL versions. The returned values must match exactly with those returned by MariaDB used in mailcow. The SQL modes must match etc. 

SQL cannot be replaced with any other SQL. SQL is very individual in its behavior between versions, derivates and configurations. 

Don't replace it, if you want to be sure it works. We don't store TB of data there. Just leave it as it is. It is configured to not be heavy on RAM either. :)
