### ISSUE TITLE
Add API method to send emails and to get status of their delivery

### ISSUE THREAD

**Issue by dragoangel** [mailcow/mailcow-dockerized#3478]
**Is your feature request related to a problem? Please describe.**
Now emails can be send only over SMTP without any easy option to check that they was been send|waiting in queue with temp error|bounced. Ability to send mail from API will give option to use mailcow with any self developed webservice.

**Describe the solution you'd like**
We could look how this already done by other delivery services, e.g.: mailchimp, mailgun and so on.
There endless possibility to enhance in future if this function latter will be used by many people like:
templating, url tracking, push notifications etc., but for beggining simple 2 methods is good start to check how this will be used by users.

**Comment by mkuron** [comment]
Is there an established REST/SOAP/... API that Mailcow could implement for this? I am not aware of one and I don't think it makes sense to invent our own. No standard application would be able to use it.

**Comment by phillipplum** [comment]
A few days ago I found open source software: [Postal](https://github.com/postalhq/postal). That would be an alternative if you are looking for something like Mailgun or Sendgrid.
I don't think it would fit in mailcow.

**Comment by dragoangel** [comment]
@phillipplum thanks, somebody (maybe even you) give me link to Postal in mailcow offtopic. I already installed it and it works.
@mkuron Yes standard applications would be able to use it. Only that what been developed specially to use such API. As there is already exists another opensource software which specially designed for this, this FR can be closed. Thanks.

**Comment by asgardianec** [comment]
Hello colleagues, 

I am running the Mailcow server on virtual server. Also I have ElasticMail as SMTP server because I use it for tracking emails. But I want to get rid of ElasticMail as it making troubles sending the emails. However I need a reliable tool to monitor my e-mails for status, delivered or not, bounced or not and etc. Can you recommend one ? It would be nice if it works as API inside the Mailcow. Greylog or opensearch looks like complicated solution. Thank you in advance.
