### ISSUE TITLE
Unicode mail account name

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [mailcow/mailcow-dockerized#3498]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
Adding the mail address `dфҿ@example.com` (in my case as alias) containing Greek Unicode characters causes an error telling:
```quote
Alias address dфҿ@example.com is invalid
```

**Docker container logs of affected containers**:
*Does not seem to require logs...*

**Reproduction of said bug**:
Go to alias page of Mailcow web interface in the mail setup section and add a mail address alias for a mail containing Greek letters.
If I correctly understood https://en.wikipedia.org/wiki/International_email , my letters should be allowed in mail addresses.

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | UBUNTU |
| Is Apparmor, SELinux or similar active? | Nope |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | NaN |
| Server/VM specifications (Memory, CPU Cores) | 8GB, 4 cores |
| Docker Version (`docker version`) | 19.03.6 |
| Docker-Compose Version (`docker-compose version`) | 8d51620a |
| Reverse proxy (custom solution) | Apache 2 |

**Comment by andryyy** [comment]
Biggest show stopper is Dovecot not advertising smtputf8 for me.

I think we should even disable smtp utf8 in Postfix completely, until this is considered by Dovecot devs.

I am unsure if this will ever be part of Dovecot, tbh.

What are your thoughts, @mkuron?

**Comment by mkuron** [comment]
I think we enabled it after #2774 when someone said that a message with UTF8 _content_ was bounced. According to http://www.postfix.org/SMTPUTF8_README.html and my understanding, it should only matter for envelope addresses though. So we might as well disable it as long as it doesn‘t fully work. We should show a specific error message in the web UI when someone tries to create a mailbox with characters outside the ASCII range.

I know this is disappointing to people speaking non-ASCII languages, but certain parts of the computing world still don‘t (and probably never will) support Unicode sufficiently well to be usable. This is usually either due to backward compatibility requirements or due to ambiguities (a Unicode string might look identical, but not be the same byte string). E-mail, being four decades old, certainly is such a historic protocol, but the same problem is also found in e.g. domain names and file names.

There is another reason though why you should limit your email addresses to ASCII: it‘s the only way to be sure that your address can be typed on every keyboard found anywhere on this planet.

**Comment by TheOneWithTheBraid** [comment]
I seed the problem with Unicode characters and EAI but shouldn't the decision to use it - or not - be left to the users/admins of the Mailcow server?

> I know this is disappointing to people speaking non-ASCII languages, but certain parts of the computing world still don‘t (and probably never will) support Unicode sufficiently well to be usable.

It would be great if such a good open source project like Mailcow was making an example by supporting such mail addresses. I checked out some proprietary mail providers and they all supported *sending* mails to Unicode addresses.

> There is another reason though why you should limit your email addresses to ASCII: it‘s the only way to be sure that your address can be typed on every keyboard found anywhere on this planet.

Hmm, I disagree. I wanted to add this Mail address as some people were *unable* to use the Latin transcription on their keyboard.

I moreover tried to to fix this by a domain-wide redirect (all @example.com redirected to me@domain.tld) but still any address containing Unicode characters silently disappeared.

I am really looking forwards to see Unicode support, even for other languages.

**Comment by mkuron** [comment]
> It would be great if such a good open source project like Mailcow was making an example by supporting such mail addresses.

Mailcow does not develop Postfix or Dovecot. As long as UTF8 support is incomplete there, we can't do anything.

**Comment by andryyy** [comment]
I don't see it widely used in the future. Deliverability and client compatibility is a big problem.

**Comment by TheOneWithTheBraid** [comment]
@andryyy I see but this does not mean there might not be a eventually huge group of people trying to get this working.

According to the dovecot mailing list from April 2019, there theoretically is support which has successfully been enabled at https://github.com/progmaticltd/homebox .

Here are the corresponding configs:

* https://github.com/progmaticltd/homebox/tree/master/install/playbooks/roles/dovecot/templates/conf.d
* https://github.com/progmaticltd/homebox/tree/master/install/playbooks/roles/postfix/templates

**Comment by mkuron** [comment]
According to http://dovecot.2317879.n4.nabble.com/SMTPUTF8-support-td67266.html, Homebox uses some trick with a special LDAP schema to map non-ASCII addresses to something Dovecot can understand. That's just a hack, has weird side effects, and we wouldn't even be able to use it because we don't use LDAP. It _might_ be possible to adapt this trick to our SQL queries, but it would be an even messier hack, so we are definitely not going to do that.

Until Dovecot implements SMTPUTF8 over LMTP, Mailcow cannot support mailboxes with non-ASCII addresses.

**Comment by andryyy** [comment]
That's a very hacky workaround, you won't be happy with it.

We will wait until LMTP supports UTF8.

**Comment by Lozik** [comment]
Just a another consideration, why it might be interesting to have that utf8 support in addresses, even if one sets the rule to only allow asci-characters in account names:
There are names with non-asci-characters like René, André or Loïc. Even if one then follows the best practice to add account names in the asci-version of the name (i.e. rene@example.com, andre@example.com, etc.), some people will perhaps try to send emails to rené@example.com (for whatever reason). At the moment, those emails will then be rejected. I understand that there are some technical hurdles, e.g. Dovecot, which makes it hard/impossible to correctly have utf8 account names, but how is it with aliases? Wouldn't it work to have utf8 aliases, at least, as this should 'only' be postfix? Or does that, again, causes problems with Dovecot?

**Comment by diancho** [comment]
Good question, Lozik.
 I was wandering about this too.
The webmail and clients software must be able to use aliases for login.
