### ISSUE TITLE
apache config template leeds to swift mailer error regarding to CN Peer ssl certs

### ISSUE THREAD

**Issue by horvan** [mailcow/mailcow-dockerized#3504]
Installed mailcow by using the template for apache from the docs, Now when I send a mail by using swift mailer I got an error like this:
`
Swift_TransportException: Connection could not be established with host mail.domain.net :stream_socket_client(): Peer certificate CN=`autoconfig.domain.net' did not match expected CN=`mail.domain.net'
--
Any Ideas on how to solve this?

`

**Comment by andryyy** [comment]
Your mailcow certificate is not correct. It is missing a name. Probably because you use a reverse proxy and mailcow cannot requests a certificate via LE or you simply didn't copy the certificate from an external location into mailcow. 

I don't get why people totally ignore the issue template and don't give a damn to read even the first three lines. It's frustrating.

Read through the docs again or even the issue template and check how to get support, please.
