### ISSUE TITLE
SOGo redirects to local IP

### ISSUE THREAD

**Issue by jadyndev** [mailcow/mailcow-dockerized#3507]
After login SOGo tries to redirect to the web-mail page. Unfortunately it redirects to the local IP of the Server and not the domain. In my case SOGo is located behind a reverse proxy and the site can't be loaded. 
For example:
example.com/SOGo redirects to 1.2.3.4/SOGo/so/[address]/Mail/view

If you change the URL manually to the domain SOGo works fine, until you log out and want to log in again.

I've looked through the config files and I've not found an option to set the domain or hostname. Is there any way to prevent this?

**Comment by DatAres37** [comment]
Have you checked the reverse proxy documentation? https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/

**Comment by jadyndev** [comment]
Changed some options according to the tutorial, it works now. Thank you.

But I don't no why it works...

**Comment by Torxed** [comment]
This is one of those threads that keep popping up while searching for this particular issue.

So I'll add some clarification on what OP probably did to solve it, that has worked for me in the past - if you put your own reverse proxy in front of Mailcow:

The issue is most likely because the `Host` header being forwarded to Mailcow is wrong, most likely the reverse proxy is forwarding the "upstream server" configuration rather than the hostname used to access the service.

In [caddy](https://github.com/caddyserver/caddy) this would happen if this config was used:
```
mail.domain {
	@mail host mail.domain
	handle @mail {
		encode zstd gzip
		reverse_proxy https://1.2.3.4:8443 {
			header_up X-Forwarded-Port {http.request.port}
			header_up X-Forwarded-TlsProto {tls_protocol}
			header_up X-Forwarded-TlsCipher {tls_cipher}
			header_up X-Forwarded-HttpsProto {proto}
			header_up Host {upstream_hostport}
			transport http {
				tls_insecure_skip_verify
			}
		}
	}
}
```

And the fix would be:
```diff
  mail.domain {
  	@mail host mail.domain
  	handle @mail {
  		encode zstd gzip
  		reverse_proxy https://1.2.3.4:8443 {
  			header_up X-Forwarded-Port {http.request.port}
  			header_up X-Forwarded-TlsProto {tls_protocol}
  			header_up X-Forwarded-TlsCipher {tls_cipher}
  			header_up X-Forwarded-HttpsProto {proto}
-  			header_up Host {upstream_hostport}
+  			header_up Host mail.domain
  			transport http {
  				tls_insecure_skip_verify
  			}
  		}
  	}
  }
```

It's an easy error to fix if you know what you're looking for, but hopefully this will be useful for those that find it confusing.

*(apologies for posting in an old issue, but again, it's the one post that keeps popping up when searching for this issue)*
