### ISSUE TITLE
Outgoing TLS policies suggestions on base of mails which are sent

### ISSUE THREAD

**Issue by 8ear** [mailcow/mailcow-dockerized#3550]
Hi,
A new feature request for discussion about TLS outgoing policies.

I want to use TLS outgoing policies. But it is very hard to know which domain and which settings are required.
But every day postfix connects already to different mail domains.
So my proposal is all domains where postfix deliver mails, should be added as an dynamic entry at the TLS outgoing policies. So the administrator can see which domains were connected and if it was encrypted.
Further should the administrator have the possibility to create a static entry from an dynamic entry and can so overwrite the setting.
If you are in the static (or currently in a new TLS policy) view the administrator should be able to click on a test button to the test which possibilites are available? encrypt?, dane? fingerprint? ,....

If you have any other great ideas comments it.

Thanks to all

**Comment by andryyy** [comment]
Today company X supports TLS 1.2 with a medium cipher.
Next month they suddenly support TLS 1.3 and DANE. You'd want to switch to dane-only and TLS 1.3.
You will still connect to their server with TLS 1.2 because of your pinning.

You probably want to enforce outgoing TLS for that mailbox. Or all mailboxes. And enforce TLS 1.3 where possible? If they don't support 1.3, don't create a policy at all, perhaps pin a very secure cipher.

If it's super, super, super critical information, you probably know exactly which protocols and ciphers your remote supports and can create policies accordingly.
