### ISSUE TITLE
OCSP stapling

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#3615]
Hello,

Could 'OCSP stapling' (for webserver only) perhaps be enabled (by standart) in your configurations? :)

Thanks.

**Comment by mkuron** [comment]
We had a pull request for stapling (not must-staple) two years ago: https://github.com/mailcow/mailcow-dockerized/pull/1688. We didn’t go ahead with it because some people had concerns. I don‘t think there is any risk as Nginx should just stop stapling when the OCSP server is unreachable, but I haven‘t tried.

OCSP is of limited use though as browsers tend to only check against their internal revocation databases (OneCRL, CRLset, ...) nowadays. Plus our certificates are only valid for 90 days, so the damage a compromised certificate can do is limited to that time. Of course, OCSP stapling reduces it to one day, but it‘s still much better than 3 years or whatever was common on certificates before Let‘s Encrypt.

**Comment by omexlu** [comment]
Hm, okay, maybe your team think about it again :)

**Comment by andryyy** [comment]
Please decide this on your own for your personal installation. 

I agree with mkuron here. :)
