### ISSUE TITLE
Support Group-Office

### ISSUE THREAD

**Issue by ThauEx** [mailcow/mailcow-dockerized#3632]
Currently SOGo is used as groupware etc., I just found [Group Office](https://github.com/Intermesh/groupoffice), which is similar, but it's supporting things like JMAP (quite nice for mobile sync etc.). It's using PHP and MySQL, like the frontend, so it would be less load (maybe) and less dependencies for the whole stack.
[Here is a manual](https://www.group-office.com/wiki/Mailserver), how to integrate it into dovecot, sieve etc..

I have not tested the integration, because I don't know how mailcow is internally configured and working and if Group Office is compatible to the current setup.

**Comment by mkuron** [comment]
That's an interesting piece of software. It didn't even exist back when Mailcow started, but seems like a relatively complete SOGo alternative. CalDAV and CardDAV didn't seem to work in the demo instance though, and its EAS support comes from z-push, which I recall as not being particularly reliable (but SOGo's EAS is far from perfect too). One of SOGo's advantages is still its Mozilla Thunderbird integration, but that might be replicated with https://github.com/jobisoft/TbSync (haven't tried).

SOGo integrates with Mailcow in multiple places, but that can probably be sorted out without too much work. The main difficulty I see in switching to a different groupware solution is migration of data and keeping sync working without reconfiguring clients and devices. And since SOGo continues being actively developed and Group Office doesn't have any extra features we desparately need, I don't see an urgent reason to take risks there.

**Comment by ThauEx** [comment]
Thanks for your comment.
Would it be possible to offer both (one active at the time) without any migration? Or at least some kind of tutorial how to switch?
In my case SOGo is not really used, because I only need the inbox and JMAP would be really nice to have. But this is only my case.

**Comment by andryyy** [comment]
Not planning to write a guide or integrate it as we integrated SOGo.
