### ISSUE TITLE
Wildcard mail domains

### ISSUE THREAD

**Issue by sosnik** [mailcow/mailcow-dockerized#3734]
**Is your feature request related to a problem? Please describe.**
At the moment, it is not possible to specify a wildcard mail domain, such as `*.example.com`.

**Describe the solution you'd like**
I'd like to achieve a result akin to what you get with Fastmail.
With Fastmail, each user account is configured to receive email on a corresponding subdomain of the chosen mail domain.

`user@example.com` will receive all mail addressed to `anything@user.example.com`.
When new users are added, routing is configured automatically.

I know I can create wildcard `*.example.com [...] MX mx.example.com` entries in my DNS, and subsequently add a new subdomain in the mailcow config every time I add a user, but I'd rather this be a more elegant and automatic solution.

How do I achieve this?

**Additional context**

See also #2077. In this issue, the author wanted to create wildcard aliases as `*user@example.com`. I'm looking for a wildcard solution on the other side of the \@.

**Comment by patschi** [comment]
I don't believe that this is possible as Postfix, Dovecot and SOGo needs to support this as well and I doubt they support this OOTB. I think one possible way for you might be solving this by automatically triggering the API to make necessary changes for you.

**Comment by dragoangel** [comment]
Hi, this clearly not standard, I really doesn't see usecases why people will need this. Could you please explain what a point to user has own subdomain?
To add list of software which need to support this I want add rspamd.
As @patschi said you can configure script to trigger mailcow API which will create domain alias for you for example. Want to note that domain aliases has own limitations, for example email aliases doesn't included in domain aliases.

**Comment by Adorfer** [comment]
> Could you please explain what a point to user has own subdomain?

that's a service some traditions internet access providers (did?) offer by default. like "free.fr". Every user received a "catchall"-subdomain with his/her sitename. (mostly it was identical to the offered dyndns-name)

**Comment by dragoangel** [comment]
Never saw such option in provider that I was saw/used. Yes I understand that this catch-all subdomain.

**Comment by wedi** [comment]
**postfix** does support this. It's a matter of adjusting `virtual_mailbox_domains`, `virtual_mailbox_maps`, `virtual_alias_maps` to return a valid result if an unknown domain with matching wildcard is checked.
**dovecot**, needs to return the required values on `userdb` and `passdb` queries for a matching subdomain.
**rspamd** gets the mail after postfix accepted it so that's probably not a problem but it might depend on the exact configuration mailcow uses.
I have no idea about **SOGo** but if it doesn't, I think it would be ok to just document that this configuration does not work with SOGo. It does work with **roundcube** out of the box as it relies on dovecot/postfix.

**Comment by Permanently** [comment]
Is this something we will ever see movement on? It'd be good to have this as a feature.
