### ISSUE TITLE
Self-Registration User Portal

### ISSUE THREAD

**Issue by drizzo0** [mailcow/mailcow-dockerized#3840]
Hi,

I've checked on the issues but I haven't find something similiar..
It would be a cool feature to have a portal to enable self-user registration to allow anyone who want to create a mailbox..
This will be cool for anyone who wants to start a public mail service on his own server..

**Comment by andryyy** [comment]
A public mail service can be very, very hard to manage. It WILL be used for spam.

I don't support this idea. 

You can use the API to bundle it with your own registration system.

**Comment by kiuX89** [comment]
Hi, I would also like this function to be activated or deactivated at any time. Do you think this feature could be integrated into mailcow?

**Comment by d1hydr0gen** [comment]
i want this feature too

**Comment by mwa85** [comment]
I also think this should be build into mailcow, as a global variable and then also on domain level so that it would be possible to only allow on 1 out of 2 domains on the same mailcow installation.
In regards to the comment about it would be hard to manage and spam would be an issue this should of course be a opt-in feature that by default is disabled (reason for a global "Self-Signup" toggle).

It would be a nice and huge functionality.

+1

**Comment by Cisco30** [comment]
i want this feature too
