### ISSUE TITLE
Outlook email DNS Resoultion error

### ISSUE THREAD

**Issue by jc565** [mailcow/mailcow-dockerized#3862]
Hello Everyone. 

I have an issue sending to microsoft.  I do not beleive this is the standard issue that is well documented that requires a mail relay. I think I have a DNS issue on my end.  

when i send an email to an outlook address, i get the following reply:

```
`This is the mail system at host mail.myserver.com.

####################################################################
# THIS IS A WARNING ONLY.  YOU DO NOT NEED TO RESEND YOUR MESSAGE. #
####################################################################

Your message could not be delivered for more than 4 hour(s).
It will be retried until it is 5 day(s) old.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<receiver@example.com>: Host or domain name not found. Name service error for
    name=example-com.mail.protection.outlook.com type=AAAA: Host not found,
    try again` 

```

I CAN resolve the address from both the host, and the acme instance.    I have actually been able to get through to microsoft after joining all their programs and they have told me that my IP is whitelisted and there should be no problem receiving my emails on their end.

I have searched quite a bit but not found an issue to this exact problem.

**Comment by jc565** [comment]
im not sure what the "invalid" tag is supposed to mean

**Comment by andryyy** [comment]
![image](https://user-images.githubusercontent.com/2972950/99548779-4c41c780-29b9-11eb-9906-f2acffb79964.png)

Even if you consider it a bug, you simply removed the whole issue template.

You also didn't search for the problem in the tracker to check for the answer: network issues. Firewall on local machine, firewall in front of mailcow and misconfigured, other stuff preventing your container to reach the DNS root servers. Some information is being asked in the issue template.

**Comment by jc565** [comment]
first,   i have seen no template. no template was present when you click create issue.  so unless its in another thread somewhere, i have no idea what said template would be. 

Second off, I have searched top to bottom, up and down, trying to fix this issue for 3 months.  I have tried every trick I can find on the internet (hence how i learned to do the dig commands in the first place) .

again, the host resolves the dns address.... the acme container resolves the address.... my network firewall has all outlook servers whitelisted...the host does not have a firewall at all..

if you would provide a template I would be happy to fill it out, but I can not find anything misconfigured in my setup and would consider this a bug.

**Comment by patschi** [comment]
> first, i have seen no template. no template was present when you click create issue.

Can you please let me know what you can see when you create a new issue? You should see following:
![image](https://user-images.githubusercontent.com/2029878/99576360-c8480980-29d1-11eb-8c03-80d598a5e900.png)

And both options should give you a very detailed template, like at "Bugs":
![image](https://user-images.githubusercontent.com/2029878/99576419-ddbd3380-29d1-11eb-81dd-fc6e7765ac05.png)

**Comment by jc565** [comment]
the template does now appear when i click bug report. was not there the
first time i made the issue.

Im done with mail cow. going back to my standard postfix / dovecot stack.
nothing but issues and the developer is more interested in telling you why
your post is done incorrectly than pointing you towards a fix.

**Comment by patschi** [comment]
> the template does now appear when i click bug report. was not there the first time i made the issue.

As you can see [here](https://github.com/mailcow/mailcow-dockerized/commits/master/.github/ISSUE_TEMPLATE/Bug_report.md) the template exists since Oct 2018, so it's nothing new - and also previous issues match the bug reports. So maybe it was a GitHub or browser-side issue.

It might sound rough, templates are there for a reason - just like in other GitHub projects. It's quite handy to see issues in the same format, with some additional information asked for, to guide through the issue/bug.

We - including myself as you can see in the history above - have invested quite some time to get a general template together. So I hope you also understand that ignoring the template (I know, you've apparently not seen the template) is like an impolite punch in the face to ignore stuff people invested time in. Specially when this happens over and over again from so many people.

However, if you still have your mailcow: The first thing coming in my mind might be that you're server does not have IPv6 support and you didn't disable IPv6 - see [docs here](https://mailcow.github.io/mailcow-dockerized-docs/firststeps-disable_ipv6/).

**Comment by jc565** [comment]
would of absolutely filled out the template if it was present when i first
submitted.
