### ISSUE TITLE
mailcow uses an outdated version of Nextcloud

### ISSUE THREAD

**Issue by 74k1n984ckmyp21v4cy** [mailcow/mailcow-dockerized#4009]
## Summary

I know Nextcloud isn't the main focus of mailcow, but the mail application in the current Nextcloud releases feels better than SOGo, so I think helper-scripts/nextcloud.sh should use the latest version of the current major release and not just the latest version of Nextcloud 19.
Changing the links from "https://download.nextcloud.com/server/releases/latest-19.tar.bz2" to "https://download.nextcloud.com/server/releases/latest.tar.bz2" would use the latest version of Nextcloud (which is as of now Nextcloud version 21).

## Motivation

Users could benefit from the latest version of Nextcloud without having to update manually.

**Comment by mritzmann** [comment]
> which is as of now Nextcloud version 21

Nextcloud 21 is the latest version, but is not yet distributed as an update (even by Nextcloud in the stable channel). In a productive environment, I would highly recommend using stable, so Nextcloud 20.

see: https://github.com/nextcloud/updater_server/blob/4c344622668b639cb3711796ef7331f426bf189d/config/config.php

(This is common practice at Nextcloud. The new major version is announced as new, but nextcloud itself is hesitant. You can almost say every new Major version is a secret public beta 😄)

**Comment by intxcc** [comment]
Hi @mritzmann 

there was a commit that bumped the NC version to 20.
https://github.com/mailcow/mailcow-dockerized/commit/184963f76080e5fbfe6fbac10eb316ddf51026f9

The installation fails with this script! (They probably changed the syntax for the occ cli of Nextcloud in version 20)
What worked was installing version 19 and then in the NC UI update to 20.

I'd suggest downgrading the helper script, because it is currently not working.

Or should I open a new issue for that?

Best,
Marvin

**Comment by intxcc** [comment]
This is what happens with the current scipt
![grafik](https://user-images.githubusercontent.com/17449580/114078921-d7105980-98a9-11eb-83a2-fe654d9cfd07.png)

**Comment by TheSupraLife** [comment]
Any updates on this issue ?

**Comment by MAGICCC** [comment]
> 
> 
> Any updates on this issue ?

Looks like it got fixed in https://github.com/mailcow/mailcow-dockerized/commit/496f4ad81f39041c99d531b9825df0f952072a60
Are you sure that you are using the latest nextcloud.sh in the helper-script folder?
