### ISSUE TITLE
If port 25 is closed, how to configure to send mail using TLS port

### ISSUE THREAD

**Issue by bigbeef** [mailcow/mailcow-dockerized#4199]
If port 25 is closed, how to configure to send mail using TLS port

**Comment by waja** [comment]
aehm ... you did not fill out the template? This is a question, how about doing this at https://community.mailcow.email/?

**Comment by MAGICCC** [comment]
Closed due not respecting the issue template - not a bug or enhancement
We don't provide support here on GitHub
Either ask in our [telegram channel](https://telegram.me/mailcow) or in [our forum](https://community.mailcow.email/)

Basicly not really possible because you need to connect to port  25 to the other server. Either ask your host/ISP to unblock or use a relay
