### ISSUE TITLE
Backup Script Failure on Docker 20.10.8

### ISSUE THREAD

**Issue by leonyannnick** [mailcow/mailcow-dockerized#4246]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X ] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X ] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
While I was trying to backup my server, an error occurred. When the backup script tries to backup the MySQL database, the script stops. I was able to reproduce this error on another server with the same Docker version (20.10.8). 
I have another Mailcow instance running Docker 20.10.7 on another server, this one the backup works fine. My guess is that the new Docker version requires a different syntax when using Docker. Can anyone reproduce this error, or even have a solution for it?

## Logs
zzzz@zzzzzz:/docker/   zzzz    /mailcow-dockerized/helper-scripts# ./backup_and_restore.sh backup mysql
Backup location (absolute path, starting with /): /mnt/test
Using /mnt/test as backup/restore location.

Found project name mailcowdockerized
Using SQL image mariadb:10.5, starting...
docker: invalid reference format.
See 'docker run --help'.

## System information

| Question | Answer |
| --- | --- |
| My operating system | Linux Debian Buster |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM|
| Server/VM specifications (Memory, CPU Cores) | 16GB RAM, 4 cores |
| Docker Version (`docker version`) | 20.10.8 |
| Docker-Compose Version (`docker-compose version`) | 1.29.2 |
| Reverse proxy (custom solution) | Nginx |

Thanks in advance.

**Comment by andryyy** [comment]
You may have zombie containers, check `docker ps -a`.

It works no matter the Docker version.

**Comment by leonyannnick** [comment]
Thanks for the tip. 
If you use a network name that doesn't match the following syntax the error occurs: 
`docker network ls -qf name=^${CMPS_PRJ}_mailcow-network$`

In the end a mistake from me, so can be closed here.

**Comment by BlackWolfDEsign** [comment]
Hi i have an similar issue:

`Using SQL image mariadb:10.5, starting...
[00] 2022-01-04 09:13:14 Connecting to MySQL server host: mysql, user: root, password: set, port: not set, socket: /run/mysqld/mysqld.sock
[00] 2022-01-04 09:13:14 Failed to connect to MySQL server: Access denied for user 'root'@'172.22.1.14' (using password: YES).
mariabackup based on MariaDB server 10.5.13-MariaDB debian-linux-gnu (x86_64)
mariabackup: Can't change dir to '/backup_mariadb/' (errno: 2 "No such file or directory")
[00] 2022-01-04 09:13:14 can't my_setwd /backup_mariadb/
chown: cannot access '/backup_mariadb': No such file or directory
/bin/tar: /backup_mariadb: Cannot stat: No such file or directory
/bin/tar: Exiting with failure status due to previous errors
`

I renamed my containers (added a prefix) and **docker network ls -qf name=^${CMPS_PRJ} _mailcow-network$** did not find it. So I added **. *** as a test case, but it has no effect. (in bash it works)

Which IP is that: **172.22.1.14**? My mysqlcontainer has a different IP. (8 instead of 14)
