### ISSUE TITLE
Roundcube displaying Mailcow Admin when allowing remote resources

### ISSUE THREAD

**Issue by itmunky** [mailcow/mailcow-dockerized#4312]
I followed the documentation here; https://mailcow.github.io/mailcow-dockerized-docs/third_party-roundcube/ 
to enable roundcube webmail on my mailcow instance. 
All works fine however when i click on the "Allow" option for remote resource sin an email, i can see the mailcow admin dashboard in the reading pane! 

![image](https://user-images.githubusercontent.com/23394753/139803617-332f5f2b-6237-459f-8f8d-47ca26ddfaa4.png)

![image](https://user-images.githubusercontent.com/23394753/139803679-2ef280ba-218d-4391-ab7a-5653ef267a04.png)

**Comment by ssuess** [comment]
I have the same problem

**Comment by andryyy** [comment]
Check https://github.com/roundcube/roundcubemail/issues/8170#issuecomment-922436182

**Comment by itmunky** [comment]
> 
> 
> Check [roundcube/roundcubemail#8170 (comment)](https://github.com/roundcube/roundcubemail/issues/8170#issuecomment-922436182)

Thanks, that did it!

**Comment by MAGICCC** [comment]
Should be now fixed in the latest release https://github.com/roundcube/roundcubemail/releases/tag/1.5.1

**Comment by Coolguy3289** [comment]
It's not included in the 1.5 release branch of the repo, just updated to 1.5.2 and had to still manually make the change in the rcmail.php file. I've also commented on their issue to indicate this

**Comment by deepc2020** [comment]
@Coolguy3289 did you use the "sed" command from the doc or did you copy in the part from the roundcube issue?
I get a server error with 1.5.2 if i try the patches

**Comment by Coolguy3289** [comment]
I manually made the change. I didn't use sed.

**Comment by deepc2020** [comment]
Ok, thank you.
I tried it, also tried the newest version from git with no success.
Login works but then there is only a short "Server Error" banner in the lower right.
it looks as if the whole ui is trying to use the wrong path / instead of /rc
that started to happen since the last mailcow update with the status from November and Roundcube 1.5 RC it worked with the patch.
And sorry i am also on 1.5.2, change it in my last comment.

Hope this will all be fixed soon
