### ISSUE TITLE
Feature request/question: Does mailcow have filelink support?

### ISSUE THREAD

**Issue by G2G2G2G** [mailcow/mailcow-dockerized#4358]
https://support.mozilla.org/en-US/kb/filelink-large-attachments

Is this beyond the goal of mailcow? I understand it is file hosting/serving instead of actually being email, but it is useful for email since it's probably better than base64 encoding everything and doesn't have the limits of file size emails do.
(please close if it's beyond the goal of mailcow)

**Comment by mkuron** [comment]
This is basically something that file storage services can provide. If you have a Nextcloud or Dropbox account, there are Thunderbird extensions at https://addons.thunderbird.net/en-US/thunderbird/tag/filelink to use them as Filelink storage. Mailcow does not contain any such service, so it's definitely out of scope for us.

There is [documentation](https://mailcow.github.io/mailcow-dockerized-docs/third_party-nextcloud/) (but not support) for setting up Nextcloud on your Mailcow server. But since that gives you essentially a standard Nextcloud installation, we really don't need to provide documentation on how to use Filelink with Nextcloud.

**Comment by G2G2G2G** [comment]
Yes I did in fact read the link I posted...

I assume the answer to my question is "no mailcow doesn't have filelink support" and "it's beyond the scope"
was just checking since there's a WebDAV addon, I'll check with SOGo if it's something they'd do.

**Comment by mkuron** [comment]
SOGo only does WebDAV in the shape of CalDAV/CardDAV. Since this data is stored in a database by SOGo, there is no way to store generic large files in it. So it's out of scope for SOGo too.
