### ISSUE TITLE
Constant traffic use 

### ISSUE THREAD

**Issue by alyzrazor** [mailcow/mailcow-dockerized#436]
Hey guys I got something to share with you
After installing mailcow dockerized and while using command: "**iftop**" I noted that my server is constantly using traffic in/out from many sources
the most notable ones are: **mail.highsecure.ru** (top usage),  **li110-45.members.linode.c** **ns1.rollernet.us**  and a lot of IP's and so on.

I also figured that its related to "**Rspamd**" once I stopped that service the traffic stops.

does anybody knows why is that? does it stop one day? or whats the purpose.

**Another thing/suggestion**: is any way for "add domain button" to show only for super admins and hidden or moved from domain administrators?  I think it's irrelevant for domain admins since they can't even use it due to permissions anyways.

Thanks guys.

**Comment by mkuron** [comment]
highsecure.ru is rspamd's developer. I guess that's where it gets spam rules from, though I'm not sure how much/often that should be happening.

**Comment by stevesbrain** [comment]
Not sure what the Linode + RollerNet traffic is doing, but, you could use tshark/wireshark to get an idea of what's going on :)

**Comment by K2rool** [comment]
li110-45.members.linode.com is the PTR for the IP of ns3.urmombl.com which is a dns server for Spam Eating Monkey.

The traffic from Rspamd is just it checking if dns is working but doing some sanity checks.

Quote form https://github.com/vstakhov/rspamd.com/blob/master/doc/modules/surbl.md

<pre>By default, Rspamd checks each SURBL sanity by queriyng of facebook.com domain. URL black list must NOT reply by some positive result (other than NXDOMAIN) to such a query.
</pre>

A few week back i had Mailcow set to use Dnsmasq on the host server for dns lookup that's when i first noted the dns lookup's.

<pre>
Jun 13 17:31:48 dnsmasq[639]: cached rspamd.com is 88.99.142.95
Jun 13 17:31:52 dnsmasq[639]: query[A] facebook.com.fresh15.spameatingmonkey.net from 172.22.1.253
Jun 13 17:31:52 dnsmasq[639]: cached facebook.com.fresh15.spameatingmonkey.net is NXDOMAIN
Jun 13 17:32:01 dnsmasq[639]: query[A] 1.0.0.127.bl.ipv6.spameatingmonkey.net from 172.22.1.253
Jun 13 17:32:01 dnsmasq[639]: cached 1.0.0.127.bl.ipv6.spameatingmonkey.net is NXDOMAIN
Jun 13 17:32:04 dnsmasq[639]: query[AAAA] rspamd.com from 172.22.1.253
Jun 13 17:32:04 dnsmasq[639]: cached rspamd.com is NODATA-IPv6
Jun 13 17:32:04 dnsmasq[639]: query[A] rspamd.com from 172.22.1.253
Jun 13 17:32:04 dnsmasq[639]: cached rspamd.com is 88.99.142.95
Jun 13 17:32:05 dnsmasq[639]: query[A] 1.0.0.127.zen.spamhaus.org from 172.22.
</pre>

I've added cache-min-ttl to unbound on my server to override the low ttl of lookup such as "facebook.com.fresh15.spameatingmonkey.net" due to Rspamd doing a lookup for it up-to 2-3 time ever min since the ttl for that lookup is only 60 which mean unbound is getting forced to lookup that domain ever min.

**Comment by alyzrazor** [comment]
thanks for answering =D 

Not sure if I need to create another topic about this thing please correct me.

**What you guys say about this:** 

> Is there any way for "**add domain button**" to show only for super admins and hidden from **domain administrator's** panel? I think it's irrelevant for domain admins and such feature should be moved away since they can't even use it.  Peace.

**Comment by K2rool** [comment]
About the add domain button, it can probably be hidden from a domain administrator by added a if into the php code to check if the user is a Admin or just a domain admin.

I can't tell where it would need to be added as am currently on my mobile phone.

**Comment by andryyy** [comment]
The traffic is nothing to be concerned about. I think it will be reduced with the next release of Rspamd. These are internal lookups.

I will check the domain button, I totally forgot about that when switching to the API.

**Comment by carlbennett** [comment]
These are internal lookups? The server should be idle:

![image](https://user-images.githubusercontent.com/592196/28229128-27e77ea6-68a7-11e7-9787-e22c4424d339.png)

**Comment by andryyy** [comment]
Yes, still internal checks. DNS checks, RBL checks etc. There is an open (closed?) issue in Rspamds repository about this.

These graphs are not just mailcow... why would it start to to query 2 GiB data and then stop it?

Please ask in Rspamd or in #rspamd on Freenode or just don't use RBLs at all. Also deactivate Rspamd rule updates. O_O

**Comment by carlbennett** [comment]
>These graphs are not just mailcow... why would it start to to query 2 GiB data and then stop it?

Which graph are you referring to? I don't see any that indicate this behavior. The 'network utilization hourly' is a bar graph. The traffic is constant at 550 kBps in and out.

**Comment by andryyy** [comment]
While I _really_ don't like monitoring by graphs, it is "network utilization hourly". It increased to 3,7 GiB (or something) very fast. I was just saying "this was not a mailcow container". But I guess that's when you downloaded the images?

Would be good to create a trace of the traffic. Or disable RBL monitoring and Rspamd updates. Also check https://github.com/vstakhov/rspamd/issues/1729 :-)

**Comment by stuzfuz** [comment]
> Yes, still internal checks. DNS checks, RBL checks etc. There is an open (closed?) issue in Rspamds repository about this.
> 
> These graphs are not just mailcow... why would it start to to query 2 GiB data and then stop it?
> 
> Please ask in Rspamd or in #rspamd on Freenode or just don't use RBLs at all. Also deactivate Rspamd rule updates. O_O

Where is it possible to deactivate Rspamd rule updates?
