### ISSUE TITLE
'ü' in domain name not ptopper represented

### ISSUE THREAD

**Issue by n3aka** [mailcow/mailcow-dockerized#4360]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [ x ] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [ x ] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [ x ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [ x ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Logs

2/04/2021, 08:12:56 AM | success | 851129 | admin | admin | 178.197.209.130 | ["domain_added","xn--gggsle-3ya.ch"]
12/04/2021, 08:12:56 AM | success | 851129 | admin | admin | 178.197.209.130 | ["dkim_added","xn--gggsle-3ya.ch"]
12/04/2021, 08:11:09 AM | danger | 4297C5 | admin | admin | 178.197.209.130 | ["access_denied","güggsle.ch"]
["dkim","add",{"domains":"güggsle.ch","dkim_selector":"dkim","key_size":"2048"}]

## Reproduction

simply adding a domain, persists after deleting and re adding

## System information

| Question | Answer |
| --- | --- |
| My operating system | CoreOS
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | digitalocean droplet |
| Server/VM specifications (Memory, CPU Cores) | 2 cores, 4GB |
| Docker Version (`docker version`) | 20.10.9 |
| Docker-Compose Version (`docker-compose version`) | 1.28.6 |
| Reverse proxy (custom solution) | no |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by mkuron** [comment]
Partial duplicate of #2875 and #1142. The log messages you posted look like you ran into a place in the admin UI where domain internationalization is broken, but it's actually not fully supported in Postfix and Dovecot either. What should work is this: add your non-ASCII domains in their punycode form (`xn--gggsle-3ya.ch`). Do not create mailboxes for these domains, only create aliases that forward to ASCII domains. Then you can log in with your ASCII mailboxes and send messages via the non-ASCII aliases (as long as the client does proper conversion to punycode) and receive messages for the non-ASCII aliases (since the delivering mail server will use the punycode form).

**Comment by n3aka** [comment]
thank you very much for the fast response, didn't really know what to look for in previous issues.
