### ISSUE TITLE
Add recipient restrictions for catch-all domains

### ISSUE THREAD

**Issue by asirinelli** [mailcow/mailcow-dockerized#441]
Hi,

Thank you for the great project. I am using the following features with my legacy system:
- I have a domain configured in catch-all to a given mailbox.
- When I start having too many spams on one of the username, I had it to a blacklist of recipient.

This is simply implemented in the postfix "smtpd_recipient_restrictions" variable with a "check_recipient_access" parameter.

In Mailcow, the domain's blacklist are, to my understanding, only checked against senders and not recipients. I would be great if we could build a blacklist of recipients in case of catch-all configuration.

Thank you,

Antoine

**Comment by andryyy** [comment]
Hi,

This can be added to the UI, I put it on "my list". :-)

A workaround for now (in the mailcow-dockerized directory):
```
cat <<EOF >> data/conf/rspamd/local.d/multimap.conf

RCPT_BLACKLIST {
  type = "from";
  map = "file:///etc/rspamd/local.d/rcpt_blacklist.map";
  regexp = true;
  prefilter = true;
  action = "reject";
}
EOF
````

Then add a rcpt to this map. Format `/search/i` =>
````
echo "/blocked-rcpt@example.org/i" > data/conf/rspamd/local.d/rcpt_blacklist.map
````

Restart Rspamd afterwards:
``` 
docker-compose restart rspamd-mailcow
```

**Comment by mkuron** [comment]
This is useful not just for catch-all domains, but also for addresses with tags (user+tag@example.com), allowing you to blacklist individual tags. Handling this on the rspamd level, as @andryyy suggested, makes the most sense and could also be extended so that a user can himself (i.e. without requiring action of the admin) blacklist any tags on his addresses.

**Comment by 3VonaBP** [comment]
Thank you for this, very good work!  It would not work for me as-is, so In order for this to work for me, I had to make the type = recipient since it was for a recipient email coming into the system, not the sender from who emailed the recipient to the system:

type = "rcpt";

However, I can't get the file to be Read and Write in the GUI - only read. Even though the file permissions are rw-rw-rw-, any suggestions?
