### ISSUE TITLE
Receive mails on a default email if recipient doesn't exist

### ISSUE THREAD

**Issue by ThalesC** [mailcow/mailcow-dockerized#4563]
### Summary

I was wondering if there is a way to receive emails to non-existent recipients on a default email address.

Let's say I have a domain like _mail.example.com_ and some addresses like _admin@example.com_, _some-user@example.com_ and so on.

For example, if someone tries to send an email to _not-a-valid-mail@example.com_, that email would land on _admin@example.com_ instead of the sender receiving a bounce email with "Delivery fail: recipient not found".

### Motivation

I'm using CPanel at the moment and it has this option, but I want to migrate to Mailcow and didn't find it.
Not critical, I'm still going to migrate, but it would be very nice if I could do it on Mailcow too.

**Comment by DerLinkman** [comment]
Hi,

i think you can already solve that by using a catch-all Address.

You can find that under the Aliasses Tab in the mailcow UI. There simply create a Alias which is @yourdomain.tld (so no mailbox name in the front of the @) 

As the reciepients you add your desired mailbox or boxes (you can add multiple if you like)

Then this catch-all will be used if a mailbox does not exist instead of rejecting the mails.

**Comment by ThalesC** [comment]
Hi @DerLinkman!
That is exactly what I needed, I didn't think to look under aliases for that 😅
Thank you!

**Comment by DerLinkman** [comment]
No problem. I'll close the issue then.

**Comment by berjanb** [comment]
Hi 👋 Folks,
We are using MailCow with Google Workspace with spilit delivery 
In this case how can we catch all in mailcow side ?
