### ISSUE TITLE
Disable Forwarding of Undelivered Messages

### ISSUE THREAD

**Issue by jonathanmmm** [mailcow/mailcow-dockerized#4565]
### Summary

Suppose you have a mailbox `list@example.com` that forwards e-mails to external mailboxes (forwarding done via SoGo).

For example:
`spam@spam.com` sends a spam E-Mail to `list@example.com`.
This spam E-Mail is not detected by rspamd (no-action) and send to all external mailboxes.
At least one of the mail servers where an external mailbox is, rejects the E-Mail (detects it rightfully as spam) and sends a reject message/E-Mail.
Now mailcow sends the UNDELIVERED message to all external mailboxes from list@example.com.

Maybe this is a bug, I don't know, but if not, this feature would be useful. Maybe there is also a way to accomplish this via filters?

This is annoying and makes that people maybe don't read / read these E-Mail even less.

### Motivation

Not having to deal with undelivered messages from E-Mails you have not even send.

**Comment by mkuron** [comment]
I guess this behaves as expected. Mailcow generates an undelivered mail notification and sends it to list@example.com. That Mailbox has the forwarding rule you created to send it to everyone else.

If you don‘t want that, you cannot use an unconditional forwarding. Instead, create a filter that forwards everything except for these bounces. Filter by subject (they always look the same since they are generated by Mailcow — unless the remote mailserver is misconfigured and sends backscatter spam) or an appropriate header field. I believe the envelope sender on bounces is empty, so that‘s also a possibility for a custom filter (but cannot be configured in SOGo‘s filter UI).

**Comment by jonathanmmm** [comment]
@mkuron Ok, thanks, do you have an example on how such a filter could look like?
