### ISSUE TITLE
Don't work autodiscover

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#46]
I get error 

Warning: include_once(inc/vars.local.inc.php): failed to open stream: No such file or directory in /web/autodiscover.php on line 28

Warning: include_once(): Failed opening 'inc/vars.local.inc.php' for inclusion (include_path='.:/usr/local/lib/php') in /web/autodiscover.php on line 28

Warning: Cannot modify header information - headers already sent by (output started at /web/autodiscover.php:28) in /web/autodiscover.php on line 42

Warning: Cannot modify header information - headers already sent by (output started at /web/autodiscover.php:28) in /web/autodiscover.php on line 43

**Comment by PhoenixPeca** [comment]
Hi @aekv,

Thanks for reporting!!

I forgot that the dockerized version doesn't have a localized version of vars.local.inc.php.

Please merge PR #47 in your production server. Don't hesitate to reply back if you had any more issues. :smile:

**Comment by andryyy** [comment]
Merged it and also set error_reporting to 0 for this file.

**Comment by ghost** [comment]
Attempting to send an Autodiscover POST request to potential Autodiscover URLs.
 	Autodiscover settings weren't obtained when the Autodiscover POST request was sent.
 	
	Additional Details
 	
Elapsed Time: 175 ms.
 	
	Test Steps
 	
	The Microsoft Connectivity Analyzer is attempting to retrieve an XML Autodiscover response from URL https://autodiscover.domain.com:443/Autodiscover/Autodiscover.xml for user test@domain.com.
 	The Microsoft Connectivity Analyzer failed to obtain an Autodiscover XML response.
 	
	Additional Details
 	
The URL returned in the mobile autodiscover response was invalid: 'https:///Microsoft-Server-ActiveSync'
HTTP Response Headers:
Transfer-Encoding: chunked
Connection: keep-alive
Strict-Transport-Security: max-age=15768000; includeSubDomains
Content-Type: application/xml
Date: Tue, 14 Feb 2017 10:38:19 GMT
Server: nginx/1.11.9
X-Powered-By: PHP/7.1.1
Elapsed Time: 174 ms.

**Comment by andryyy** [comment]
Can you please try the new commit? => 
```
wget -O data/web/autodiscover.php https://raw.githubusercontent.com/andryyy/mailcow-dockerized/master/data/web/autodiscover.php
```

**Comment by PhoenixPeca** [comment]
Hi,
I'm sorry if you had this problem. my bad. I can't be sure that my PRs in the dockerized version works well in the dockerized version, for I can't create another testing server for testing the dockerized version (the standard mailcow is the only version I can test).

However I have encountered a similar problem in the standard mailcow version, which is only specific in the "Microsoft Office Outlook Connectivity Tests", because "Microsoft Exchange ActiveSync Connectivity Tests" and "Microsoft Office Outlook Connectivity Tests" in the Microsoft Remote Connectivity Analyzer is different . As for the fix, I simply changed [this line](https://github.com/andryyy/mailcow-dockerized/blob/master/data/web/autodiscover.php#L8) to 
`'useEASforOutlook' => 'no',`

PS: Have you tried setting it up on an actual Microsoft Outlook Client to use the autodiscover feature?

# UPDATE

> Have you also tried opening https://autodiscover.example.com/autodiscover/autodiscover.xml and got a log-in promt?
> ![capture](https://cloud.githubusercontent.com/assets/9730242/22926483/b33557e8-f2e7-11e6-98e3-7b39faaf6c4e.PNG)

> Try logging-in with your mailbox account.
> If you received a XML message similar to this:
> ![capture](https://cloud.githubusercontent.com/assets/9730242/22926603/3664ea52-f2e8-11e6-80b2-433a9c6db039.PNG)
> THEN YOUR AUTODISCOVER IS WORKING WELL!!!

**Comment by andryyy** [comment]
He just couldn't read the hostname variable without vars.inc.php. :-) This should have fixed it.

**Comment by PhoenixPeca** [comment]
Hi @andryyy,

I guess we should leave the 'inc/vars.local.inc.php' below the config array so that the user can override the values of the array without loosing modifications everytime he/she updates.

However, I think things were different in the dockerized version, so maybe, ignore the PR #49 if needed.

**Comment by ghost** [comment]
Thank you! Fixed

**Comment by andryyy** [comment]
Yes @PhoenixPeca, that's a good idea.
