### ISSUE TITLE
Fuzzy Learn Error

### ISSUE THREAD

**Issue by daygle** [mailcow/mailcow-dockerized#4624]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

When attempting to learn a quarantined email as spam I am presented with a 'Fuzzy learn error'. Sometimes I see a orange 'Array' message/error too...

Is this a known issue at the moment? If not, any hints how to fix?

### Logs

```bash
09/06/2022, 22:34:09	warning	DA680B	admin	admin	XX.XXX.XXX.XX	["fuzzy_learn_error","Message sending error"]
Call	["quarantine","edit",{"id":["22"],"action":"learnspam"}]
```

### Steps to reproduce

1. Login to Mailcow with admin.
2. Open 'Quarantine'
3. Select email, then press the 'Actions' button.
4. Select 'Learn as spam and delete'.
5. Fuzzy learn error displayed.

### System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 22.04 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technology (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 6GB RAM, 2 Cores |
| Docker version (`docker version`) | 20.10.17 |
| docker-compose version (`docker-compose version`) | 1.29.2 |
| mailcow version (```git describe --tags `git rev-list --tags --max-count=1` ```) | Version: 2022-06 |
| Reverse proxy (custom solution) | Yes, Apache |

Output of `git diff origin/master`, any other changes to the code? If so, **please post them**:
```
diff --git a/data/assets/ssl-example/cert.pem b/data/assets/ssl-example/cert.pem
index 96d16bec..2720dfb5 100644
--- a/data/assets/ssl-example/cert.pem
+++ b/data/assets/ssl-example/cert.pem
@@ -1,19 +1,33 @@

```

**Comment by daygle** [comment]
This seemed to only be related to the one email.

Not sure why.

**Comment by baderas** [comment]
Please think about reopening this issue, because the same Issue occurs when using "Scan/Learn" from the rspamd web ui. Just enter anything as mailsource, it doesn't matter, and press "Scan Message" and then "Upload Fuzzy".

The result is always:
![grafik](https://user-images.githubusercontent.com/13378513/178484724-66b3341d-880a-484d-b746-4bb90231d454.png)

If I use the browser debugger, i can see that the result of the Post Request to https://mail.mydomain.de/rspamd/fuzzyadd is "404 Not Found".

If I however enter https://mail.mydomain.de/rspamd/fuzzyadd directly in my browser, I get "Unauthorized" which for me means, it is reachable. 

Not sure why this happens and rspamd cannot connect to /rspamd/fuzzyadd.

**Comment by daygle** [comment]
@baderas might be best if you open a issue as I have no longer experienced any more fuzzy errors.

That way they can contact you to investigate.
