### ISSUE TITLE
Configuration -> System Information -> System & Containers is not usable by those with red/green color blindness

### ISSUE THREAD

**Issue by gatortux** [mailcow/mailcow-dockerized#4707]
### Summary

Mailcow with some minor changes could be made more ADA compliant for those with color blindness especially red/green. The biggest problem is the above mentioned page in the subject which is not presently usable because the small, red and green colored dots on the button are indiscernible from each other to a respectable number of users (maybe about 8%). Replacing them with different shapes, a circle and an 'X' is one of many ways to solve the issue.

There are good tools that operate as browser plugins that will identify these types of issues on a given page and offer suggestions to make it "508 compliant". When I did software for the government this was a requirement and we were mandated by law. I am not suggested a site wide review though I wouldn't discourage it. The main issue is the System & Containers page.

Thanks for taking this into consideration.

### Motivation

About 8% of males are red/green colorblind per Wikipedia and the page mentioned above is not presently usable.

**Comment by FreddleSpl0it** [comment]
this issue is a duplicate [https://github.com/mailcow/mailcow-dockerized/issues/4639](https://github.com/mailcow/mailcow-dockerized/issues/4639). Enhancement will come with the Bootstrap5 Update :).

![Screenshot 2022-08-08 125755](https://user-images.githubusercontent.com/75116288/183404396-4c6f8bba-e0ef-4d9e-9c90-451ff64588b6.png)

**Comment by MAGICCC** [comment]
I'll close it in favor of mentioned issue.
