### ISSUE TITLE
windows defender found a virus on mailcow rspamd backup

### ISSUE THREAD

**Issue by atlanticfirst** [mailcow/mailcow-dockerized#4779]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

windows defender found a virus named TrojanDownloader:O97M/Dornoe.AP!ams in mailcow rspamd backup.located in backup_rspamd.tar.gz/\rspamd\,filename is 7de5410c328c7272aba5ee8b4afa11cfb92ab008.map.
is that a false alarm on rspamd URL filter?
[7de5410c328c7272aba5ee8b4afa11cfb92ab008.txt](https://github.com/mailcow/mailcow-dockerized/files/9708584/7de5410c328c7272aba5ee8b4afa11cfb92ab008.txt) attach files does support .map,so i change it to .txt

### Logs

```bash
null
```

### Steps to reproduce

null

### System information

null

**Comment by mkuron** [comment]
It seems like a false alarm. This file contains a list of URLs that rspamd considers spammy and it's regularly downloaded automatically by Mailcow. An overzealous antivirus scanner might consider the presence of a dangerous URL in a file as rendering the file itself dangerous, so that's probably why you got the virus report. If you upload the file to VirusTotal (https://www.virustotal.com/gui/url/a6ae2a5d1d6d2da85082b3c121be097a7585d38226be08a4821d35223769d3e7), it tells you that 89 other antivirus programs do not consider it dangerous.
