### ISSUE TITLE
Hardcoded ip breaks sogo with custom network setups

### ISSUE THREAD

**Issue by lgleim** [mailcow/mailcow-dockerized#480]
Due to https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/sogo/reconf-domains.sh#L4 Sogo does not start in case mysql is not configured at the given IP. A solution using 'mysql' and dns instead would solve this issue and would be much appreciated

**Comment by mkuron** [comment]
There are many more places where IPs are used instead of hostnames. Maybe @andryyy can shed some light on the reasons and whether they still exist. If I remember correctly, it was due to DNS sometimes not being available immediately after a container was started.

Also, there are some places where hostnames cannot be used, e.g. the Postfix trusted networks, Nginx X-Forwarded-For trust list, ...

**Comment by kpcyrd** [comment]
@mkuron Can you elaborate on the dns issues? This shouldn't be an issue unless the email setup assumes that network can't fail.

I ran into issues with the hardcoded setup as well, as mailcow-dockerized assumes that 172.22. hasn't been assigned yet. Moving this to a different IP range seems to be non-trivial. Have you considered writing a script that detects the IP range from the docker interface and write that range into the configs?

**Comment by andryyy** [comment]
I plan to change this in the future, but right now you can just rewrite IPs yourself to fit your setup. Not a big deal.
Docker sometimes had some strange DNS issues I could no more replicate. But testing needs to be done. The entrypoint scripts could handle most stuff related to the networking problems I had, though...
