### ISSUE TITLE
QUESTION: It is safe to use :latest instead

### ISSUE THREAD

**Issue by JOduMonT** [mailcow/mailcow-dockerized#520]
in reference of #340 
I was wondering if it's safe to use :latest instead of version into the docker-compose.yml
I know the docker best practice say : You must use version number
Put in fact; most of the time is just more manipulation and potential error when you upgrade.

So It is safe to use :latest ?

Regards!

Jonathan

**Comment by mkuron** [comment]
It is not safe to do that. The version numbers were explicitly added to make sure that the container always matches up with the configuration files in the Git repo. Running a newer container with an old Git repository was a very common source of error (just look through the issue tracker) that has gone away completely since switching to version numbers.

Of course, requiring Mailcow to be run out of the Git repository (and not via a simple `docker pull`) is not exactly best practice, but it's the only viable way to maintain the complex interdependencies of a mail server.

**Comment by JOduMonT** [comment]
@mkuron 
Thanks for you're answer
and I found the command ./update.sh :)
