### ISSUE TITLE
Whitelabeling for mail.domain

### ISSUE THREAD

**Issue by jaketame** [mailcow/mailcow-dockerized#528]
Is it possible to configure additional domain names automatically into the SAN such as

mail.domain1.org
mail.domain2.org?

Cheers

**Comment by chriscroome** [comment]
Yes, add them using the `ADDITIONAL_SAN` environmental variable in the `mailcow.conf` configuration file, see [this line](https://github.com/mailcow/mailcow-dockerized/blob/master/generate_config.sh#L80).

**Comment by jaketame** [comment]
Thanks for reply, was hoping for a more automated way / when add new domain - tickbox to add as SAN?

**Comment by chriscroome** [comment]
Why do you want additional `mail.example.org` and `mail.example.org.uk` sub-domains, why don't you just use the main domain for the server -- you can add additional email domains via the web interface and these are added to the SAN list for `autodiscover.` and `autoconfig.` automatically, or perhaps I'm misunderstanding what you are asking?

**Comment by jaketame** [comment]
So I can provide some sort of white labelling to sites I host and provide them with there own mail.domain to connect to with a validate cert.

**Comment by chriscroome** [comment]
Fair enough, I'm not the one to answer this, perhaps it would be worth making the issue title clearer regarding the aim?

**Comment by mkuron** [comment]
Just adding extra domain names is not sufficent to get white-labeling. MAILCOW_HOSTNAME is used in a number of places throughout the configuration files and in the web UI code. Mailcow in its current state is not made for white-label setups.

**Comment by kunago** [comment]
I see the usage in easy migration process. Once you set your emails in clients and use MAILCOW_HOSTNAME, it's then difficult to simply switch servers.

What about having some 2 extra fields in the UI for each domain where you could set the incoming and outgoing domain names? Or maybe more then 2 depending on the amount of services.

**Comment by jaketame** [comment]
I give a client mail.there-domain.com, which just points to my mailserver, its a bit neater and nice for them. They don't need a full whitelabel service. The certificate is to ensure they don't have errors client side by using a different domain connecting to the server.

**Comment by kunago** [comment]
@jaketame I do the same thing, however, autoconfig points to MAILCOW_HOSTNAME which may be confusing for some.

**Comment by mkuron** [comment]
@kunago, it's not just a UI thing, but you could try and post a pull request with all the other necessary bits if you get it working. At the very minimum, you'll need to modify data/Dockerfiles/acme/docker-entrypoint.sh, data/web/autoconfig.php and data/web/inc/vars.inc.php. You may also need to modify data/conf/nginx/templates/server_name.template for it to work in a setup without reverse proxy.

**Comment by markirb** [comment]
As we have several domains, and also provide the user with a seperate subdomains, i set it up like this

https://github.com/markusg/mailcow-dockerized/commit/7efd2baa8bbb62d153d1bbe8f5d2c2b85d065dbd

For me this is enough.... 
The generalization is because i also want seperate mail,sogo and roundcube subdomains (convenience redirecting by frontend proxy).

Now the question is, as @mkuron  said, should it be rewritten to also change the autoconfigs?
The question for me here is, how would i match the domain part?
Can i assume that the autoconfig.php is called with autoconfig.$TLD ?
Then i would reset $mailcow_hostname to mail.$TLD if the subdomain is within the above ADDITIONAL_SUBDOMAINS.
Would this be good enough for you? Seems a little bit weird to me, any suggestions?

**Comment by alexandernst** [comment]
Any news on this? Why did it get stalled?

**Comment by mkuron** [comment]
Pull requests are welcome. It's not the most pressing issue to the main developers and nobody else has so far come up with a comprehensive solution.

**Comment by SLGShark6** [comment]
This seems to still be a needed feature, I might look into making my own PR. I'm knew to mailcow, but absolutely love it. The previous PR's seem to have been closed because they weren't comprehensive solutions. I'm assuming to make this comprehensive one would have to:

- Have options in the mailcow.conf file for perhaps setting either a static URL (such as mail.example.com) or a wildcard (such as mail.* or imap.*, pop3.*) for either all or individual protocols (imap, pop3, smtp).
- Perhaps have override options for each mail domain in the domain configuration section of the mailcow UI
- Utilize these settings with the NGinx instance to accept traffic from those URL's
- Utilize these settings with the letsencrypt instance to add those URL's to the SSL certs

I'm not too sure about the feasibility of this, or how difficult it will be to implement but I'm willing to give it a go. Any advice or suggestions anybody can give me before I get started would be greatly appreciated.

I really love mailcow, just feel held back by the lack of this feature, in case I need to move servers or separate my mail server from my web server in the future, without having to sign out all of my clients and sign them back in.
