### ISSUE TITLE
fail2ban-mailcow -> f2b-mailcow

### ISSUE THREAD

**Issue by denji** [mailcow/mailcow-dockerized#529]
https://github.com/AdUser/f2b
 - written in pure C
 - small memory footprint
 - minimum dependencies (required: libc, libdl; optional: pcre, redis)
 - `f2b*.deb`: https://github.com/AdUser/f2b/tree/master/debian

**Comment by k0nsl** [comment]
That looks quite nice, actually. Good suggestion!

**Comment by snc** [comment]
BTW latest fail2ban got faster, too: https://github.com/fail2ban/fail2ban/releases/tag/0.10.0

**Comment by mkuron** [comment]
AdUser/f2b doesn't appear to have full IPv6 support, so we can't use it.
fail2ban can't access Docker logs, that's why we didn't use it.

If there is a different piece of software that fulfils all requirements and has major advantages over the existing solution, feel free to submit a pull request. I don't see any reason to replace the current solution though.
