### ISSUE TITLE
ACME cannot match IP against hostname

### ISSUE THREAD

**Issue by carlbennett** [mailcow/mailcow-dockerized#546]
I followed the documentation available [here](https://mailcow.github.io/mailcow-dockerized-docs/firststeps-ssl/) to setup multiple mail domains with mailcow hosted on the same server.

I have mailcow working great, I am able to send and receive mail on all of the additional domains. However, I am running into an issue trying to get mailcow to generate certificates for all of the secondary domains.

I receive the following errors:

```
[root@mail mailcow-dockerized]# /usr/local/bin/docker-compose logs acme-mailcow
Attaching to mailcowdockerized_acme-mailcow_1
acme-mailcow_1       | Found Let's Encrypt or mailcow snake-oil CA issued certificate with SANs: mail.carlbennett.me
acme-mailcow_1       | Found A record for autoconfig.carlbennett.me: 162.253.43.10
acme-mailcow_1       | Cannot match your IP  against hostname autoconfig.carlbennett.me (162.253.43.10)
acme-mailcow_1       | Found A record for autodiscover.carlbennett.me: 162.253.43.10
acme-mailcow_1       | Cannot match your IP  against hostname autodiscover.carlbennett.me (162.253.43.10)
acme-mailcow_1       | Found A record for mail.carlbennett.me: 162.253.43.10
acme-mailcow_1       | Cannot match your IP  against hostname mail.carlbennett.me (162.253.43.10)
acme-mailcow_1       | Found A record for mail.carlbennett.me: 162.253.43.10
acme-mailcow_1       | Cannot match your IP against hostname mail.carlbennett.me 
acme-mailcow_1       | Found A record for mail.carlbennett.io: 162.253.43.10
acme-mailcow_1       | Cannot match your IP against hostname mail.carlbennett.io
acme-mailcow_1       | Cannot validate hostnames, skipping Let's Encrypt...
[root@mail mailcow-dockerized]#
```

At the moment, only https://mail.carlbennett.me/ is serving the correct certificate. If you try https://mail.carlbennett.io/ for example, it serves the certificate for mail.carlbennett.me instead.

What do I need to do to resolve this?

**Comment by carlbennett** [comment]
I resolved this by reinstalling mailcow completely. I don't call that a solution though.

**Comment by max-baz** [comment]
I've just experienced this issue, and I believe the root cause is that `curl -4s https://mailcow.email/ip.php` sometimes responds with an empty string.

Everything was working fine for a week, and today I got certificates that do not include SAN that I used to have.

Looking at the logs in `acme` container, I see the following:

```
Found A record for autoconfig.maximbaz.com: 40.68.155.0
Confirmed A record autoconfig.maximbaz.com
Found A record for autodiscover.maximbaz.com: 40.68.155.0
Confirmed A record autodiscover.maximbaz.com
Found A record for mail.maximbaz.com: 40.68.155.0
Confirmed A record mail.maximbaz.com
...
Found A record for autoconfig.maximbaz.com: 40.68.155.0
Confirmed A record autoconfig.maximbaz.com
Found A record for autodiscover.maximbaz.com: 40.68.155.0
Confirmed A record autodiscover.maximbaz.com
Found A record for mail.maximbaz.com: 40.68.155.0
Confirmed A record mail.maximbaz.com
...
Found A record for autoconfig.maximbaz.com: 40.68.155.0
Cannot match your IP  against hostname autoconfig.maximbaz.com (40.68.155.0)
Found A record for autodiscover.maximbaz.com: 40.68.155.0
Cannot match your IP  against hostname autodiscover.maximbaz.com (40.68.155.0)
Found A record for mail.maximbaz.com: 40.68.155.0
Cannot match your IP  against hostname mail.maximbaz.com (40.68.155.0)
Found orphaned SAN autoconfig.maximbaz.com autodiscover.maximbaz.com in certificate, moving old files to /var/lib/acme/acme/private/2017-09-09_21_55_02.bak/, keeping key file...
```

See those two spaces in `Cannot match your IP__against ...`? That is showing that the environment variable `${IPV4}` has an empty value, and its value comes from `IPV4=$(curl -4s https://mailcow.email/ip.php)`.

Relevant snippet of code:

https://github.com/mailcow/mailcow-dockerized/blob/c6d461382cba82cf1459843f4af21d87f3392398/data/Dockerfiles/acme/docker-entrypoint.sh#L76-L95

So a little bit better workaround than reinstalling mailcow completely is to execute `docker-compose restart acme-mailcow`, this basically makes another attempt to provision certificates, which usually succeeds. But I wish `https://mailcow.email/ip.php` would be more stable.

Could someone check the logs behind `https://mailcow.email/ip.php`, maybe you could spot the issue and see how often it occurs?

**Comment by Bersam** [comment]
hmmm, i have similar problem, in my case nginx return 404 on ip.php... i think skip_ip_check in enviroment variables could be another workaround to this problem.

**Comment by Bersam** [comment]
This is not actually fixed, still can not find ip.php, it's working by skipping ip check.

**Comment by andryyy** [comment]
Just open it in a browser and tell me it is not working.

**Comment by Bersam** [comment]
@andryyy you're right it's fixed. my bad, i thought ip.php is located on my server, and i'm getting 404 on my server which is not the problem..

**Comment by Braintelligence** [comment]
I still have this problem today...
```
Found orphaned SAN autoconfig.domain1.tld autoconfig.domain2.tld in certificate, moving old files to /var/lib/acme/acme/private/2019-01-07 17 01 44.bak/, keeping key file...
```

This is only true for autoconfig.

EDIT: Skipping IP check didn't help (or maybe it would've if I did `docker-compose up -d` after doing so) I had to add autoconfig to ADDITIONAL_SAN ...

EDIT2: @andryyy Is it normal that autoconfig recommends IMAP via SSL/TLS on 993 and SMTP on 465 via SSL/TLS instead of using the other ports via STARTTLS?

**Comment by andryyy** [comment]
autoconfig.* was dropped from the certs. If you use a reverse proxy, you should update the config (see the docs).

I think autoconfig.php passes both options, it is probably up to the client to decide. See `autoconfig.php`. :)

**Comment by montgomery-auber** [comment]
zxdca

**Comment by montgomery-auber** [comment]
I created a new certbot cer manually. then copied them to /opt/mailcow-dockerized/data/assets/ssl  changing the name to key.pem and cert.pem . the easiest way was to use route53, but you can use other certbot methods. acme is more work than using a DNS.

REMEmber to remove --staging, otherwise your cert will give a new and more creative error.

`version: '3.4' 
services:  
  certbot:
    container_name: 'certbot'
    image: certbot/dns-route53
    restart: "no"
    volumes:
      - ../docker-volumes/etc/letsencrypt:/etc/letsencrypt
      - ../docker-volumes/var/lib/letsencrypt:/var/lib/letsencrypt
      - ../docker-volumes/letsencrypt-docker-nginx/src/letsencrypt/letsencrypt-site:/data/letsencrypt
      - ../docker-volumes/var/log/letsencrypt:/var/log/letsencrypt
      - ../docker-volumes/.aws:/root/.aws 
    #remove --staging!!!!!!
    command: certonly --email support@YouRDOMAIM --agree-tos --no-eff-email --non-interactive -d YOURDOMANAME --dns-route53 --staging`

I am frustrated with mailcow, am creating a simpler system that will also use docker compose, but all paths inside containers will be defaults. check out the project [https://github.com/montgomery-auber/postfix-containerized]
