### ISSUE TITLE
mailcow.conf specific bindings not working (nginx)

### ISSUE THREAD

**Issue by a-t-a-r-i** [mailcow/mailcow-dockerized#55]
Hi,

when i setup bindings to an specifc ip this works for all containers except nginx-mailcow.

`ERROR: The Compose file './docker-compose.yml' is invalid because:
services.nginx-mailcow.ports is invalid: Invalid port "10.10.10.10:443:10.10.10.10:443", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
`

I think line 221 in docker-compose.yml is wrong
`        - "${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
`

i changed it to

`        - "${HTTPS_PORT:-443}:443" `

but now nginx refuces to bind:

`nginx: [emerg] bind() to 10.10.10.10:443 failed (99: Cannot assign requested address)
`

I think part of the problem is my lack of knowledge about docker ;)

(Real ip adress host ist configured to replaced with 10.10.10.10)

**Comment by andryyy** [comment]
Yes, will be fixed in a newer version.

Nginx needs a slightly different method for this, because the SOGo webobjects header fields will fail if the port is not 1:1 inside:outside NAT. So we need a HTTPS_BIND variable and a HTTPS_PORT variable with only the port and no IP. I implemented this in dev and will push it here soon.

**Comment by andryyy** [comment]
Will be fixed with todays merge.
