### ISSUE TITLE
Mailcow in Plesk Onyx docker not starting

### ISSUE THREAD

**Issue by robetus** [mailcow/mailcow-dockerized#554]
I can't get mailcow running on Plesk Onyx Docker. I installed the default image from the docker hub and added the volume maps but the container won't start. Do I need to build my own yaml for this to work?

**Comment by Avalarion** [comment]
I did not try this as this is some kind of wrong in my opinion.

Are you able to tell me the used ports of Plesk? I would guess that this problem exists because you are already using all Mailcow ports with Plesk xD.

On your command line as root this would for example be:

```
netstat -tulpen
```

Greetings from Bochum, Germany,

Bastian
