### ISSUE TITLE
default for MX_INVALID too high

### ISSUE THREAD

**Issue by marrco** [mailcow/mailcow-dockerized#576]
trying to debug a few false positives from slow responding mx (all MX for tiscali.it wait 10+ seconds before returning a 220) I realized that score for `MX_INVALID`   (see https://i.imgur.com/XphBTNb.png )
 are really different than those in the example here:   [https://rspamd.com/doc/modules/mx_check.html](https://rspamd.com/doc/modules/mx_check.html) 

a quick fix for me was to add 

```
group "MX" {
	symbol "MX_INVALID" {
	  score = 1.0;
	  description = "No connectable MX";
	  one_shot = "true";
	}
	symbol "MX_MISSING" {
	  score = 2.0;
	  description = "No MX record";
	  one_shot = "true";
	}
	symbol "MX_GOOD" {
	  score = -0.5;
	  description = "MX was ok";
	  one_shot = "true";
	}
}
```

to `data/conf/rspamd/local.d/metrics.conf`

so I wonder what was the rationale behind having mx_invalid much higher than MX_missing, considering that waiting a few seconds before responding and early talkers detection are common antispam measures.

**Comment by mkuron** [comment]
Rspamd 1.7 changes the scores once it's released  (https://github.com/vstakhov/rspamd/commit/6a0f96a890b86d68680a994a807c96ccc8281bf4). I find the mx_check module a bit questionable anyway as MX_MISSING is perfectly legitimate (if there is no MX record, there is one implied based on the A record)  and now it carries a score of 3.5...

**Comment by marrco** [comment]
thx for the heads up mkuron. At least the 1.7 version makes some sense. I know it's ok per rfc to just have a A record  at apex, but I'd say it's fair to use it as a hint, at least to greylist the first message.

**Comment by mkuron** [comment]
Well, a score of 3.5 is more than just a hint... it's 70% of the way to being flagged as spam.

**Comment by marrco** [comment]
@mkuron I agree with you, my values now are:

```
group "MX" {
	symbol "MX_INVALID" {
	  score = 0.5;
	  description = "No connectable MX";
	  one_shot = "true";
	}
	symbol "MX_MISSING" {
	  score = 3.0;
	  description = "No MX record";
	  one_shot = "true";
	}
	symbol "MX_GOOD" {
	  score = -0.01;
	  description = "MX was ok";
	  one_shot = "true";
	}
}
```
but I'll probably set MX_INVALID lower as many legit MTA wait more than 1 sec (default timeout) before returning a 200. Right now all those default to 80% chance of being flagged as spam for implementing an antispam measure. So until the new 1.7 i suggest mc-d has this fix

**Comment by mkuron** [comment]
You could increase the timeout in https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/rspamd/local.d/mx_check.conf . I've also seen false-positive MX_INVALID due to to that (e.g. on LinkedIn notification emails), so please submit a pull request.

I'd suggest decreasing MX_MISSING to 1.0 to make it just a weak hint at spamminess. I have seen more false positives with this one than true positives.

**Comment by marrco** [comment]
pull request issued with MX_MISSING set to 2

a quick review of my logs shows 1 is too low to be effective, so I keep 3 for me and lower to 2 for the pull request. I intend to remove the change to get back to rspamd defaults when official 1.7 will be merged with new values.

I will test rising timeout on my local server before pulling a request for that too, but I guess it will be ineffective because slow responding MX usually wait more than 5 seconds, and I fear that setting could keep too many open sessions.

**Comment by mkuron** [comment]
Ok, please let us know how these timeout tests go.

 I don't think a 10-second timeout would be a big problem: rspamd advertises being able to process 100 messages per second, so there'd never be more than 1000 open connections with a 10-second timeout. That's a number Linux is perfectly capable of handling. In reality, most of these connections will be to MXes that answer quickly and thus be closed within a second.

**Comment by marrco** [comment]
I tested with 8 seconds timeout, and it eliminates (large) part of false positives, without slowing my installation and without creating problems. So I updated the pull request with the timeout set to 8 seconds. 

It will still return false positives for MX_INVALID that have early talker detection with very long wait (tiscali.it mx wait about 12 seconds) but more rarely now.

**Comment by mkuron** [comment]
The SMTP spec probably doesn't mandate a minimum connection timeout, so Tiscali isn't violating any standard, but waiting 12 seconds is clearly excessive.
Is Tiscali the only mail service you're seeing these large delays with? If so, we could just assign an opposite score to any message coming from Tiscali to cancel out the MX_INVALID.

**Comment by marrco** [comment]
[rfc2821](https://www.ietf.org/rfc/rfc2821.txt) defines **5 minutes** as the maximum timeout for the 220 greeting.

```
 Based on extensive experience with busy mail-relay hosts, the minimum
   per-command timeout values SHOULD be as follows:

   Initial 220 Message: 5 minutes
      An SMTP client process needs to distinguish between a failed TCP
      connection and a delay in receiving the initial 220 greeting
      message.  Many SMTP servers accept a TCP connection but delay
      delivery of the 220 message until their system load permits more
      mail to be processed.
```

greet pause/greeting delay (https://wiki.asrg.sp.am/wiki/Greet_pause) has been implemented also in sendmail since v. 8.13 with suggested values of 2-10 seconds, usually gets set to 5000 msec.
Others suggest 20 seconds: http://www.tldp.org/HOWTO/Spam-Filtering-for-MX/smtpdelays.html

Review of my logs with the value set as in my pull request confirm that 8 sec. timeout solves most false positives, but tiscali.it is not the only one with >10 secs delay I've found. And that's an effective, absolutely legit antispam feature.

If you can confirm that 15 seconds are not an issue or cause significant slowdown, large memory use on your system we could raise that value to 15 seconds to achieve even less false positives, or if you feel that's too high, let's commit the pull as it is now with 8 seconds and move the discussion to rspamd group since you think the mx_check module is a bit questionable anyway.

**Comment by mkuron** [comment]
5 minutes is just too much. 15 seconds, on the other hand, is something we could handle. One connection for each incoming message for the MX check is no problem at all, even with a large timeout -- that only doubles the number of open connections per message (the other one being the SMTP connection initiated by the delivering server), so it cannot be used for any kind of DoS attack.

Since rspamd is capable of 100 messages per second, the worst case scenario is 1500 open non-timedout connections -- the Linux kernel can easily handle that. The only other limitation is that we have to stay below 30 seconds as that's the Postfix Milter timeout.

That being said: how many true-positive MX_INVALID are you seeing? To date, all my encounters of MX_INVALID and MX_MISSING have been false positives, so I'm still kind of leaning toward disabling mx_check altogether.

**Comment by marrco** [comment]
Sometimes logging is not very clear, MX check is correctly done on the  envelope-from, so you have to spot a line: FROM_NEQ_ENVFROM where the second value is the envelope from.  That value is checked for MX_INVALID.

apart from hosts with very long greeting delay, i have seen no false positives. And raising the timeout to 15 would fix all of them, at least from limited log check. 
Also using the new, lower value of 0.5 for mx invalid caused no collateral damage in the really rare (only tiscali.it last night) case for a wrongly assigned penalty with the 8 seconds delay proposed in the pull.

So for me this check is ok. What false positives are you seeing?

**Comment by mkuron** [comment]
MX_INVALID I've seen with a corporate mail server (2 second delay) and Linkedin notifications (4 second delay). Both of these would be fixed by your increased timeout. I've also seen it on a very low number of spam mails, but all of them were also flagged by DNSBLs and the Bayesian filter -- so mx_check wasn't actually needed to get across the threshold.

MX_MISSING I've seen primarily by emails coming from a German web hosting company (all-inkl.com) that relies on the implicit MX record for its customers' subdomains. I have not seen MX_MISSING on any spam mails.

Could you please check your logs for how many true positives have MX_MISSING and for what fraction of them it actually made a difference (e.g. which ones wouldn't have been flagged as spam had mx_check been disabled)?

So my current opinion is that mx_check is not needed at all.
Your suggestion of reducing MX_INVALID to 0.5 kind of confirms that it cannot be trusted; 0.5 only rarely makes the difference that lifts a message across the spam threshold. For such a small score difference, it's not really worth spending the resources to open a new TCP connection or to wait for a timeout that may be up to 15 seconds.

**Comment by marrco** [comment]
with the higher timeout set to 8 new, corrected, standard rspamd values make sense, and the check helps to detect spam sources with no false positives for me in the last few days. so 
values here
https://rspamd.com/doc/modules/mx_check.html
or even
https://github.com/vstakhov/rspamd/commit/6a0f96a890b86d68680a994a807c96ccc8281bf4
can do. 
MX_INVALID can be rised to 1 or even 2 with the timeout set at 8 seconds without risk, as far as I can tell looking at my logs.

so my suiggestion is to commit the pull with this values (timeout 8sec, MX_INVALID 0.5 - MX_MISSING 2.0 and MX_GOOD -0.01) and revaluate this when the new rspamd 1.7 get released.

imho this check has to stay. no false positives with timout rised to 8 secs and helps spam detection.

**Comment by mkuron** [comment]
> helps spam detection

Does it actually? How many spam mails are you seeing rejected solely thanks to mx_check? Can you provide some numbers as requested in my previous message?

**Comment by marrco** [comment]
mailcow is not my primary antispam device. I have much more experience with assp where some years ago I constantly had to filter millions incoming connections per day. And MX check was one of the many parameters that helped me do my $DAYJOB
I did review my log for the weekend and that check caused zero false positives and helped filter spam.

> reject solely thanks to mx_ckeck 
that would be an error. 

It's fine to reject where no mx or apex a record, and also no mailserver responding at mx or a record after a very long timeout. But just checking for no mx and no connectable mx gives a very strong hint of spam too. And in the few dozen of spam filtered/greylisted because of that check, I have seen no errors.

Right now you're mixing 2 different things. Antispam techniques and implementation.
The pull is about a mistaken value and timeout. 
My idea is that a better check would be no-mx-or-a-record (like in ASSP), but that discussion should go to rspamd issues, not here. Anyway, the filter as it is implemented in rspamd, where they fixed the mistaken values is certainly fine and helps to stop spam especially from abused scripts and form where email is from @www.domain.ext or other hosts below the main domain.

if you think that the entire check is a nonsense I suggest you discuss it on rspamd github, maybe you can get the rationale behind the check as it is. For me it's a keeper, but the pull is about a different thing: a low timeout and wrong values, that have already been fixed and will be pushed with next rspamd official image.

**Comment by mkuron** [comment]
I do see the rationale behind mx_check, I just don't see it provide enough contrast (distinguishing spam and ham) and exclusivity (detecting spam that has not already been tagged by other methods like Bayes and DNSBL) to justify having it consume time and resources. That's why I would have liked to see numbers from someone else on how much it helps them detect spam (it doesn't help me at all). Also, rspamd disables mx_check by default and Spamassassin doesn't even have such a check as far as I'm aware -- so this check should probably be taken with a grain of salt.

**Comment by mkuron** [comment]
@marrco, I just had an idea how to eliminate the MX_MISSING false positives when only an A record is present. Could you update the PR accordingly? Create a [composite symbol](https://rspamd.com/doc/configuration/composites.html) that applies a score of -2.0 to messages that are both MX_GOOD and MX_MISSING. You could name it MX_IMPLICIT.

**Comment by marrco** [comment]
@mkuron that could be an excellent idea. 

Please review the changed files, I'm not sure if adding a line to mx_check.conf as symbol_implicit_mx = "MX_IMPLICIT"; is correct and enough for redis caching and timeout. And i did not check that MX_GOOD really tries to connect to an A record at the apex when no mx is defined, so I can't tell if this new MX_IMPLICIT will ever be true.

Anyway, that should fix the technical issue due to timeout and wrong defaults. Now we could discuss if the test is worth its return. After this fix, it's really low risk (still reporting wrong for @tiscali.it and probably a few others with greeting delay > timeout). Coming from ASSP and considering this is a pre-data check I definitely favor it, But if you want to remove the check completely that's not a problem for me, just please don't leave the wrong values and timeout in the actual active version.

**Comment by marrco** [comment]
I'm not sure MX_IMPLICIT value has been set correctly in the pull request. Can you please check it?

**Comment by mkuron** [comment]
I'll check later. It worked in my test. Can you provide the log output for a message that should have MX_IMPLICIT (`docker-compose logs rspamd-mailcow`)?

**Comment by marrco** [comment]
you're right, it's working fine. MX_INVALID and MX_MISSING add their scores and can be both present for a single message. 
instead, i always found MX_IMPLICIT alone, as the only MX check for a given message.

I wonder now if it should weight 0.50 instead of -.01 because the few samples I've seen in my logs all look like mass emailing.

**Comment by mkuron** [comment]
> I wonder now if it should weight 0.50 instead of -.01 because the few samples I've seen in my logs all look like mass emailing.

We should not. They have a valid MX (the implicit one) and a responding SMTP server. So they shouldn't be treated any different than if they had an explicit MX.
