### ISSUE TITLE
Email not showing up on Rspamd gui

### ISSUE THREAD

**Issue by K2rool** [mailcow/mailcow-dockerized#582]
I got a weird issue it's on a new install, Rspamd gui is only showing email that have been sent by the server, its not showing any emails that been sent to the server, i know the email are getting sent to Rspamd since the scanned counter is going up.

Am quite sure it is checking the email but it doesn't seem to be displaying them.

I got this from it's logs

<pre>
ESC[36mrspamd-mailcow_1     |ESC[0m 2017-09-11 22:35:19 #11(normal) <ccb38a>; task; rspamd_task_write_log: id: <5fc8379b6d74e44347db71df1989d47e@****.co.uk>, qid: <292F5C3BF690>, ip: 137.**.42.98, from: <ryan@****.co.uk>, (default: F (no action): [-0.40/15.00] [R_SPF_ALLOW(-0.20){+ip4:137.***.42.98;},MIME_GOOD(-0.10){text/plain;},MX_GOOD(-0.10){mail.***.co.uk;},ARC_NA(0.00){},ASN
(0.00){asn:16276, ipnet:137.74.0.0/16, country:FR;},DMARC_NA(0.00){***.co.uk;},DYN_RL_CHECK(0.00){},FROM_EQ_ENVFROM(0.00){},FROM_HAS_DN(0.00){},MID_RHS_MATCH_FROM(0.00){},PREVIOUSLY_DELIVERE
D(0.00){ryan@****.yt;},RCPT_COUNT_ONE(0.00){1;},RCPT_MAILCOW_DOMAIN(0.00){***.yt;},RCVD_COUNT_THREE(0.00){3;},RCVD_NO_TLS_LAST(0.00){},R_DKIM_NA(0.00){},TO_DN_NONE(0.00){},TO_MATCH_ENVRCPT_A
LL(0.00){}]), len: 805, time: 201.999ms real, 14.403ms virtual, dns req: 26, digest: 
</pre>

**Comment by andryyy** [comment]
Is it shown in mailcow UI -> Logs -> Rspamd?

**Comment by K2rool** [comment]
I've done more testing it not showing up on the Mailcow ui log for Rspamd too, the Rspamd and Mailcow ui Rspamd is currently only showing information for outgoing email and incoming ones that got rejected or soft rejected but not for email that Rspamd has accepted as fine.

On one my other server running Mailcow that i have not updated for a month or two, Rspamd log show ever email in and out rejected or not.

**Comment by VladimirBorisov** [comment]
Hello,

I have very similar issue - some emails not appears in redis history (in both mailcow ui and redis ui).
Using redis cli ( docker-compose exec redis-mailcow redis-cli ) MONITOR command I can see that trere is no attempt to write this log to redis.
At the same time in log ( docker-compose logs --tail=10 -f rspamd-mailcow ) I can see "rspamd_task_write_log" lines for all messages.
The only difference I can find so far in a rspamd log is
```
rspamd-mailcow_1     | 2017-09-14 20:54:42 #10(normal) <c76394>; task; rspamd_stat_check_autolearn: <E0030B7E-9D2A-4FF9-A83A-D8B9C7E7F882@gmail.com>: autolearn ham for classifier 'bayes' as message's score is negative: -0.35
rspamd-mailcow_1     | 2017-09-14 20:54:42 #10(normal) <c76394>; task; rspamd_stat_classifiers_learn: <E0030B7E-9D2A-4FF9-A83A-D8B9C7E7F882@gmail.com> contains less tokens than required for bayes classifier: 4 < 11
rspamd-mailcow_1     | 2017-09-14 20:54:42 #10(normal) <c76394>; task; rspamd_task_process: learn error: <E0030B7E-9D2A-4FF9-A83A-D8B9C7E7F882@gmail.com> contains less tokens than required for bayes classifier: 4 < 11
```
The overall process looks like this: message is good and get a negative score -> bayes try to learn but fail because message too short -> messages not appears in a log.

I also chack that:
- in case message get 0 or small positive score bayes not try to learn and message appears in history
- in case autolearn is set to false in statistic.conf bayes not try to learn and message appears in history

All this looks strange but I think that I check everything twice.

**Comment by K2rool** [comment]
Thanks @VladimirBorisov I've been too busy in the last few days to do
some debugging to find out what was causing this issue. 

I've looked the Rspamd log on my server and cross reference it with
Rspamd history your correct it's only happening on emails with
rspamd_task_process: learn error so that issue is due to bayes
autolearn.

**Comment by VladimirBorisov** [comment]
Hello,

Just to let you know - I believe that I do not see this issue after commit c45ea5433f2a3ab6120d9e1c5f4b4a48d8d82ce2 from 2017.11.15 14:29
