### ISSUE TITLE
Flatcurve: Problems with long E-Mails

### ISSUE THREAD

**Issue by DerLinkman** [mailcow/mailcow-dockerized#5986]
After I have activated FTS and started a reindex 
`( docker compose exec dovecot-mailcow doveadm fts rescan -A & docker compose exec dovecot-mailcow doveadm index -A '*' )`

I get this error.....

 Could not write message data: uid=271; InvalidArgumentError: Term too long (> 245): Au+mq6tanjqhftdijtjhu4wmojxgm3dizbygnrgkyzqmzsgmy3bhe4dqodfgvqtimdggnrgcjjugbzxo2lgoqxgozlomvzgc5dfmqtgqpldmzrwcn3ggbstsytfme3dizbsgbrgizjxgrrdqyzxmvrtqobrgytg2yljnrpwszb5gm2donbygizcm4r5nfxhizlsnzsxillqn5zxijjugbwgs5tffzqxijtuhusteqi@survey.pledgebox

same error as https://github.com/slusarz/dovecot-fts-flatcurve/issues/62

_Originally posted by @euDominic in https://github.com/mailcow/mailcow-dockerized/issues/5920#issuecomment-2228985741_

**Comment by h3ssan** [comment]
Hello @DerLinkman 

> As the [RFC-5322 - Addr-Spec Specification](https://www.rfc-editor.org/rfc/rfc5322#section-3.4.1) mentioned out that email address length should be maximum of 254 characters. 

The email address you provided is actually 251 characters, so should be OK.
So, I think the problem is with FTS, it is configured with only 245 characters long maximum. We need to re-configure it to 254 characters maximum.

Could you please confirm that the problem is actually as I said above?

**Comment by DerLinkman** [comment]
Hi @h3ssan @euDominic opened this issue in first place...

I'm not 100% sure if this is the issue here as i never touched the setting regarding length limits.

If you have an idea for this feel free to help.

**Comment by h3ssan** [comment]
Great, I'll try to fix the issue!

**Comment by MAGICCC** [comment]
Nice, I did have the same issue, but this should be an upstream issue no?

**Comment by h3ssan** [comment]
OK, well, 

There's something which is `Mailbox name is invalid`, yes it's invalid address. You cannot make such address with that long.

## Explanation

> Basically, you can't send to/receive from such address since it's incorrect, here's why:

```txt
local@domain.tld
```

- local part must be maximum 64 characters! Can't be longer than 64.


This also mentioned in [`RFC-5322 - Addr-Spec Specification`](https://www.rfc-editor.org/rfc/rfc5322#section-3.4.1), said:
```txt
An addr-spec is a specific Internet identifier that contains a locally interpreted string followed by the at-sign character ("@", ASCII value 64)
```

## How you received that long email?

Simply, don't know yet. Please provide more details how you received/sent such email at first place!? @euDominic

**Comment by MAGICCC** [comment]
> ## How you received that long email?
> 
> Simply, don't know yet. Please provide more details how you received/sent such email at first place!? @euDominic

I remember that I had 10 cases where the sender was mailgun or other newsletter relays. Too bad that I don't have the full sender anymore... Maybe with a force reindex I can see them again.

**Comment by h3ssan** [comment]
> I remember that I had 10 cases where the sender was mailgun or other newsletter relays. Too bad that I don't have the full sender anymore... Maybe with a force reindex I can see them again.

I tried to make a longer address in my mailcow but it refused since that long mailboxes are not valid so can't lame mailcow, tried to receive or send, but no luck.

I'll give it a little more time to fix it.

**Comment by h3ssan** [comment]
Finally, got the same error message which is: 

```txt
doveadm(MY_EMAIL): Warning: fts-flatcurve(Sent): Could not write message data: uid=1; InvalidArgumentError: Term too long (> 245): Aau+mq6tanjqhftdijtjhu4wmojxgm3dizbygnrgkyzqmzsgmy3bhe4dqodfgvqtimdggnrgcjjugbzxo2lgoqxgozlomvzgc5dfmqtgqpldmzrwcn3ggbstsytfme3dizbsgbrgizjxgrrdqyzxmvrtqobrgytg2yljnrpwszb5gm2donbygizcm4r5nfxhizlsnzsxillqn5zxijjugbwgs5tffzqxijtuhusteqi@survey.pledgebo
```

## Description

What I did to show this message?

I sent an empty email, and then edit the email from filesystem inside my server manually using vim, and added that long address `Aau+mq6tanjqhftdijtjhu4wmojxgm3dizbygnrgkyzqmzsgmy3bhe4dqodfgvqtimdggnrgcjjugbzxo2lgoqxgozlomvzgc5dfmqtgqpldmzrwcn3ggbstsytfme3dizbsgbrgizjxgrrdqyzxmvrtqobrgytg2yljnrpwszb5gm2donbygizcm4r5nfxhizlsnzsxillqn5zxijjugbwgs5tffzqxijtuhusteqi@survey.pledgebo`
Then, I tried to rebuild the cache, and here the error come out !

Will try to fix it now

**Comment by h3ssan** [comment]
Hi all,

Finally some good news, @DerLinkman, @MAGICCC and @euDominic

The problem is not with mailcow, but `email-address` of `fts_tokenizers`.
So the tokenizers of fts, especially `email-address` tokenizer have a limit of 245 characters of email address.

Here's the description from the [`official GitHub of Dovecot`](https://github.com/dovecot/core/blob/main/src/plugins/fts-flatcurve/fts-backend-flatcurve.c#L319), that it clearly said the following:
```c
/* Xapian has a hard limit of "245 bytes", at least with the glass
	 * and chert backends.  However, it is highly doubtful that people
	 * are realistically going to search with more than 10s of
	 * characters. Therefore, limit term size (via a configurable
	 * value). */
	size = I_MIN(size, ctx->backend->fuser->set.max_term_size);
``` 

Here's the `Xapian` which is the exception itself [`xapian/xapian/blob/master/xapian-core/tests/api_wrdb.cc`](https://github.com/xapian/xapian/blob/master/xapian-core/tests/api_wrdb.cc):
```c
    for (size_t i = 246; i <= 290; ++i) {
	tout.str(string());
	tout << "Term length " << i << '\n';
	Xapian::Document doc;
	string term(i, 'X');
	doc.add_term(term);
	try {
	    db.add_document(doc);
	    TEST_AND_EXPLAIN(false, "Expecting exception InvalidArgumentError");
	} catch (const Xapian::InvalidArgumentError &e) {
	    // Check that the max length is correctly expressed in the
	    // exception message - we've got this wrong in two different ways
	    // in the past!
	    tout << e.get_msg() << '\n';
	    TEST(e.get_msg().find("Term too long (> 245)") != string::npos);
	}
    }
```

Also, here we can change it to more than 245 characters, but they said it's not recommended to change at [`xapian-core/backends/glass/glass_database.cc`](https://github.com/xapian/xapian/blob/master/xapian-core/backends/glass/glass_database.cc):
```c

// The maximum safe term length is determined by the postlist.  There we
// store the term using pack_string_preserving_sort() which takes the
// length of the string plus an extra byte (assuming the string doesn't
// contain any zero bytes), followed by the docid with encoded with
// pack_uint_preserving_sort() which takes up to 5 bytes (for a 32-bit
// docid).
//
// The Btree manager's key length limit is 255 bytes so the maximum safe term
// length is 255 - 1 - 5 = 249 bytes.  We actually set the limit at 245 for
// consistency with flint and chert, and also because this allows for 64-bit
// docids.
//
// If the term contains zero bytes, the limit is lower (by one for each zero
// byte in the term).
#define MAX_SAFE_TERM_LENGTH 245
```

## How to temporary fix

Just remove the `email-address` from the `fts_tokenizers` inside file `data/conf/dovecot/conf.d/fts.conf`
```conf
# Autogenerated by mailcow
plugin {
    fts_autoindex = yes
    fts_autoindex_exclude = \Junk
    fts_autoindex_exclude2 = \Trash
    fts = flatcurve

    # These are not flatcurve settings, but required for Dovecot FTS. See
    # Dovecot FTS Configuration link above for further information.
    fts_languages = en es de
    fts_tokenizer_generic = algorithm=simple
    fts_tokenizers = generic email-address  # <------------ here is it

    # OPTIONAL: Recommended default FTS core configuration
    fts_filters = normalizer-icu snowball stopwords
    fts_filters_en = lowercase snowball english-possessive stopwords
}
```

The updated file should be:
```conf
# Autogenerated by mailcow
plugin {
    fts_autoindex = yes
    fts_autoindex_exclude = \Junk
    fts_autoindex_exclude2 = \Trash
    fts = flatcurve

    # These are not flatcurve settings, but required for Dovecot FTS. See
    # Dovecot FTS Configuration link above for further information.
    fts_languages = en es de
    fts_tokenizer_generic = algorithm=simple
    fts_tokenizers = generic

    # OPTIONAL: Recommended default FTS core configuration
    fts_filters = normalizer-icu snowball stopwords
    fts_filters_en = lowercase snowball english-possessive stopwords
}
```

It will keep caching the content but without the email address, till they fix it.

## More info on `data/conf/dovecot/conf.d/fts.conf`

The file `data/conf/dovecot/conf.d/fts.conf` is being auto-generated from `data/Dockerfiles/dovecot/docker-entrypoint.sh`. Therefore the edit must be from `data/Dockerfiles/dovecot/docker-entrypoint.sh` file.

## Final Conclusion

### We have 2 solutions

#### First Solution

We can temporarily exclude the email-address from being tokenized (whatever the right word). As I demonstrated the way above, and then after they fix it, we'll return the `email-address` tokenizer back to life.

#### Second Solution

Since this is not a big problem for most emails ( a problem for only emails that have an email address with more than 245 characters ), therefore we can ignore it and keep going in life!

___

@DerLinkman if you want me to do any of the said solutions please let me know and I'll apply the solution and push it to the stage branch!

**Comment by DerLinkman** [comment]
Honestly i would wait for it... as the issue has been reported in the upstream repo too.

The "fixed" version of flatcurve has not been pushed yet to Alpines repos so we have to wait and apply the patch then when it's live if it fixes this problem.

But many thanks @h3ssan for taking a look into it!

**Comment by DerLinkman** [comment]
It seems that in https://github.com/slusarz/dovecot-fts-flatcurve/issues/62#issuecomment-2287576540 there has been a undocumented setting for the fts tokenizers of dovecot.

I'll adapt this and limit it to the mailcow UI max allowed chars for a mailbox to align it accordingly.
