### ISSUE TITLE
TLS support error

### ISSUE THREAD

**Issue by samuelebistoletti** [mailcow/mailcow-dockerized#616]
Hi,
after last update I have this error on Postfix log:

18/9/2017, 10:44:45 | warning | warning: Invalid TLS protocol list "!SSLv2, !SSLv3 #, !TLSv1, !TLSv1.1": disabling TLS support

I think that last commit must have damaged Postfix configuration.

**Comment by JackThursby252** [comment]
In the last commit, the TLS options were planned to be more restrictive to secure protocols. But the '#' in this config creates a syntax error.

To temporarily fix this on your local mailcow, change the values around lines 72 to 77 in <mailcow-dockerized directory>/data/conf/postfix/main.cf and remove the '#'. So that the lines look like this:

`
smtp_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1                                                                         
smtp_tls_protocols = !SSLv2, !SSLv3                                 
lmtp_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1     
lmtp_tls_protocols = !SSLv2, !SSLv2, !SSLv3, !TLSv1, !TLSv1.1       
smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1    
smtpd_tls_protocols = !SSLv2, !SSLv3
`

It should be fixed in the repo soon too.

/Edit added actual content. Sorry^^

**Comment by andryyy** [comment]
Damn. Thanks.

**Comment by samuelebistoletti** [comment]
Thanks, I already reverted the commit. I opened the issue just to notify the problem. The problem is also that disabling TLS 1 and 1.1 would cause other issues with external services that are using that protocol. We are experiencing that issue right now, to fix that I removed !TLSv1, !TLSv1.1 from mandatory protocols.
