### ISSUE TITLE
[Question] Why switch to docker? And usage with nextcloud

### ISSUE THREAD

**Issue by Extarys** [mailcow/mailcow-dockerized#632]
All in the title :P
Why the switch to docker?

What are the disadvantages?
What are the advantages?

I never used docker and I'm kind of old school when deploying servers.

Also, how easy can I deploy this with my existing nextcloud installation?
Can I set the quota of nextcloud to work with this?

**Comment by mkuron** [comment]
Docker‘s main advantage is isolation of the different services from each other and from the host system. This gives security benefits and allows for easier upgrades.

Mailcow doesn‘t care about or integrate with Nextcloud, so you can deploy them side-by-side.

**Comment by Braintelligence** [comment]
Is there even any mail app that integrates with Nextcloud other than imap-webmail-apps?
So what does the Nextcloud quota have to do with this?

**Comment by Extarys** [comment]
I used this but it's no bundle and lack some informations https://thomas-leister.de/en/mailserver-debian-stretch/

**Comment by chriscroome** [comment]
@Braintelligence there is the [Nextcloud Mail App](https://apps.nextcloud.com/apps/mail) I would expect that this works without a problem with Mailcow.

**Comment by Braintelligence** [comment]
@chriscroome but that's a simple imap web client. It sounded like we're talking about more features. 

I use RainLoop on my NextCloud.

**Comment by chriscroome** [comment]
@Braintelligence sorry I misread before I posted, you are right.

**Comment by stevesbrain** [comment]
In addition to what @mkuron said, another benefit is ease-of-deployment or recovery. You have your config file? Great - get your new server, clone this repo, then `docker-compose up -d` and you're done :) Need to recover from backups? Just make sure that your vmail container/files are synced over, and do the same as above.

Because it's all in a docker container, you can recover it to any distro + server that runs docker - doesn't have to be the same version etc. anymore, and you don't have to worry about upgrades to the software breaking things, in that it's expected that any released version of mailcow has been tested as working :) Basically, just abstracts away a bunch of the administration tasks in order to save you time, and increase security.
