### ISSUE TITLE
Use latest version without Docker

### ISSUE THREAD

**Issue by lucianlazar1983** [mailcow/mailcow-dockerized#670]
Hi there, is there any way i could use the latest version of mailcow without Docker? I have implemented a LXD container service and cannot use Docker on top of it. Thanks!

**Comment by janxb** [comment]
Docker inside of LXD/LXC is possible, most of the bugs have been fixed with a LXC version some time ago.
Have you tried just using Docker inside your LXD container?

Here you can find some quickstart guide: https://stgraber.org/2016/04/13/lxd-2-0-docker-in-lxd-712/

**Comment by w194** [comment]
+1 @ecoitsolutions 
IMHO mailcow should switch to ansible-container. This would be the first step to a container-agnostic mailcow. There are lots of people who prefer k8s or LXC/LXD over Docker. Also, with ansible-container and Ansible one can get rid of these complex Dockerfiles and automate the whole installation and update process.
LXD is not supported yet in ansible-container (https://github.com/ansible/ansible-container/issues/78) but having YAML instead of Dockerfiles would simplify it to use mailcow entirely without Docker.

**Comment by Braintelligence** [comment]
@widder For you docker files may be "complex" but I don't know anything about ansible. I don't see the advantage of changing the whole mailcow structure to any other container environment.

**Comment by w194** [comment]
@Braintelligence The structure wouldn't necessarily change. The docker container images should have the same content as before. Docker-compose is replaced by Container.yml with similar options. It would be just easier to port mailcow to other container hypervisors.

**Comment by lucianlazar1983** [comment]
Or just simply a bash scritp that pulls from the repo and configures everything, no matter what hypervisor I use. At least give us this option as it was before with the old version

--
Lucian Lazar – System Engineer
ecoIT Solutions Srl
@       lucian.lazar@ecoit.ro
Tel     +40371783679
web   https://ecoit.ro

On Nov 2, 2017 21:03, widder <notifications@github.com> wrote:

@Braintelligence<https://github.com/braintelligence> The structure wouldn't necessarily change. The docker container images should have the same content as before. Docker-compose is replaced by Container.yml with similar options. It would be just easier to port mailcow to other container hypervisors.

**Comment by Braintelligence** [comment]
@widder Sounds like this could be done via PR request for an ansible-branch?

**Comment by andryyy** [comment]
The way stuff works right now, makes it pretty hard to just extract etc.

There is much more.

**Comment by mkuron** [comment]
> I have implemented a LXD container service and cannot use Docker on top of it.

You can probably install LXD and Docker side-by-side on the same host machine.

> There are lots of people who prefer k8s or LXC/LXD over Docker.

There are so many containerization platforms out there that it‘s impossible to support them all. Docker-compose is the most natural choice as Docker is the most widespread one and compose is a relatively thin layer on top of it.

> Also, with ansible-container and Ansible one can get rid of these complex Dockerfiles and automate the whole installation and update process.

Some of our Dockerfiles contain some rather nontrivial things, so the complexity is there for a reason.

> It would be just easier to port mailcow to other container hypervisors.

Mailcow explicitly uses Docker API functionality in multiple places, e.g. networking (ipv6nat), log access (fail2ban) and restarting containers (sogo, acme). That would need to be abstracted away to make platform-agnostic containers.

> At least give us this option as it was before with the old version

That‘s probably the most realistic suggestion, but it’s not easy either. Write a shell script that extracts the commands from the Dockerfiles, modify some paths to avoid name collisions and generate an /etc/hosts file with the internal host names. Then replace the explicit Docker API calls with equivalent shell execution.

**Comment by w194** [comment]
> Or just simply a bash scritp that pulls from the repo and configures everything, no matter what hypervisor I use. 

Will be definitely on my roadmap for my "docker-free" mailcow branch/fork. But I'm not sure if it makes sense right now as mailcow uses a mix of Alpine and Debian containers.

 > Mailcow explicitly uses Docker API functionality in multiple places, e.g. networking (ipv6nat), log access (fail2ban) and restarting containers (sogo, acme). That would need to be abstracted away to make platform-agnostic containers.

Thanks for pointing this out. I will consider this in my branch/fork

> That‘s probably the most realistic suggestion, but it’s not easy either. Write a shell script that extracts the commands from the Dockerfiles, modify some paths to avoid name collisions and generate an /etc/hosts file with the internal host names. Then replace the explicit Docker API calls with equivalent shell execution.

While this is possible it is much harder to make this bash script idempotent. With Ansible this is much easier. With Docker, idempotent scripts are not needed at all because you always rebuild the image from scratch. So extraction of these commands is not enough for a well working installation script. If you want a containerless mailcow to be update-able you need a script that you can run multiple times without any bad things to happen like data loss.

**Comment by killua-eu** [comment]
Untangling Docker stuff is a bit over my head, but I hardforked https://github.com/sovereign/sovereign, cut away everything non-mail related and did maintenance, version bumps and stuff here and there. The playbook is here: https://github.com/ubermail/ubermail

**Comment by killua-eu** [comment]
Untangling Docker stuff is a bit over my head, but I hardforked https://github.com/sovereign/sovereign, cut away everything non-mail related and did maintenance, version bumps and stuff here and there. The playbook is here: https://github.com/ubermail/ubermail
