### ISSUE TITLE
postfix mynetworks defaults

### ISSUE THREAD

**Issue by tudorbarascu** [mailcow/mailcow-dockerized#733]
Hi,

Really love your work (will donate right away 👍 ).

By default, my setup  (which should be a pretty standard one) leaves mailcow failing open relay tests and maybe reason why the mails I'm sending to gmail domains go into spam.

Setup:

router (public ip, 192.168...ip)

virtualized docker-server 192.168.. ip

In postfix ``main.cf`` I had to erase the ``192.168.0.0/16`` part from ``mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 [fd4d:6169:6c63:6f77::]/64`` as that was accepting open-relays from the internet.

My thoughts are to do one of these:

* Make a pull request and document how to solve this
*  shouldn't the ``mynetworks`` options be more restrictive? e.g. eliminate all but from localhosts and let's say 172.22.0.0/16? as we can setup from the admin an open relay of our choosing? just begun my email setup quest so I'm not an expert if this breaks stuff in other places

What do you think?

**Comment by mkuron** [comment]
This must be due to the NAT router in front of Mailcow, though it doesn‘t make much sense that requests appear to be coming from 192.168.x.x as the router should pass through the original source address.

Maybe you have disabled Docker‘s iptables rules and it is falling back to its userland proxy?

I think it would be fine to reduce mynetworks to the v4 and v6 mailcow networks and localhosts. It shouldn’t be necessary though as requests from the internet should never have private IP addresses.

**Comment by tudorbarascu** [comment]
Indeed, I moved mailcow on another docker server (not virtualized) and it worked like it should.
What's clear is that the router wasn't the culprit. Thanks!
