### ISSUE TITLE
Add rspamd quarantine support

### ISSUE THREAD

**Issue by lucianlazar1983** [mailcow/mailcow-dockerized#738]
Hi there, i would like to suggest adding the quarantine plugin for rspamd. It would be very convenient to be able to manage quarantined messages. The implementation is here:
https://github.com/sys4/rspamd-quarantine
I suppose it is not difficult to include it in the rspamd dockerfile?
Thanks

**Comment by mkuron** [comment]
My understanding of this plugin is that it makes rspamd submit all rejected messages to a web service so that one can manually inspect them later. Is that correct?

Since the (default) rspamd rejection threshold is quite high, it’s unlikely that you will find any non-spam email in this quarantine. And because the message was rejected, the sender doesn’t expect you to have received it, meaning you don‘t have to save it. And if you want to check what messages rspamd has rejected recently, you can already go to the rspamd web interface and see sender, recipient, subject, date/time and score in the history.

This plugin uses a PostgreSQL backend, while we have a MySQL/MariaDB database. So we can‘t use it. But you could easily rewrite https://github.com/sys4/rspamd-quarantine/blob/master/quarantine.py in less than 100 lines of PHP and incorporate that functionality into Mailcow if you need it.

**Comment by mkuron** [comment]
Fixed by #814
