### ISSUE TITLE
How to set up sending email from an alias (multiple identities)?

### ISSUE THREAD

**Issue by MrSuttonmann** [mailcow/mailcow-dockerized#767]
I have a wildcard alias set up which redirects *@plinkpaste.com to me@plinkpaste.com. However, sometimes I'd like to reply to an email from here@plinkpaste.com.

How can I set this up, if it's possible?

**Comment by mritzmann** [comment]
Doesn't it work with different identities?
https://support.mozilla.org/en-US/kb/using-identities

**Comment by CurlyMoo** [comment]
I have the same question. I have a@b.com and *@a.b.com. All mail sent to *@a.b.com is received by a@b.com. However, when in SOGo, i reply to a mail sent to c@a.b.com the sender address is a@b.com instead of c@a.b.com. So the question is, how can i reply with the same address the mail was sent to?

**Comment by mkuron** [comment]
You need to explicitly add that alias. How else could SOGo know about the address?

**Comment by CurlyMoo** [comment]
> You need to explicitly add that alias. How else could SOGo know about the address?

I'm able to set the `Allow to send as` setting to a certain wildcard. That could tell SOGo that it should use the addresses matching the wildcards as sender alias. And when it doesn't match it could use the default address.

**Comment by mkuron** [comment]
How should SOGo decide which ones to show of the infinitely many addresses that match the wildcard? It has no way to know which ones you care about or which ones have been used in the past.

**Comment by CurlyMoo** [comment]
> How should SOGo know which ones to show of the infinitely many addresses that match the wildcard? It has no way to know which ones you care about or which ones have been used in the past.

As i already said. In case of new mails it can use the default one, but in case of replies it can use the alias address. So it doesn't have to know all addresses, just the address a mail was directed to.

**Comment by mkuron** [comment]
SOGo doesn‘t support that, so there is nothing Mailcow could do. It can only have a relatively static list of addresses that comes from the database, but not dynamically depending on what the original message was.

Thunderbird might support it with some add-on, but that‘s probably the only email client that could.

**Comment by CurlyMoo** [comment]
Too bad. Thanks for the quick responses and wonderful suite.

**Comment by gelse** [comment]
I got the same problem, yes thunderbird can do that, with an addon even without explicitely defining an identity (you just get an editable text-box instead of a drop-down for the "From" field).
Also rainloop allows to add predefined identities, which get matched for if you hit the "reply" button.

yes, mailcow does forward the aliases to SOGo and even matches in replies, but it's a but clumsy that i have to explicitely state every identity that i want to use, especially for a catchAll-alias.

it would be nice if somehow SOGo would recognize that the current account is a catchAll and allow for manual entering the FROM-adress.
If my research is correct, that would be the "SOGoMailCustomFromEnabled" field in SOGo, so this would have to be set if the account is a catchAll.

Please correct me, if i am wrong.

**Comment by andryyy** [comment]
SOGoMailCustomFromEnabled is already YES and has another meaning.

Open an issue with SOGo, please. :)

**Comment by gelse** [comment]
What meaning does it have, then?
The docu says:

> Parameter used to allow or not users to specify custom "From" addresses from SOGo’s preferences panel.

**Comment by andryyy** [comment]
And that's what it does. :) You can set a custom default from address in the preferences.

**Comment by gelse** [comment]
ohhh, i get it, only ONE.
well, anyway, there is already an open ticket which roughly would do what i need: https://sogo.nu/bugs/view.php?id=768
