### ISSUE TITLE
after install login doesn't work

### ISSUE THREAD

**Issue by crazyman143** [mailcow/mailcow-dockerized#772]

**Comment by stevesbrain** [comment]
What have you tried logging in as? Presumably you've tried the standard "admin" and "moohoo"? What error message do you receive? Need a few more details @crazyman143 :)

**Comment by crazyman143** [comment]
sorry my post didn't include the details somehow:

Fresh install of mailcow dockerized on digital ocean Ubuntu 16.04.3 x64. Attempting to log into gui with admin/moohoo = 'Login failed"

tried using password reset procedure in documentation and get this: 

`Working, please wait...
ERROR 1146 (42S02) at line 1: Table 'mailcow.admin' doesn't exist
ERROR 1146 (42S02) at line 1: Table 'mailcow.admin' doesn't exist
ERROR 1146 (42S02) at line 1: Table 'mailcow.domain_admins' doesn't exist
ERROR 1146 (42S02) at line 1: Table 'mailcow.domain_admins' doesn't exist
ERROR 1146 (42S02) at line 1: Table 'mailcow.tfa' doesn't exist
`
obviously something wrong with the database. I tried starting interactive session with mariadb container. the 'mailcow' database and 'mailcow' user exist. I did the manual password reset per documentation and that just made it worse. started getting database 'access denied' messages in the console repeatedly. I wiped my vps and started over, now back to where I started and still can't log in.

edit:

now I notice after a few minutes the mariadb container goes into 'unhealthy' state as well. docker log shows crashing. docker log for the container attached. 
[log.txt](https://github.com/mailcow/mailcow-dockerized/files/1500823/log.txt)

**Comment by crazyman143** [comment]
also this is less of a problem but setting the port bindings in mailcow.conf seem to have no effect. I changed to ports 8080/8443 also per suggestion in the doc but the webserver still listens on 80/443

**Comment by stevesbrain** [comment]
Interesting - I did a fresh install on Ubuntu 16.04.3 myself yesterday without issue. One thing that might be worth clarifying @crazyman143 - did you use the official Docker repo's, or the Ubuntu repo's? Ubuntu repo's have an outdated docker version in them; I used the official docker repo's for mine (and grabbed latest version of docker-compose as well).

**Comment by crazyman143** [comment]
I just used the curl command that's in the documentation: 
`curl -sSL https://get.docker.com/ | sh`
since it comes straight from the docker site I assume its up to date?

**Comment by crazyman143** [comment]
tried again and this time instead of using root I setup another user and used sudo. Also ensured latest docker version is installed by following documentation on docker's website. same exact issue.

**Comment by andryyy** [comment]
No problem here. 

Unhealthy MySQL sometimes indicates low resources.

**Comment by crazyman143** [comment]
Any other thoughts on the login / missing database elements issue? still can't log in or use this. Would love to get it working.

**Comment by stevesbrain** [comment]
@crazyman143 If you want, I could do an "ascii cinema" capture of all the things I do/commands I type, then you could watch that and see if what you're doing is the same?

**Comment by crazyman143** [comment]
@stevesbrain If you have the time to do that yes, I would greatly appreciate the help.

**Comment by stevesbrain** [comment]
@crazyman143 - sure, [here it is](https://asciinema.org/a/uMAjGTfn1mp6P2JvDXH3Z7WKx). Sorry about the massive pause whilst security update list gets updated - takes a while :P I followed the [Docker install guide here](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-docker-ce-1) in case you wish to copy + paste from there! I use elinks at the end btw just to prove I can login as admin user (just because I can't show you the GUI web browser with asciinema)

**Comment by crazyman143** [comment]
@stevesbrain Thanks a ton. I followed along with your recording exactly. You ran the update.sh script, which is not what I was doing because it's a clean install. well I went ahead and just did what you did and that seems to have worked.

**Comment by stevesbrain** [comment]
@crazyman143 Glad to hear it :) The only difference with the update script is that it pulls the latest docker-compose direct from the web, rather than the repo's, and then obviously it pulls latest docker images too. I expect docker compose versioning was *probably* what was causing the issue, given that update.sh is technically not needed - however, then I tried a direct `docker-compose up -d` with the repository version of docker-compose, there were format issues. Either way, glad it worked :)
