### ISSUE TITLE
How can I get or create a "GAL" in SOGo

### ISSUE THREAD

**Issue by jm3west** [mailcow/mailcow-dockerized#773]
Hi guys,

I don't understand the GAL in SOGo!
How can I get or create this

Kind regards
jm3west

**Comment by Braintelligence** [comment]
I could be wrong but I think the GAL doesn't work with a mysql setup, which mailcow uses.
Did I guess correctly, @andryyy ?

**Comment by andryyy** [comment]
It is a global address book and working just fine. Just type a users name or mail address to search for an element.

**Comment by MosabWadea** [comment]
@andryyy

Hello andre, I would like to ask if it is possible to edit the name of the GAL and the fields to show?

I would like to edit all personal data of the company contacts and add pictures for them so that users can see all other users and their public information. 

and can I create another list that can be edited by users and give rights to users from some kind of admin interface?

Thanks

**Comment by MosabWadea** [comment]
or is there any other application that I can add and link to mailcow from the "customization" sector where I can edit and manage contacts and lists?

this app for example?
https://github.com/sabre-io/Baikal

**Comment by andryyy** [comment]
You cannot edit SOGos GAL, but you can create a new shared address book and grant everyone access to it. :)

**Comment by MosabWadea** [comment]
Thanks Andre
however, I can see in the documentation that I can grant access to any user, but I can't see this option in my setup. I have to select each user every time.

Also I would like to ask, is there any way that I can make default settings for every user? for example I would like to make the personal calendar shared with everyone so that setting up a meeting can be easier.

**Comment by MosabWadea** [comment]
@andryyy 
Sorry andre if I am annoying you, I have a question now if you don't mind.
is it possible to change the avatar to a custom one? I can see that there is an option to enable gravatar but I can't see if I can upload one.
