### ISSUE TITLE
Can't receive mail

### ISSUE THREAD

**Issue by Jaxophon** [mailcow/mailcow-dockerized#776]
I can send mails but I cant receive them.

Example:

info@mydomain.com
When I SEND mails from this mail address it works and my partner receives them.

myprivatmail@mail.de
When I SEND mail from this mail address to info@mydomain.com it dosent work and info@mydomain.com dosent receive the mail. For each try i get an mail from mail.de with an error:

The Message I get:

This is the mail system at host shout02.mail.de.

I'm sorry to have to inform you that your message could not be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can delete your own text from the attached returned message.

                   The mail system

<info@mydomain.com>: Host or domain name not found. Name service error for
    name=mail type=AAAA: Host not found

**Comment by harm-matthias-harms** [comment]
same problem here :(

         550-Requested action not taken: mailbox unavailable
         550 invalid DNS MX or A/AAAA resource record
from other email:

        Host or domain name not found. Name service error for
        name=mail type=A: Host not found
DNS settings:

        @ in A XX.XXX....
        www in A XX........
        autoconfig in CNAME mail
        autodiscover in CNAME mail
        * in A XX.X.....
        mail in A XX........
        @ in MX 10 mail 
Server also needs to run websites so port forwarded to 127....:8080 by nginx

**Comment by Jaxophon** [comment]
Hope someone can help us to fix this soon :/

**Comment by andryyy** [comment]
Looks like DNS queries do not work. Does your provider block this traffic?

**Comment by Jaxophon** [comment]
I dont think so. I mean why should he do this. 
maybe it helps you or someone else, here are my settings.

DNS Settings:
```
mail.mydomain.com in A IPV4_OF_MY_SERVER
autodiscover.mydomain.com in CNAME mail
autoconfig.mydomain.com in CNAME mail
imap.mydomain.com in CNAME mail
smtp.mydomain.com in CNAME mail
pop3.mydomain.com in CNAME mail
@ in MX 10 mail
mail.mydomain.com in AAAA IPV6_OF_MY_SERVER
@ in TXT v=spf1 a mx ~all

```

If I execute "hostname" or "hostname --fqdn" via ssh i gives me "mail.mydomain.com" out.
thurther more i have two PTR Records at my server provider:

1. IPV4_OF_MY_SERVER and 2. IPV6_OF_MY_SERVER on mail.mydomain.com

**Comment by harm-matthias-harms** [comment]
I know that DNS settings can take a while until they are working, but issue still exists after 48 hours.
Online DNS checker say it's allright but on reverse ip->host the server hostname by provider shows up, not `mail.xxx.com` or `xxx.com`. But the domain is working, as other webapps are showing, but they are not dockerized and I don't know much about docker. I also don't think so that the provider blocking traffic, be cause other with same servers and domains host mail-servers. Mailcow was installed yesterday. DNS-settings 2 days from now. But yeah it looks like DNS query a bit.

**Comment by harm-matthias-harms** [comment]
ok I fixed it. In docs there is under DNS setup following line:

        @                   IN MX 10   mail
On my providers hompage they say:

        @                  IN MX 10 mail.domain.com
Is working better. Changed it now. Working fine and instant. :)

**Comment by luxflux** [comment]
Hm... usually adding `@ IN MX 10 mail.domain.com` means that the DNS server should expand it to `@ IN MX 10 mail.domain.com.domain.com.`, which is exactly what happens if you add `@ IN MX 10 mail`: it becomes `@ IN MX 10 mail.domain.com`.

If you want to prevent this automatic expansion, you'd have to write `@ IN MX 10 mail.domain.com.` (notice the last dot).

I don't know how you provider handles this, though. Which one do you use?

**Comment by harm-matthias-harms** [comment]
It's a cheap netcup.de domain. In their docs it's handled diffrent, but that was the same thing i thought first. ;). But now its working, maybe because it's right for netcup or caused by try and error. I don't know.

**Comment by KarstenHahn** [comment]
@matze-h
My mailcowserver is hosted by Netcup too without problems, maybe I can help you to configure youre domain in the ccp-UI?
Karsten
Am Dienstag, November 28, 2017 15:48 CET, matze-h <notifications@github.com> schrieb:
 
It's a cheap netcup.de domain. In their docs it's handled diffrent, but that was the same thing i thought first. ;). But now its working, maybe because it's right for netcup or caused by try and error. I don't know.

**Comment by harm-matthias-harms** [comment]
@KarstenHahn my server is now working fine and fast. But thank you 👍 . Hope @Jaxophon can fix his Problem soon.

**Comment by Jaxophon** [comment]
Yeah it works fine thanks man :D
