### ISSUE TITLE
Relayhost for external aliases

### ISSUE THREAD

**Issue by stephtr** [mailcow/mailcow-dockerized#782]
Relayhosts can now be defined on the administration site and assigned to domains, but that only applies to mails sent from those domains, not to mails which get received by such a domain and alias-forwarded to an external mail address.
Since there are no other settings available in the latter case one still has to edit the `postfix/main.cf` file, even though [[documentation] Setup a relayhost](https://mailcow.github.io/mailcow-dockerized-docs/firststeps-relayhost/) doesn't contain the information anymore.

**Comment by jgeusebroek** [comment]
I ran into the same problem; my quickfix was to add the host to mynetworks.

**Comment by hachre** [comment]
I also noticed today that relayhosts are not used for mails sent from alias domains. Maybe related?

**Comment by andryyy** [comment]
>  not to mails which get received by such a domain
What do you mean?

> alias-forwarded to an external mail address.
Yes, that's true.

@hachre No, I just checked, it works for alias domains. :-/

**Comment by stephtr** [comment]
I just meant that if I create an email alias (a@my-domain.com -> b@gmail.com), I can't specify a relayhost which should be used to forward the mails to the external mail address (in the sample case gmail), since the relayhost defined in the domain configuration applies only to mails going out from mailboxes.

**Comment by einig** [comment]
I just ran into the same problem, as I used an alias to create a small mailinglist with 2 internal addresses and 2 external addresses. My temporary fix was to set up a filter in SOGo with the "To:" filter set to the alias address at my domain and then forwarding the mail to the recipients. While this works for now, I am very interested in a fix.

As I have configured a relayhost for the domain itself, why not 'simply' check if the target of an alias is a foreign domain and in this case use the relayhost configured for the original domain?

**Comment by stephtr** [comment]
Since I previously used one single relayhost for all domains, my temporary workaround was to manually setup the relayhost as specified in a [previous version](https://github.com/mailcow/mailcow-dockerized-docs/blob/ead346bccd1bb7d65dc40455dac23b85abdf825b/docs/firststeps-relayhost.md) of the documentation.

**Comment by einig** [comment]
Now this is even more confusing. I'll look into your suggestion later @stephtr 

I added a new alias called 'test@mydomain' with 'mymail@mydomain' and a test email 'test@test'. All mail is successfully delivered using the relayhost:
XXX: to=<test@test>, orig_to=<test@mydomain>, relay=smtp.host[X.X.X.X]:587, delay=0.54, delays=0.04/0/0.24/0.26, dsn=2.0.0, status=sent (250 Requested mail action okay, completed: id=XXX)

The original alias called 'alias@mydomain' with 4 addresses, including 'recipient@test' (yes, both test domains are the same) fails to deliver, because the relay is not used:
24322E0CA3: to=<recipient@test>, orig_to=<alias@mydomain>, relay=none, delay=2204, delays=2203/0.01/0/0.19, dsn=4.0.0, status=deferred (delivery temporarily suspended: host @test[X.X.X.X] refused to talk to me: 554-test Nemesis ESMTP Service not available 554-No SMTP service 554-Bad DNS PTR resource record. 554)

Could it be, that this is due to the fact that I created the alias before setting the relayhost?

**Comment by einig** [comment]
I deleted the alias and re-created it. Now it is using the relayhost. Could someone verify this behaviour?

1. Setup domain without relayhost
2. Create alias to external mail
3. Send mail to the alias, check log for usage of relayhost (should be none)
4. Setup relayhost for domain
5. Send mail to the alias, check log for usage of relayhost (probably be none, but should be relayed)
6. Remove and re-create alias
7. Send mail to the alias, check log for usage of relayhost (should be relayed)
