### ISSUE TITLE
add config option to disable sogo

### ISSUE THREAD

**Issue by pschiffe** [mailcow/mailcow-dockerized#785]
Hello, there is couple of options to disable some services, like clamd, fail2ban, etc. It would be great to have such option also for sogo, as some users may prefer to use different web mail client, or when trying to use mailcow as smtp server only (my case). Thanks.

**Comment by pschiffe** [comment]
Dovecot also doesn't need to be running for smtp only deployment, so options to disable sogo and dovecot would be great.

**Comment by K2rool** [comment]
The option to disable Sogo might be helpful for some user that don't need any exchange/activesync and who are happy with just IMAP.

Not sure why you would what a option to disable Dovecot you can't have a full mail server setup without a IMAP server.

 Anyway Postfix in Mailcow is broken without Dovecot since it needs it to deliver email to mailbox and it also uses it for SMTP authentication.

**Comment by pschiffe** [comment]
For smtp only deployments of mailcow - i.e. smtp for sending emails from infrastructure, for mailing list, etc. But if that's too much hassle, it doesn't really matter. Sogo is eating significant enough amount of memory, so that would make much more sense.

**Comment by UtechtDustin** [comment]
Any update on that issue ?
Is it possible, Sogo needs to much memory for running without any reason.

**Comment by andryyy** [comment]
You can stop the container or set the workers to 1.

**Comment by pschiffe** [comment]
Even though the work-around is available, I still think this is a valid feature request.

**Comment by andryyy** [comment]
It is not planned at the moment.

**Comment by Braintelligence** [comment]
@pschiffe Why don't you submit a PR that stops the container or sets workers to 1 when a specific env is set? :)
