### ISSUE TITLE
show used quota in domain list

### ISSUE THREAD

**Issue by swoga** [mailcow/mailcow-dockerized#833]
Hi,

currently the domain list displays the sum of max quota of all mailboxes per domain.
I think it would be more useful to display the actual used amount.

![image](https://user-images.githubusercontent.com/3697291/34342245-bb91bb0c-e9a9-11e7-9b99-6145fcddebc7.png)

**Comment by andryyy** [comment]
Example: You have assigned 2 GiB per mailbox for 5 mailboxes = 10 GiB. Now let's say everyone uses 1 GiB. It would show 5 of 10 GiB but you won't be able to create a new mailbox in this domain, because the domain has reached its quota.

We could add information about the amount currently in use. But it doesn't really help. One mailbox could be 90% in use, another 10%. Averaging both values will not warn you about mailbox 1 hitting its limit.

**Comment by swoga** [comment]
I understand the intentions behind the currently displayed values, but I thought it might be nice to see the values really in use.

I will implement it and create a pull request when I have some time.

**Comment by swoga** [comment]
Implemented in 92f8b4a09156c5b30d6f4fc49e82a38208d500a6.
Thanks @andryyy!
