### ISSUE TITLE
Folder /var/lib/docker/vfs is huge !

### ISSUE THREAD

**Issue by ghost** [mailcow/mailcow-dockerized#840]
Hello
On the docs it says we need about 5Gb to install mailcow, but once installed the folder /var/lib/docker/vfs is 25Gb in size and has about 150-200 folders... I tried a lot of docker commands to prune/pruge/clean/whatever but I just got 85Mb back...

I'm using docker on top of a LXC machine, I know it's not the best practice but I have 5 others LXC machines with different containers and no size problems up to now...
Did I miss something somewhere ? I'm pretty new to docker so I probably missed the magic command.
Thanks

**Comment by hachre** [comment]
I don't have that folder on my mailcow system. So as a docker layman myself, I'd say this wasn't created by mailcow.

**Comment by ghost** [comment]
Well it was... ;) I prepared an empty machine, installed docker and then the docker-compose pull took forever as I saw my disk getting nearly full.

**Comment by hachre** [comment]
Something must have gone wrong, on my system all of mailcow fits into ~5 GB as advertised. Did you build the images instead of pulling? I'm not sure what might have happened.

Maybe something about your LXC host throws Docker off?

Did you follow the steps as described here?
https://mailcow.github.io/mailcow-dockerized-docs/install/

**Comment by ghost** [comment]
I simply followed this doc : https://mailcow.github.io/mailcow-dockerized-docs/install/
I also rebuilt my machine twice with the same results... strange thing.

**Comment by hachre** [comment]
I think it would be helpful if you could do a new setup and run the output of `docker-compose pull` into a file that you can attach here. Maybe that'll give some clues.

**Comment by MAGICCC** [comment]
Seems so that LXC edited the `/etc/docker/daemon.json` (Something like https://github.com/lxc/lxd/issues/2305)
Best storage driver is still overlay2, but mailcow doesn't use it by default, don't ask me why
See [this ](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/) as reference

**Comment by mkuron** [comment]
The vfs storage driver copies everything, while aufs and overlayfs2 do union mounts. If you chose the vfs driver, these 25 GB sound perfectly reasonable.

This is not a Mailcow problem. It doesn't choose a storage driver. Docker chooses overlayfs2 by default (I think) and you can set a different one in /etc/docker/daemon.json. If LXC requires you to use vfs, then that is unfortunate. The issue @MAGICCC found is the right one, and using btrfs as suggested there may be a good workaround.

**Comment by kilo42L** [comment]
Mine defaulted to vfs by default. There should be some information on this on the install instructions as an optional setting to check.
