### ISSUE TITLE
How to change Mailrouting / Transport IP for a specific Domain

### ISSUE THREAD

**Issue by hansapils** [mailcow/mailcow-dockerized#847]
Hi there,

I need to add a specific route to a local mailserver for a single domain. For example, all mails sent to the domain "123.com" from mailcow should be sent to a local mailserver (192.168.1.2).

I could not find the option to specify this mailroute. Is there a way to specify this in a configuration file?

Regards,
hansapils

**Comment by mkuron** [comment]
Mailcow doesn‘t provide a user interface for this feature, but you can manually configure it in Postfix‘s main.cf. The parameter is called `transport_maps`. For details, see the Postfix manual.

**Comment by marrco** [comment]
this is related to https://github.com/mailcow/mailcow-dockerized/issues/56 that was marked as an enhancement last year

**Comment by hansapils** [comment]
Hi, 

since mailcow is running dockerized, postfix is installed on the subsystem. I figuered out, that I can use "docker exec -it XXX /bin/dash" to enter the bash of the postfix-container (mailcow/postfix). In this I added the following line to the main.cf

`transport_maps = hash:/etc/postfix/transport`

in this file I wrote the following line
`ExampleDomain.com smtp:[10.16.1.2]`

and rebuild the transport map:
`postmap /etc/postfix/transport`

I restarted the whole server, logged in to SOGo and tried to write an Email to "r@ExampleDomain.com". But I am still getting the following error:

> warning: no MX host for ExampleDomain.com has a valid address record
> 
> 0D87D442C18: to=<r@ExampleDomain.com>, relay=none, delay=0.85, delays=0.84/0.01/0/0, dsn=5.4.4, status=bounced (Host or domain name not found. Name service error for name=mail.ExampleDomain.com type=AAAA: Host not found)

So it seems, like postfix does not care about the transport_maps and is still resolving from public DNS. But why?

**Comment by catcun** [comment]
It also happened to me. Try executing the following (make sure the path is correct):
docker-compose exec postfix-mailcow postconf -e "transport_maps = hash:/etc/postfix/transport"
restart postfix:
docker-compose restart postfix-mailcow
confirm: 
docker-compose exec postfix-mailcow postconf transport_maps

**Comment by hansapils** [comment]
Hi,

i fail on the first command:
```

serveruser@mxa:~$ cd mailcow-dockerized/
serveruser@mxa:~/mailcow-dockerized$ ls
CODE_OF_CONDUCT.md  CONTRIBUTING.md  data  docker-compose.yml  generate_config.sh  helper-scripts  LICENSE  mailcow.conf  README.md  update.sh
serveruser@mxa:~/mailcow-dockerized$ docker-compose exec postfix-mailcow postconf -e "transport_maps = hash:/etc/postfix/transport"
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

**Comment by catcun** [comment]
I would say that is a problem with docker/docker-compose
But the important command is 
postconf -e "transport_maps = hash:/etc/postfix/transport"
you can try executing it from a shell into the postfix container

**Comment by hansapils** [comment]
Hi, i tried this and rebooted the server. The command was executed without a failure, but when I try to sent a mail to "r@ExampleDomain.com" I still get the following error:

`69F2C442C2D: to=<r@ExampleDomain.com>, relay=none, delay=1.6, delays=1.6/0.02/0/0, dsn=5.4.4, status=bounced (Host or domain name not found. Name service error for name=mail.ExampleDomain.com type=AAAA: Host not found)`

This is driving me crazy. I also tried to modify "/etc/hosts" and added an IP for "mail.exampleDomain.com". But postfix is ignoring this. :-(

**Comment by andryyy** [comment]
@hansapils Are you sure the transport map is now configured correctly?
For the extra host: Just edit docker-compose.yml and add "extra_hosts" like this:

```
    postfix-mailcow:
      ...
      extra_hosts:
        - "somehost:1.2.3.4"
      ...
```

Oh, and run docker-compose up -d afterwards.

**Comment by catcun** [comment]
@hansapils
That's a DNS problem. Postfix is trying to use IPv6 but there is no AAAA record for mail.ExampleDomain.com 
And I guess that what you put in /etc/hosts is a IPv4 address
If you want to force postfix to use only IPv4 you can change the line 
inet_protocols = all 
to 
inet_protocols = ipv4
in data/conf/postfix/main.cf
and restart postfix

**Comment by andryyy** [comment]
I'm back in the afternoon, I can have a look at your system then. 👍 Just let me know by mail.

**Comment by hansapils** [comment]
Hi guys,

thank you for your help so far. It is still not working.

It took me some time, to find out how the syntax of "docker-compose.yml" is supposed to be. I made the changes and could modify "etc/hosts" in the container. The postfix-Container is now able to resolve the servername, but postfix is not. 

Postfix is still resolving from somewhere else and is ignoring the tranport map. 

I also disabled ipv6 by changing the "inet_protocols" to ipv4 and tried "disable_dns_lookups=yes ".

i am getting desperate. Is there anything else, I could try?

**Comment by hansapils** [comment]
Could I define my own DNS in the postfix container?

**Comment by catcun** [comment]
It seems to me that there is something wrong with your mailcow installation. I have to admit that I had to wrestle with both the .cf files and postconf untils everything worked. But it does, and is very reliable.
I don't think I can help anymore, but I'm sure the "Host not found" error is DNS/IPv6 related

**Comment by andryyy** [comment]
You forgot the correct config path in the postconf command. By default it uses /etc/postfix, but we place them in /opt. Just add that transport map line in data/conf/postfix/main.cf and run postmap /opt/postfix/conf/yourtransportmapfile.bla via docker-compose exec. 

Mit besten Grüßen
André Peters

**Comment by hansapils** [comment]
Hey André,

tausend Dank, thank you! That was the trick. I was working on the wrong directories. 

Regards!

**Comment by chaosbunker** [comment]
I am trying to do this also but it doesn't work and I can't figure out why. For the domain example.com I want to use a specifix mx server when sending mail there from a mailcow address. 

What I did so far is
>add `transport_maps = hash:/opt/postfix/conf/transport` to main.cf
>add `example.com smtp:[<ip address of mx>]` to /opt/postfix/conf/transport
>and then rebuilt the transport map with `postmap /opt/postfix/conf/transport`

.. i also restarted postfix-mailcow. But mail is not delivered via the ip i set in transport.
The problem is that the address I want to deliver to is normally connected to a "regular" webhost but i added dns records so i can send and receive emails for my address (me@example.com) on my mailcow server. so example.com is also added to my mailcow and that's why mailcow delivers outgoing emails to someoneelse@example.com straight into the mailcow instead of delivering to the correct mx. 

What am I missing?

**Comment by andryyy** [comment]
Can you post the output of `docker-compose exec postfix-mailcow postconf -c /opt/postfix/conf transport_maps` and `docker-compose exec postfix-mailcow cat /opt/postfix/conf/transport`, please?

**Comment by chaosbunker** [comment]
transport_maps = hash:/opt/postfix/conf/transport
example.com smtp:[xxx.xx.x.xxx]

the output shows the correct ip

**Comment by andryyy** [comment]
Ah, wait, you added example.com, which is a virtual domain in mailcow, to the transport map?

**Comment by chaosbunker** [comment]
yes, example.com is added to mailcow and a mailbox exists for me@example.com and a catchall for example.com (that my emails to someoneelse@example.com get delivered to). all other addresses are running via the mx ip i set in /opt/postfix/conf/transport

**Comment by andryyy** [comment]
I don't think that will work for a domain virtual_domain_maps.

**Comment by chaosbunker** [comment]
Hm. So there is no solution? I know my configuration is a little ridiculous, but it would be cool if I could make this work, because I would have all my emails on one private (mailcow) server ..

**Comment by andryyy** [comment]
I don't think so, but I also don't understand this part: "The problem is that the address I want to deliver to is normally connected to a "regular" webhost but i added dns records so i can send and receive emails for my address (me@example.com) on my mailcow server. so example.com is also added to my mailcow and that's why mailcow delivers outgoing emails to someoneelse@example.com straight into the mailcow instead of delivering to the correct mx."

Another idea would be to check the checkboxes for "Backup MX" to mark it as relay domain. But I'm not sure this will work.

**Comment by chaosbunker** [comment]
Ah ok. so basically my family has a domain example.com and we all have an email address. we also own example.net and this will become relevant later in this post. the domains dns is managed by the webhost "xyz" of my father, so the mx is the webhosts mx. Instead of having my emails stored on and hosted by that webhost, I wanted them to be going through my mailcow server. So i added the example.com to my mailcow, created my mailbox me@example.com, added necessary dns records in cpanel of "xyz"-host (dkim._domainkey generated by mailcow for example.com  and added the mailcow servers ip4 to the spf record, and also added _dmarc.example.com) .. i also set the mx record for example.NET to be mx.mycow.com and created an alias me@example.net that forwards mail to me@example.com. i used imapsync to move all mails to me@example.com on my server, deleted the mailbox on "xyz" and on "xyz"-host i created a forwarder that forwards emails from me@example.com to me@example.net on my cow and then from there into my cow inbox for me@example.com.

now everything works just as I want it to, except that now if i send an email to any familymember@example.com it gets delivered internally instead of the mx of "xyz".

god, writing this down i realize how silly this whole setup is 😮 🤣 And it's probably still quite confusing.

but still, i kind of like the idea of storing my mail on my cow. it's more than 8GB and would take up almost half of my family's space on that host...

**Comment by chaosbunker** [comment]
I figured it out. Adding the mailboxes in question in mailcow makes the transport work, but all this is a bad idea. i just realized mail sent to me from xyz cannot be delivered because my address does not exist on xyz. i know i could fix that too, but I guess I will have to give up that email address as my primary address and just forward emails to my alternate address, that way i avoid this horrible, horrible setup :-)

**Comment by nupplaphil** [comment]
I'm currently working on a dynamic "transport_map" per user and/or per domain.
Just have a look at https://github.com/nupplaphil/mailcow-dockerized/tree/new_transport

I want to set up mailcow as a new antispam/antivirus-gateway for my MS Exchange environment :-).
-> And yes I already tried to completely switch to mailcow, but I do need some features, which are currently shown under "known issues" (f.e. labeling)

**Comment by andryyy** [comment]
Cool. :-) The sender dependent default transport map option is not working for you?

**Comment by nupplaphil** [comment]
@andryyy You're right. I didn't recognized it yet, but it should work for the "per user" setting. Maybe we can talk in another topic, I don't want to hijack this one any further ;-).

**Comment by alxhlz** [comment]
Do you have any new information about this?
