### ISSUE TITLE
fail2ban network block size

### ISSUE THREAD

**Issue by catcun** [mailcow/mailcow-dockerized#935]
Is it me of fail2ban is blocking /24 and /64 networks instead of just the offending IP?
If that's the case, how can I change it to only ban the IP? DO I need to change logwatch.py?

**Comment by mkuron** [comment]
You would need to change the script and rebuild the container. This is not meant to be configurable as blocking less than a /64 is pointless with v6 (almost always, the client can freely choose the host part of its address). /24 was chosen for v4 as that is the smallest allocation unit. If you have certain hosts that run into the block too often but are otherwise trustworthy, consider adding them to the whitelist instead.

**Comment by catcun** [comment]
@mkuron
Thank you, I will do as directed. 
The reason I am concerned is that many attacks I am seeing on Mailcow and other servers are coming from hacked PCs with IPv4 and blocking the whole class C seems like too much. Specially when many ISPs are now using NAT for their clients.

**Comment by mkuron** [comment]
If you have both legitimate clients and attackers in the same /24 (or even NATed behind the same IP), perhaps you should file abuse reports with that ISP. NAT of course violates the assumption that fail2ban makes, but there is nothing we can do about it. If an IP causes too many authentication failures, we just block its /24 to be on the safe side.

**Comment by ChessSpider** [comment]
I changed the script to block /32, that works as expected.

**Comment by andryyy** [comment]
Forgot to refer this issue in the last dev commit. It is now configurable as it was very easy to implement (+ I was changing that file anyway). I'd still listen to @mkurons advice. 👍
