### ISSUE TITLE
Outlook for Mac 16.9 Office 365

### ISSUE THREAD

**Issue by develth** [mailcow/mailcow-dockerized#978]
HI there, 

i wanted to test Mailcow with the Outlook for mac. 
The autodiscover always fails, and a lot of confirm / refuse dialog appears.

At some point it goes on but quits with message 

"Unable to connect to the server. Pleas try again"

In mailcow admin, debugging, logs, autodiscover the status for the request is green.

In the MailCow docks this is documented:

```
Outlook 2011 or higher on macOS
The Mac version of Outlook does not synchronize calendars and contacts and therefore is not supported.
```

Is this related? Why it does not work and why it isn´t fixable?

Thanks,
Thomas

**Comment by develth** [comment]
Removed misleading stuff.

**Comment by Ringelnatz** [comment]
This is the information I got related to Outlook for Mac: https://github.com/mailcow/mailcow-dockerized/issues/681#issuecomment-339716114
I configured mail with the Apple Mail app and contacts/calendar also using the Apple apps and Cal/CardDAV.

**Comment by develth** [comment]
Ok, read that already. Don´t want to use Apple Mail as Mail-client so i was / am search(ing) for a solution.

**Comment by mkuron** [comment]
The Mac version of Outlook doesn‘t support CardDAV/CalDAV (not even with a plugin like the Windows version). It doesn’t support ActiveSync either as far as we know.

You can use IMAP for emails only, but you have to manually configure it because we don’t fully understand Outlook 2016‘s autodiscovery and there is no documentation available on it.
