### ISSUE TITLE
Make mynetworks (postfix) setting persistent

### ISSUE THREAD

**Issue by D3luxee** [mailcow/mailcow-dockerized#987]
Hello,

All my vServers are running behind a firewall with RFC1918 ipv4 addresses (NAT), since all this servers also got a global routable ipv6 address they send mails via ipv6 to the mailcow instance.

Ive added my /64 network to the "mynetworks" setting but with the updates they get removed.

It would be nice if this setting would be persistent or even configurable from the webinterface.

**Comment by mkuron** [comment]
I don‘t think we could make it configurable from the we UI because it is not a map. So it can’t be pulled from MySQL.

If you use the update script, it just overwrites all local changes that are in conflict with the repository. That could be changed to ignore the repository‘s changes, but then your problem would go the other way.

So the only solution would be to set the mail service on the other machines to prefer IPv4.

**Comment by tehXor** [comment]
I don't know about the update script but at the start of this project it was suggested to use git to manage updates.

I do this since then and am also having some bigger customizations than only some config files. Anyhow, I cannot complain. This project is well structured and the maintainer is doing a good job to keep git in order. So as soon as you start to customize files (also config files) I'd suggest you use git as well. If you are already familiar with git this will be really easy, if not you will have to catch up with some git basics but it also shouldn't be too hard. The basic workflow will be something like this: 

- Initially `git clone` this project
- optionally add your own remote repo (you don't need this as you can keep your changes in your local git)
- make changes / customize your mailcow and commit them locally and maybe also to your own remote repo
- regularly fetch the original / upstream remote repo to see if there are updates
- on updates merge your local and customized project into the remote / upstream branch
- if there are merge conflicts (there will be in case you changed a file and it also got changed since your last commit upstream) solve these conflicts

 A note on solving merge conflicts in case you are not familiar with it: With the right tools this is normally quite easy for this project. I can recommend PhpStorm or WebStorm or Sourcetree (as mere GUI for git) in combination with some of its supported Diff tools (see the list in "Options" -> "Diff").
